Repository hmcts/pip-frontend, pull requests merged in 2021-12, with the labels that each got.

#191 PUB-848 - National lists on the Alphabetical Search Page
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
  src/main/resources/locales/en/alphabetical-search.json
  src/main/views/alphabetical-search.njk
  src/test/unit/views/alphabetical-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-191

#192 PUB-952 - View option page radio buttons labels
  src/main/resources/locales/en/view-option.json
  src/main/views/view-option.njk
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-192

#195 PUB-955 - Bold radio options and hint change
  src/main/resources/locales/en/view-option.json
  src/main/views/view-option.njk
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-195

#197 PUB-848 - National lists on the Alphabetical Search Page
  src/main/resources/locales/en/alphabetical-search.json
  src/main/views/alphabetical-search.njk
  src/test/unit/views/alphabetical-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-197

#198 PUB-966 - Protect URN search and results routes
  src/main/resources/locales/en/view-option.json
  src/main/routes/routes.ts
  src/main/views/view-option.njk
  src/test/routes/subscriptionUrnSearch.test.ts
  src/test/routes/subscriptionUrnSearchResults.test.ts
  src/test/unit/views/subscription-urn-search-results.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-198

#194 PUB-935 - Reset filters on GET requests
  src/main/controllers/CourtNameSearchController.ts
  src/test/unit/controllers/CourtNameSearchController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-194

#193 PUB-884 - Back button on Live Case Alphabet Search
  src/main/views/live-case-status.njk
  src/test/unit/views/live-case-status.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-193

#199 PUB-967 - Missing banner on URN pages
  src/main/views/subscription-urn-search-results.njk
  src/main/views/subscription-urn-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-199

#200 PUB-964 - URN input error
  src/main/views/subscription-urn-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-200

#205 PUB-971: changes for master
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
  src/test/unit/views/home.test.ts
  src/test/unit/views/session-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-205

#185 PUB-932 e2e fixes
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  package.json
  src/main/routes/routes.ts
  src/main/views/case-event-glossary.njk
  src/main/views/live-case-status.njk
  src/main/views/session-management.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CaseEventGlossary.page.ts
  src/test/e2e/PageObjects/CaseNameSearch.page.ts
  src/test/e2e/PageObjects/CaseNameSearchResults.page.ts
  src/test/e2e/PageObjects/Common.page.ts
  src/test/e2e/PageObjects/CourtNameSearch.page.ts
  src/test/e2e/PageObjects/MockSession.page.ts
  src/test/e2e/PageObjects/SingleJusticeProcedure.page.ts
  src/test/e2e/PageObjects/SubscriptionAdd.page.ts
  src/test/e2e/pageobjects/AlphabeticalSearch.page.ts
  src/test/e2e/pageobjects/HearingList.page.ts
  src/test/e2e/pageobjects/Home.page.ts
  src/test/e2e/pageobjects/LiveCaseCourtSearchController.page.ts
  src/test/e2e/pageobjects/LiveCaseStatus.page.ts
  src/test/e2e/pageobjects/Search.page.ts
  src/test/e2e/pageobjects/SearchOptions.page.ts
  src/test/e2e/pageobjects/SubscriptionManagement.page.ts
  src/test/e2e/pageobjects/SubscriptionUrnSearch.page.ts
  src/test/e2e/pageobjects/SubscriptionUrnSearchResults.page.ts
  src/test/e2e/pageobjects/ViewOption.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/mock-login.test.ts
  src/test/unit/views/case-event-glossary.test.ts
  src/test/unit/views/live-case-status.test.ts
  wdio.conf.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-185

#207 PUB-980 - Update navigation links
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-207

#202 PUB-878 Added Redis credentials to frontend
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  docker-compose.yml
  src/main/assets/scss/main.scss
  src/main/cacheManager.ts
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
  src/test/unit/views/home.test.ts
  src/test/unit/views/session-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-202

#201 PUB-963 - Account Home page
  src/main/assets/scss/main.scss
  src/main/controllers/AccountHomeController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/account-home.json
  src/main/routes/routes.ts
  src/main/views/account-home.njk
  src/test/routes/account-home.test.ts
  src/test/unit/controllers/AccountHomeController.test.ts
  src/test/unit/views/account-home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-201

#209 Pub 866 - E2E on Jenkins (Recreated)
  README.md
  package.json
  run/package.json
  run/yarn.lock
  sonar-project.properties
  src/test/e2e/PageObjects/CaseReferenceNumberSearchResults.page.ts
  src/test/e2e/pageobjects/CaseEventGlossary.page.ts
  src/test/e2e/pageobjects/CaseNameSearch.page.ts
  src/test/e2e/pageobjects/CaseNameSearchResults.page.ts
  src/test/e2e/pageobjects/CaseReferenceNumberSearch.page.ts
  src/test/e2e/pageobjects/CaseReferenceNumberSearchResults.page.ts
  src/test/e2e/pageobjects/Common.page.ts
  src/test/e2e/pageobjects/CourtNameSearch.page.ts
  src/test/e2e/pageobjects/MockSession.page.ts
  src/test/e2e/pageobjects/SingleJusticeProcedure.page.ts
  src/test/e2e/pageobjects/SubscriptionAdd.page.ts
  src/test/e2e/pageobjects/SubscriptionManagement.page.ts
  src/test/e2e/tests/specs.test.ts
  tsconfig.e2e.json
  wdio.conf.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-209
