Repository hmcts/pip-frontend, pull requests merged in 2021-11, with the labels that each got.

#114 PUB-736: Build Subscriptions Case Name Search
  src/main/assets/scss/main.scss
  src/main/controllers/CaseNameSearchController.ts
  src/main/controllers/CaseNameSearchResultsController.ts
  src/main/controllers/SubscriptionAddController.ts
  src/main/models/court.ts
  src/main/models/hearing.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/case-name-search-results.json
  src/main/resources/locales/en/case-name-search.json
  src/main/resources/requests/hearingRequests.ts
  src/main/routes/routes.ts
  src/main/service/hearingService.ts
  src/main/views/case-name-search-results.njk
  src/main/views/case-name-search.njk
  src/main/views/subscription-management.njk
  src/test/a11y/case-name-search.test.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CaseNameSearch.page.ts
  src/test/e2e/PageObjects/CaseNameSearchResults.page.ts
  src/test/e2e/PageObjects/SubscriptionAdd.page.ts
  src/test/e2e/pageobjects/SubscriptionManagement.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/case-name-search-results.test.ts
  src/test/routes/case-name-search.test.ts
  src/test/routes/subscription-add.test.ts
  src/test/unit/controllers/CaseNameSearchController.test.ts
  src/test/unit/controllers/CaseNameSearchResultsController.test.ts
  src/test/unit/controllers/SubscriptionAddController.test.ts
  src/test/unit/requests/hearingRequests.test.ts
  src/test/unit/service/hearingService.test.ts
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/case-name-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-114

#129 PUB-721: Members of the public can view live case status updates online - screen 5 UI
  src/main/controllers/LiveCaseStatusController.ts
  src/main/controllers/StatusDescriptionController.ts
  src/main/resources/mocks/StatusDescription.json
  src/main/resources/requests/searchDescriptionRequests.ts
  src/main/routes/routes.ts
  src/main/service/courtService.ts
  src/main/service/statusDescriptionService.ts
  src/main/views/live-case-status.njk
  src/main/views/status-description.njk
  src/test/routes/status-description.ts
  src/test/unit/controllers/LiveCaseStatusController.test.ts
  src/test/unit/controllers/StatusDescriptionController.test.ts
  src/test/unit/mocks/StatusDescription.json
  src/test/unit/mocks/liveCaseStatusUpdates.json
  src/test/unit/requests/searchDescriptionRequests.test.ts
  src/test/unit/service/statusDescriptionService.test.ts
  src/test/unit/views/live-case-status.test.ts
  src/test/unit/views/status-description.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-129

#132 Pub-696 - added filter service to alphabetical search page
  package.json
  src/main/assets/scss/main.scss
  src/main/controllers/AlphabeticalSearchController.ts
  src/main/routes/routes.ts
  src/main/service/courtService.ts
  src/main/service/filterService.ts
  src/main/views/alphabetical-search.njk
  src/test/unit/controllers/AlphabeticalSearchController.test.ts
  src/test/unit/service/courtService.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-132

#133 Pub 721 latest master and use mock data
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/status-description.json
  src/main/resources/mocks/StatusDescription.json
  src/main/resources/requests/searchDescriptionRequests.ts
  src/main/views/status-description.njk
  src/test/unit/requests/searchDescriptionRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-133

#134 Revert "Pub 721 latest master and use mock data"
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/status-description.json
  src/main/resources/mocks/StatusDescription.json
  src/main/resources/requests/searchDescriptionRequests.ts
  src/main/views/status-description.njk
  src/test/unit/requests/searchDescriptionRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-134

#135 PUB 748 - Added Error colour and styling
  src/main/assets/scss/main.scss
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-135

#137 Content updates for UAT
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/hearing-list.json
  src/main/resources/locales/en/home.json
  src/main/resources/locales/en/live-case-status.json
  src/main/resources/locales/en/single-justice-procedure-search.json
  src/main/resources/locales/en/view-option.json
  src/main/views/live-case-status.njk
  src/main/views/search-option.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/hearing-list.test.ts
  src/test/unit/views/home.test.ts
  src/test/unit/views/live-case-status.test.ts
  src/test/unit/views/single-justice-procedure-search.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-137

#139 Fix - Court Search Counter
  src/main/views/court-name-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-139

#140 Fix: mock a11y api request for court events glossary
  src/main/resources/requests/statusDescriptionRequests.ts
  src/main/service/statusDescriptionService.ts
  src/test/a11y/a11y.ts
  src/test/unit/mocks/StatusDescription.json
  src/test/unit/requests/searchDescriptionRequests.test.ts
  src/test/unit/requests/statusDescriptionRequests.test.ts
  src/test/unit/service/statusDescriptionService.test.ts
  src/test/unit/views/status-description.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-140

#115 PUB-748: Authentication
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.prod.template.yaml
  charts/pip-frontend/values.stg.template.yaml
  charts/pip-frontend/values.yaml
  jest.a11y.config.js
  jest.config.js
  jest.routes.config.js
  jestEnvVars.js
  package.json
  src/main/app.ts
  src/main/authentication/authentication-config.json
  src/main/authentication/authentication.ts
  src/main/controllers/OtpLoginController.ts
  src/main/controllers/OtpTemplateController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/otp-login.json
  src/main/resources/locales/en/otp-template.json
  src/main/routes/routes.ts
  src/main/views/otp-login.njk
  src/main/views/otp-template.njk
  src/main/views/template.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/OtpLoginTesting.page.ts
  src/test/e2e/pageobjects/Home.page.ts
  src/test/e2e/pageobjects/OtpLogin.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/login.ts
  src/test/routes/otp-login.test.ts
  src/test/routes/subscription-management.test.ts
  src/test/unit/authentication/Authentication.test.ts
  src/test/unit/controllers/OtpLoginController.test.ts
  src/test/unit/controllers/OtpTemplateController.test.ts
  src/test/unit/controllers/SubscriptionManagementController.test.ts
  src/test/unit/views/otp-login.test.ts
  src/test/unit/views/otp-template.test.ts
  src/test/unit/views/subscription-management.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-115

#136 Pub 696 - filter for alphabet search
  src/main/controllers/AlphabeticalSearchController.ts
  src/main/controllers/CourtNameSearchController.ts
  src/main/resources/locales/en/alphabetical-search.json
  src/main/service/filterService.ts
  src/main/views/alphabetical-search.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/pageobjects/AlphabeticalSearch.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/alphabetical-search.ts
  src/test/unit/controllers/AlphabeticalSearchController.test.ts
  src/test/unit/controllers/CourtNameSearchController.test.ts
  src/test/unit/requests/courtRequests.test.ts
  src/test/unit/service/courtService.test.ts
  src/test/unit/service/filterService.test.ts
  src/test/unit/views/alphabetical-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-136

#142 PUB-857 - Added hint for radio button
  src/main/resources/locales/en/view-option.json
  src/main/views/view-option.njk
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-142

#149 PUB-833: Create ability for frontend mocking
  README.md
  docker-compose.yml
  package.json
  src/main/authentication/authentication.ts
  src/main/cacheManager.ts
  src/main/controllers/MockSessionController.ts
  src/main/controllers/SubscriptionManagementController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/session-management.json
  src/main/resources/requests/courtRequests.ts
  src/main/routes/routes.ts
  src/main/views/alphabetical-search.njk
  src/main/views/session-management.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/MockSession.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/case-name-search.test.ts
  src/test/routes/court-name-search.test.ts
  src/test/routes/subscription-add.test.ts
  src/test/unit/authentication/Authentication.test.ts
  src/test/unit/controllers/MockSessionController.test.ts
  src/test/unit/controllers/SubscriptionManagementController.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/requests/courtRequests.test.ts
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/case-name-search.test.ts
  src/test/unit/views/court-name-search.test.ts
  src/test/unit/views/subscription-add.test.ts
  src/test/unit/views/subscription-management.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-149

#141 PUB-856 Altered header text, added header and gov.uk links
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-141

#150 pub-833: remove production checks
  src/main/routes/routes.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-150

#144 PUB-860 - Replaced subscriptions button with sign-in button
  src/main/resources/locales/en/session-management.json
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/pageobjects/Home.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-144

#155 Unset OIDC in dev
  charts/pip-frontend/values.dev.template.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-155

#147 PUB-859 date formats
  src/main/controllers/LiveCaseStatusController.ts
  src/main/resources/locales/en/live-case-status.json
  src/main/views/live-case-status.njk
  src/test/unit/controllers/LiveCaseStatusController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-147

#152 Pub 768 list option for crown and mags
  src/main/controllers/ListOptionController.ts
  src/main/controllers/SearchController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/list-option.json
  src/main/routes/routes.ts
  src/main/views/alphabetical-search.njk
  src/main/views/list-option.njk
  src/test/routes/court-name-search.test.ts
  src/test/routes/list-option.test.ts
  src/test/unit/controllers/ListOptionController.test.ts
  src/test/unit/controllers/SearchController.test.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/service/filterService.test.ts
  src/test/unit/views/court-name-search.test.ts
  src/test/unit/views/list-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-152

#157 DEBUG for express session
  package.json
  src/main/app.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-157

#151 Pub 858 updates to header on list screens
  src/main/controllers/HearingListController.ts
  src/main/controllers/LiveCaseStatusController.ts
  src/main/views/hearing-list.njk
  src/test/unit/controllers/HearingListController.test.ts
  src/test/unit/controllers/LiveCaseStatusController.test.ts
  src/test/unit/views/hearing-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-151

#158 Pub 876 mock session updates
  src/main/resources/locales/en/session-management.json
  src/main/resources/locales/en/template.json
  src/main/routes/routes.ts
  src/main/views/session-management.njk
  src/main/views/template.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/routes/logout.test.ts
  src/test/unit/views/logout.test.ts
  src/test/unit/views/session-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-158

#159 Pub 666 standard list
  src/main/assets/scss/main.scss
  src/main/controllers/StandardListController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/standard-list.json
  src/main/routes/routes.ts
  src/main/views/list-option.njk
  src/main/views/standard-list.njk
  src/test/routes/court-name-search.test.ts
  src/test/routes/standard-list.test.ts
  src/test/unit/controllers/StandardListController.test.ts
  src/test/unit/views/list-option.test.ts
  src/test/unit/views/standard-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-159

#161 Staging Fix Auth
  package.json
  src/main/app.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-161

#154 PUB-670 - Warned List
  src/main/assets/scss/main.scss
  src/main/controllers/WarnedListController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/warned-list.json
  src/main/routes/routes.ts
  src/main/views/list-option.njk
  src/main/views/warned-list.njk
  src/test/routes/warned-list.test.ts
  src/test/unit/controllers/WarnedListController.test.ts
  src/test/unit/views/warned-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-154

#160 Pub-877: Signed in status updates
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/template.json
  src/main/views/alphabetical-search.njk
  src/main/views/case-name-search-results.njk
  src/main/views/case-name-search.njk
  src/main/views/court-name-search.njk
  src/main/views/error.njk
  src/main/views/hearing-list.njk
  src/main/views/home.njk
  src/main/views/list-option.njk
  src/main/views/live-case-alphabet-search.njk
  src/main/views/live-case-status.njk
  src/main/views/search-option.njk
  src/main/views/search.njk
  src/main/views/single-justice-procedure.njk
  src/main/views/status-description.njk
  src/main/views/subscription-add.njk
  src/main/views/subscription-management.njk
  src/main/views/template.njk
  src/main/views/view-option.njk
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-160

#162 Updated Mock Session Redirect + Logout
  src/main/routes/routes.ts
  src/test/unit/views/logout.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-162

#163 changed the links for account and subscriptions to point to prototype
  src/main/views/template.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-163

#138 Pub 721 use api to fetch data.
  src/main/controllers/CaseEventGlossaryController.ts
  src/main/controllers/StatusDescriptionController.ts
  src/main/resources/locales/en/case-event-glossary.json
  src/main/resources/mocks/StatusDescription.json
  src/main/resources/requests/caseEventGlossaryRequests.ts
  src/main/routes/routes.ts
  src/main/service/caseEventGlossaryService.ts
  src/main/service/statusDescriptionService.ts
  src/main/views/case-event-glossary.njk
  src/main/views/live-case-status.njk
  src/test/a11y/a11y.ts
  src/test/routes/case-event-glossary.ts
  src/test/unit/controllers/CaseEventGlossaryController.test.ts
  src/test/unit/controllers/StatusDescriptionController.test.ts
  src/test/unit/mocks/CaseEventGlossary.json
  src/test/unit/mocks/StatusDescription.json
  src/test/unit/requests/caseEventGlossaryRequests.test.ts
  src/test/unit/requests/statusDescriptionRequests.test.ts
  src/test/unit/service/caseEventGlossaryService.test.ts
  src/test/unit/service/statusDescriptionService.test.ts
  src/test/unit/views/case-event-glossary.test.ts
  src/test/unit/views/live-case-status.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-138

#164 pub-885: Error on returning to the A-Z from a list post filtering
  src/main/views/alphabetical-search.njk
  src/main/views/case-name-search-results.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-164

#148 Pub 735
  src/main/controllers/SubscriptionAddController.ts
  src/main/controllers/SubscriptionUrnSearchController.ts
  src/main/controllers/SubscriptionUrnSearchResultController.ts
  src/main/models/caseSubscription.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/subscription-urn-search-results.json
  src/main/resources/locales/en/subscription-urn-search.json
  src/main/resources/requests/subscriptionRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/routes/routes.ts
  src/main/service/courtService.ts
  src/main/service/subscriptionService.ts
  src/main/views/subscription-urn-search-results.njk
  src/main/views/subscription-urn-search.njk
  src/test/a11y/subscription-urn-search.test.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/SubscriptionAdd.page.ts
  src/test/e2e/pageobjects/AlphabeticalSearch.page.ts
  src/test/e2e/pageobjects/SearchOptions.page.ts
  src/test/e2e/pageobjects/SubscriptionUrnSearch.page.ts
  src/test/e2e/pageobjects/SubscriptionUrnSearchResults.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/court-name-search.test.ts
  src/test/routes/subscription-add.test.ts
  src/test/routes/subscriptionUrnSearch.test.ts
  src/test/routes/subscriptionUrnSearchResults.test.ts
  src/test/unit/controllers/SubscriptionAddController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchResultController.test.ts
  src/test/unit/mocks/subscriptionListResult.json
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/subscription-urn-search-results.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-148

#165 PUB-876 v2 - Removed unverified user radio option
  src/main/views/session-management.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-165

#153 Fix Environment Variables
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.prod.template.yaml
  charts/pip-frontend/values.stg.template.yaml
  charts/pip-frontend/values.yaml
  package.json
  src/main/app.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-153

#168 pub-902: Session set up improvements
  src/main/resources/locales/en/session-management.json
  src/main/routes/routes.ts
  src/main/views/session-management.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-168

#167 Updated typo's
  src/main/resources/locales/en/list-option.json
  src/main/resources/locales/en/standard-list.json
  src/main/resources/locales/en/view-option.json
  src/test/unit/views/list-option.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-167

#172 added a space to try retrigger master container rebuild
  src/main/views/session-management.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-172

#171 Pub-902
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
  src/main/authentication/authentication.ts
  src/main/routes/routes.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-171

#166 Pub-877: Signed in status updates
  src/main/views/standard-list.njk
  src/main/views/warned-list.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-166

#175 changed hint text for search
  src/main/resources/locales/en/search.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-175

#176 PUB-924: Accessibility timeout
  jest.a11y.config.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-176

#180 PUB-903 update infra to use new infra
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-180

#169 PUB-862 - Fix - display back to top button
  src/main/views/court-name-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-169

#178 PUB-933 Navigation bar not displayed on the POST requests
  src/main/routes/routes.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-178

#183 PUB-936 - Create build workflow for cloud scanner on PR build
  .github/workflows/build.yml
  sonar-project.properties
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-183

#182 PUB-936 workflow for github
  .github/workflows/main.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-182

#187 PUB-000 Pre release into master
  .github/workflows/build.yml
  .github/workflows/main.yml
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  jest.a11y.config.js
  sonar-project.properties
  src/main/app.ts
  src/main/routes/routes.ts
  src/main/views/court-name-search.njk
  wdio.conf.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-187

#188 PUB-883 - Change infra
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-188
