Repository hmcts/pip-frontend, pull requests merged in 2021-09, with the labels that each got.

#60 Correct the repo
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.yaml
  docker-compose.yml
Labels: ns:pip, rel:pip-frontend-pr-60, prd:pip

#63 pip-717: update dependencies to fix vulnerabilities found
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-63

#66 PUB-741-Added-Testing-Page-For-UI
  src/main/controllers/OtpLoginTestingController.ts
  src/main/routes/routes.ts
  src/main/views/otp-login-testing.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-66

#72 PUB 693 - UI OTP Update
  src/main/controllers/OtpLoginController.ts
  src/main/views/otp-login.njk
  src/test/unit/controllers/OtpLoginController.test.ts
  src/test/unit/views/otp-login.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-72

#76 update yarn.lock file to fix the build
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-76

#77 Pub 729 jsonarray
  src/main/service/inputFilterService.ts
  src/test/unit/service/inputFilterService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-77

#62 Pub 695
  .eslintrc.js
  jest-puppeteer.config.js
  package.json
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AlphabeticalSearch.po.ts
  src/test/e2e/PageObjects/HearingList.po.ts
  src/test/e2e/PageObjects/HomePage.po.ts
  src/test/e2e/PageObjects/OtpLogin.page.ts
  src/test/e2e/PageObjects/OtpLoginPage.po.ts
  src/test/e2e/PageObjects/Search.po.ts
  src/test/e2e/PageObjects/SearchOption.po.ts
  src/test/e2e/PageObjects/SearchResults.po.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.po.ts
  src/test/e2e/Tests/e2e.test.ts
  src/test/e2e/pageobjects/AlphabeticalSearch.page.ts
  src/test/e2e/pageobjects/HearingList.page.ts
  src/test/e2e/pageobjects/Home.page.ts
  src/test/e2e/pageobjects/Search.page.ts
  src/test/e2e/pageobjects/SearchOptions.page.ts
  src/test/e2e/pageobjects/SearchResults.page.ts
  src/test/e2e/tests/specs.test.ts
  tsconfig.e2e.json
  tsconfig.json
  wdio.conf.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-62

#80 Updated sonar project name to be more specific
  sonar-project.properties
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-80

#84 PUB-740: Added subscription button in header
  src/main/views/template.njk
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-84

#78 pub-720: Add Live Status Hearing Updated View
  src/main/assets/scss/main.scss
  src/main/controllers/LiveCaseStatusController.ts
  src/main/resources/actions/liveCaseActions.ts
  src/main/resources/mocks/liveCaseStatusUpdates.json
  src/main/routes/routes.ts
  src/main/views/live-case-alphabet-search.njk
  src/main/views/live-case-status.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/LiveCaseCourtSearchController.page.ts
  src/test/e2e/PageObjects/LiveCaseStatus.page.ts
  src/test/e2e/pageobjects/AlphabeticalSearch.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/live-case-status.test.ts
  src/test/unit/actions/liveCaseActions/liveCase.test.ts
  src/test/unit/controllers/LiveCaseStatusController.test.ts
  src/test/unit/views/live-case-alphabet-search.test.ts
  src/test/unit/views/live-case-status.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-78

#59 pip-659 - Created api util - use of the api to gather data for each …
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  jest.a11y.config.js
  jest.config.js
  package-lock.json
  package.json
  run/package.json
  run/yarn.lock
  src/main/controllers/AlphabeticalSearchController.ts
  src/main/controllers/HearingListController.ts
  src/main/controllers/LiveCaseCourtSearchController.ts
  src/main/controllers/LocalApiController.ts
  src/main/controllers/SearchController.ts
  src/main/controllers/SearchResultsController.ts
  src/main/models/court.ts
  src/main/modules/awilix/index.ts
  src/main/resources/actions/courtActions.ts
  src/main/resources/actions/hearingActions.ts
  src/main/resources/mocks/courtAndHearings.json
  src/main/resources/mocks/courtAndHearings2.json
  src/main/resources/mocks/courtsAllReduced.json
  src/main/resources/mocks/courtsAllReducedForInputSearch.json
  src/main/resources/mocks/courtsAndHearingsCount.json
  src/main/resources/mocks/hearingsList.json
  src/main/resources/mocks/hearingsListByCourt.json
  src/main/routes/routes.ts
  src/main/service/courtService.ts
  src/main/service/inputFilterService.ts
  src/main/utils/PipApi.ts
  src/main/views/hearing-list.njk
  src/test/a11y/a11y.ts
  src/test/e2e/pageobjects/LiveCaseCourtSearchController.page.ts
  src/test/e2e/pageobjects/LiveCaseStatus.page.ts
  src/test/e2e/pageobjects/OtpLogin.page.ts
  src/test/e2e/pageobjects/SubscriptionManagement.page.ts
  src/test/e2e/pageobjects/ViewOption.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/actions/courtActions/court.test.ts
  src/test/unit/actions/hearingActions/hearing.test.ts
  src/test/unit/controllers/AlphabeticalSearchController.ts
  src/test/unit/controllers/HearingListController.test.ts
  src/test/unit/controllers/LiveCaseCourtSearchController.test.ts
  src/test/unit/controllers/LocalApiController.ts
  src/test/unit/controllers/SearchController.test.ts
  src/test/unit/controllers/SearchResultsController.test.ts
  src/test/unit/service/courtService.test.ts
  src/test/unit/service/inputFilterService.test.ts
  src/test/unit/utils/PipApi.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/hearing-list.test.ts
  src/test/unit/views/live-case-alphabet-search.test.ts
  src/test/unit/views/search-results.test.ts
  src/test/unit/views/search.test.ts
  wdio.conf.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-59

#89 PUB-740: Added e2e test for subscriptions button
  src/main/views/template.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/OtpLoginTesting.page.ts
  src/test/e2e/pageobjects/Home.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-89

#91 change page type
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-91
