Repository hmcts/pip-frontend, pull requests merged in 2021-10, with the labels that each got.

#93 Setup communication front end and business rules
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-93

#103 PUB 748 - Styling changes to Azure Logon
  src/main/assets/scss/main.scss
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-103

#109 Pub 748 OTP UI
  src/main/assets/scss/main.scss
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-109

#88 pub-744: my subscriptions
  .eslintignore
  .gitignore
  package.json
  src/main/assets/js/jquery.js
  src/main/assets/js/mojAll.js
  src/main/assets/scss/main.scss
  src/main/controllers/SubscriptionManagementController.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/actions/subscriptionActions.ts
  src/main/resources/mocks/userSubscriptions.json
  src/main/service/subscriptionService.ts
  src/main/views/subscription-management.njk
  src/main/views/template.njk
  src/test/e2e/tests/specs.test.ts
  src/test/routes/subscription-management.test.ts
  src/test/unit/actions/subscriptionActions/subscription.test.ts
  src/test/unit/controllers/SubscriptionManagementController.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/subscription-management.test.ts
  webpack.config.js
  webpack/ministryOfJusticeFrontend.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-88

#106 PUB-778 - Fixed overlapping menu buttons
  src/main/assets/scss/main.scss
  src/main/views/alphabetical-search.njk
  src/main/views/live-case-alphabet-search.njk
  src/main/views/search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-106
