Repository hmcts/pip-frontend, pull requests merged in 2022-08, with the labels that each got.

#486 PUB-1478 Update Logging
  src/main/controllers/CreateAdminAccountSummaryController.ts
  src/main/controllers/MediaAccountApprovalController.ts
  src/main/controllers/MediaAccountRejectionController.ts
  src/main/controllers/RemoveListConfirmationController.ts
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/dataManagementRequests.ts
  src/main/resources/requests/publicationRequests.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/main/service/mediaAccountApplicationService.ts
  src/main/service/publicationService.ts
  src/test/routes/remove-list-confirmation.test.ts
  src/test/unit/controllers/CreateAdminAccountSummaryController.test.ts
  src/test/unit/controllers/MediaAccountApprovalController.test.ts
  src/test/unit/controllers/MediaAccountRejectionController.test.ts
  src/test/unit/controllers/RemoveListConfrimationController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-486

#469 PUB-1416 Add additional route and passport strategy for admin login
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
  src/main/authentication/authentication.ts
  src/main/authentication/authenticationHandler.ts
  src/main/routes/routes.ts
  src/test/a11y/a11y.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/mock-login.test.ts
  src/test/unit/authentication/Authentication.test.ts
  src/test/unit/authentication/authenticationHandler.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-469

#487 PUB-1496 - Fix missing banner option
  src/main/views/template.njk
  src/test/unit/views/admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-487

#493 Updated / Fixed vulnurabilities
  package.json
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/delete-subscription.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-493

#491 PUB-1333 - Updated so that route tests run on pipeline
  README.md
  package.json
  src/main/controllers/DailyCauseListController.ts
  src/test/routes/alphabetical-search.ts
  src/test/routes/case-event-glossary.ts
  src/test/routes/case-name-search-results.test.ts
  src/test/routes/case-name-search.test.ts
  src/test/routes/case-reference-number-search-results.test.ts
  src/test/routes/case-reference-number-search.test.ts
  src/test/routes/civil-and-family-daily-cause-list.test.ts
  src/test/routes/cop-daily-cause-list.test.ts
  src/test/routes/daily-cause-list.test.ts
  src/test/routes/family-daily-cause-list.test.ts
  src/test/routes/list-option.test.ts
  src/test/routes/media-account-approval.test.ts
  src/test/routes/media-account-rejection.test.ts
  src/test/routes/media-account-review.test.ts
  src/test/routes/media-applications.test.ts
  src/test/routes/sign-in.test.ts
  src/test/routes/single-justice-procedure-press.test.ts
  src/test/routes/sscs-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-491

#492 PUB-1366 - Case Name 3 characters
  src/main/controllers/CaseNameSearchController.ts
  src/main/resources/locales/cy/case-name-search.json
  src/main/resources/locales/en/case-name-search.json
  src/main/views/case-name-search.njk
  src/test/unit/controllers/CaseNameSearchController.test.ts
  src/test/unit/views/case-name-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-492

#489 PUB-1493 secure cookies
  src/main/app.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-489

#504 Fixed E2E tests
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-504

#499 PUB-1518 Temp remove create account link
  src/main/views/sign-in.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-499

#507 Fixed E2E tests
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-507

#494 PUB-1505 Sort summary of publications by content date followed by alphabetical order of list type
  src/main/views/summary-of-publications.njk
  src/test/unit/mocks/summaryOfPublications.json
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/views/publication.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-494

#495 Pub 1431 increase admin screen timeout
  src/main/authentication/authenticationHandler.ts
  src/main/routes/routes.ts
  src/test/unit/authentication/authenticationHandler.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-495

#509 Updated consts file
  src/main/models/consts.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-509

#497 PUB 1318 Media verification flow
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.stg.template.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
  src/main/authentication/authentication.ts
  src/main/authentication/authenticationHandler.ts
  src/main/controllers/AccountHomeController.ts
  src/main/resources/locales/en/account-home.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/views/account-home.njk
  src/test/a11y/a11y.ts
  src/test/unit/authentication/Authentication.test.ts
  src/test/unit/authentication/authenticationHandler.test.ts
  src/test/unit/controllers/AccountHomeController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/views/account-home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-497

#513 PUB-1523 Destroy request session after logged out
  src/main/service/sessionManagementService.ts
  src/test/unit/service/sessionManagementService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-513

#515 Code clean up
  src/main/controllers/OtpTemplateController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/otp-template.json
  src/main/routes/routes.ts
  src/main/views/otp-template.njk
  src/test/unit/controllers/OtpTemplateController.test.ts
  src/test/unit/views/otp-template.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-515
