Repository hmcts/pip-frontend, pull requests merged in 2022-07, with the labels that each got.

#441 PUB-1336 Civil and family cause list
  src/main/modules/nunjucks/listTypeLookup.json
  src/main/modules/nunjucks/listUrlLookup.json
  src/main/resources/locales/cy/civil-and-family-daily-cause-list.json
  src/main/resources/locales/en/civil-and-family-daily-cause-list.json
  src/main/routes/routes.ts
  src/main/service/manualUploadService.ts
  src/main/views/civil-and-family-daily-cause-list.njk
  src/test/routes/civil-and-family-daily-cause-list.test.ts
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-441

#442 PUB-1412 Remove the cache for location information
  src/main/resources/requests/locationRequests.ts
  src/test/unit/requests/locationRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-442

#439 PUB-1419 PartyRole mappings
  src/main/models/consts.ts
  src/main/service/publicationService.ts
  src/test/unit/mocks/familyDailyCauseListPartyMapping.json
  src/test/unit/service/publicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-439

#445 PUB-1428 Unshuttering Changes
  src/main/resources/locales/en/search.json
  src/main/views/home.njk
  src/main/views/template.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/assets/banner.tests.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-445

#452 Fix the build pipeline
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-452

#446 Pub 1421 welsh sum of pubs
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/languageLookup.json
  src/main/views/summary-of-publications.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-446

#450 PUB-1392 - Reset Password Custom Policy
  package.json
  src/main/authentication/adminAuthentication.ts
  src/main/authentication/authentication-config.json
  src/main/controllers/PasswordChangeController.ts
  src/main/resources/locales/en/password-change-confirmation.json
  src/main/routes/routes.ts
  src/main/views/password-change-confirmation.njk
  src/test/routes/login.test.ts
  src/test/routes/password-change-confirmation.test.ts
  src/test/unit/authentication/adminAuthentication.test.ts
  src/test/unit/controllers/PasswordChangeController.test.ts
  src/test/unit/views/password-change-confirmation.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-450

#456 Pub 1392 extensions
  src/main/authentication/adminAuthentication.ts
  src/main/views/password-change-confirmation.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-456

#455 PUB-1449 Fix bug with Duration on all daily lists
  src/main/service/publicationService.ts
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/service/publicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-455

#449 PUB-1389 Correct link to SJP cases from the account-home screen
  src/main/resources/locales/en/account-home.json
  src/test/unit/views/account-home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-449

#457 Fix Civil and Family Caused list bug
  src/main/service/publicationService.ts
  src/main/views/daily-cause-list.njk
  src/test/unit/views/daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-457

#453 PUB 1276 - Welsh translation for court page
  src/main/controllers/AlphabeticalSearchController.ts
  src/main/controllers/LiveCaseCourtSearchController.ts
  src/main/controllers/ManualUploadController.ts
  src/main/controllers/RemoveListSearchController.ts
  src/main/controllers/SearchController.ts
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/models/location.ts
  src/main/resources/requests/locationRequests.ts
  src/main/service/filterService.ts
  src/main/service/locationService.ts
  src/main/service/manualUploadService.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/requests/locationRequests.test.ts
  src/test/unit/service/filterService.test.ts
  src/test/unit/service/locationService.test.ts
  src/test/unit/service/manualUploadService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-453

#459 PUB-1396-Multi-Day-Sequence-Number-Style
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/daily-cause-list.njk
  src/main/views/family-daily-cause-list.njk
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-459

#468 fixed vulns
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-468

#464 PUB-1450 Update E2E test court
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-464

#473 Suppress the vulns
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-473

#465 PUB-1467 Session cookie secure
  src/main/app.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-465

#476 Fix the E2Es
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-476

#466 PUB-1458 Footer link update
  src/main/views/template.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-466

#471 PUB-1465 Update yaml with b2c url
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/authentication/authenticationHandler.ts
  src/main/routes/routes.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-471

#479 Fix Passport Vulnurability
  charts/pip-frontend/Chart.yaml
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-479

#470 PUB-1454 Add descriptions for non-SJP service offering
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/cy/search.json
  src/main/resources/locales/en/search.json
  src/main/views/home.njk
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-470

#472 PUB-1326 - Content changes for manual upload / remove pages
  src/main/controllers/FileUploadConfirmationController.ts
  src/main/resources/locales/en/file-upload-confirm.json
  src/main/resources/locales/en/manual-upload.json
  src/main/resources/locales/en/remove-list-success.json
  src/main/service/manualUploadService.ts
  src/main/views/file-upload-confirm.njk
  src/main/views/manual-upload.njk
  src/test/unit/controllers/FileUploadConfirmationController.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/views/file-upload-confirm.test.ts
  src/test/unit/views/manual-upload.test.ts
  src/test/unit/views/remove-list-success.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-472

#461 PUB-1297 Fix back to top on Home page
  src/main/assets/scss/main.scss
  src/main/views/home.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-461

#463 PUB-1247 Cop Daily Cause list
  src/main/controllers/CopDailyCauseListController.ts
  src/main/modules/nunjucks/listTypeLookup.json
  src/main/modules/nunjucks/listUrlLookup.json
  src/main/resources/locales/bill/cop-daily-cause-list.json
  src/main/resources/locales/cy/cop-daily-cause-list.json
  src/main/resources/locales/en/cop-daily-cause-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/service/manualUploadService.ts
  src/main/views/cop-daily-cause-list.njk
  src/test/routes/cop-daily-cause-list.test.ts
  src/test/unit/controllers/CopDailyCauseListController.test.ts
  src/test/unit/mocks/copDailyCauseList.json
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/views/cop-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-463

#480 readme change
  README.md
  src/main/app.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-480

#474 PUB-1462 Admin Media User Account Reject Screen Content changes
  src/main/resources/locales/en/media-account-rejection-confirmation.json
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/media-account-rejection-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-474

#484 PUB-1459 - Radio Button Content Change
  src/main/resources/locales/en/sign-in.json
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-484

#482 PUB 1457 - Lower case A
  src/main/modules/nunjucks/listTypeLookup.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-482

#485 PUB-1492
  jest.a11y.config.js
  src/main/views/media-account-approval-confirmation.njk
  src/test/unit/views/media-account-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-485

#477 PUB-1463 - Updated special characters
  src/main/controllers/ManualUploadController.ts
  src/main/service/fileHandlingService.ts
  src/test/unit/controllers/ManualUploadController.test.ts
  src/test/unit/service/fileHandlingService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-477

#467 PUB-1461 Remove pending statement text
  src/main/resources/locales/cy/pending-subscriptions.json
  src/main/resources/locales/en/pending-subscriptions.json
  src/main/views/pending-subscriptions.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-467

#483 PUB 1475 - "admin dashboard" to "your dashboard"
  src/main/resources/locales/en/admin-dashboard.json
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-483

#481 PUB 1484 overwritten parties fix
  src/main/service/dataManipulationService.ts
  src/test/unit/mocks/familyDailyCauseListWithReorderedPartyMappings.json
  src/test/unit/service/dataManipulationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-481
