Repository hmcts/pip-frontend, pull requests merged in 2022-04, with the labels that each got.

#334 PUB-1206 - Summary of Publications Changes
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/summary-of-publications.json
  src/main/views/summary-of-publications.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-334

#338 Fix demo issues
  src/main/routes/routes.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-338

#335 PUB-1167 - Update text on courts search page
  README.md
  src/main/resources/locales/en/search.json
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-335

#327 PUB-1158 - Remove content under continue button
  src/main/resources/locales/en/view-option.json
  src/main/views/view-option.njk
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-327

#322 PUB-1171 - Publication Date
  src/main/controllers/SjpPublicListController.ts
  src/main/resources/locales/en/single-justice-procedure.json
  src/main/views/single-justice-procedure.njk
  src/test/unit/controllers/SJPPublicListController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-322

#339 Fix secret
  README.md
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/authentication/authRedirect.ts
  src/test/unit/authentication/authRedirect.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-339

#336 PUB-1196 - Update to h2 element for search page
  src/main/views/search.njk
  src/test/unit/views/search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-336

#340 Update Secrets Names
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/authentication/authRedirect.ts
  src/test/unit/authentication/authRedirect.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-340

#337 PUB-1168 - Filter order
  src/main/service/filterService.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/service/filterService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-337

#306 PUB-1055 - Create Admin Account
  src/main/controllers/CreateAdminAccountController.ts
  src/main/controllers/CreateAdminAccountSummaryController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/admin-dashboard.json
  src/main/resources/locales/en/create-admin-account-summary.json
  src/main/resources/locales/en/create-admin-account.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/routes/routes.ts
  src/main/service/createAccountService.ts
  src/main/views/create-admin-account-summary.njk
  src/main/views/create-admin-account.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AdminDashboard.page.ts
  src/test/e2e/PageObjects/CreateAdminAccount.page.ts
  src/test/e2e/PageObjects/CreateAdminAccountSummary.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/create-admin-account-summary.test.ts
  src/test/routes/create-admin-account.test.ts
  src/test/unit/controllers/CreateAdminAccountController.test.ts
  src/test/unit/controllers/CreateAdminAccountSummaryController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/views/admin-dashboard.test.ts
  src/test/unit/views/create-admin-account-summary.test.ts
  src/test/unit/views/create-admin-account.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-306

#349 Fix async dependency
  package.json
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-349

#351 update node version
  Dockerfile
  README.md
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-351

#341 PUB-1211 Daily Cause List Version2
  package.json
  src/main/controllers/DailyCauseListController.ts
  src/main/resources/locales/en/daily-cause-list.json
  src/main/service/publicationService.ts
  src/main/views/daily-cause-list.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-341

#346 PUB-1170 Rename SJP court
  src/test/e2e/PageObjects/AdminDashboard.page.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-346

#353 Pub 1169 filter pod fix
  src/main/controllers/AlphabeticalSearchController.ts
  src/main/controllers/CourtNameSearchController.ts
  src/main/routes/routes.ts
  src/main/service/filterService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/court-name-search.njk
  src/test/routes/alphabetical-search.ts
  src/test/routes/court-name-search.test.ts
  src/test/unit/controllers/AlphabeticalSearchController.test.ts
  src/test/unit/controllers/CourtNameSearchController.test.ts
  src/test/unit/service/filterService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-353

#342 PUB-1221 - Update focussing
  src/main/views/alphabetical-search.njk
  src/main/views/court-name-search.njk
  src/main/views/search.njk
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/service/publicationService.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-342

#359 PUB-1256 Cookies page update
  README.md
  src/main/resources/locales/en/cookies.json
  src/main/views/cookies.njk
  src/test/unit/views/cookies-page.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-359

#344 PUB-1113 Updated dependencies
  .nvmrc
  package.json
  src/test/unit/controllers/ManualUploadSummaryController.test.ts
  src/test/unit/controllers/SubscriptionConfirmedController.test.ts
  src/test/unit/controllers/SubscriptionManagementController.test.ts
  src/test/unit/requests/courtRequests.test.ts
  src/test/unit/requests/dataManagementRequests.test.ts
  src/test/unit/requests/hearingRequests.test.ts
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/views/publication.test.ts
  webpack.config.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-344

#363 PUB-1060 Admin upload screen warning
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/manual-upload.json
  src/main/views/manual-upload.njk
  src/test/unit/views/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-363

#364 PUB-1172 Admin upload screen help text
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/manual-upload.json
  src/main/views/manual-upload.njk
  src/test/unit/views/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-364

#365 PUB-1102 Added unit tests to SJP Public List (super old ticket)
  src/test/unit/mocks/sjp-public-list.json
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-365

#356 PUB-1205 Screen Reader Tweaks
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/court-name-search.json
  src/main/views/alphabetical-search.njk
  src/main/views/court-name-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-356

#361 PUB-1208 - beta heading added to interstitial and template
  README.md
  src/main/resources/locales/en/interstitial.json
  src/main/resources/locales/en/template.json
  src/main/views/interstitial.njk
  src/main/views/template.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/unit/views/hearing-list.test.ts
  src/test/unit/views/interstitial.test.ts
  src/test/unit/views/live-case-status.test.ts
  src/test/unit/views/manual-upload.test.ts
  src/test/unit/views/remove-list-success.test.ts
  src/test/unit/views/sign-in.test.ts
  src/test/unit/views/success-view.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-361
