Repository hmcts/pip-frontend, pull requests merged in 2022-05, with the labels that each got.

#367 PUB-1270 - Updated messaging
  src/main/resources/locales/en/create-media-account.json
  src/main/views/create-media-account.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/create-media-account.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-367

#360 PUB 1084 - service to service
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  package.json
  src/main/resources/requests/dataManagementRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/test/unit/requests/dataManagementRequests.test.ts
  src/test/unit/resources/requests/utils/axiosConfigTest.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-360

#350 PUB-1210 Remove Duplicate Results on Case Search Page
  src/main/service/publicationService.ts
  src/test/unit/service/publicationService.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-350

#369 PUB 1249 navbar update
  src/main/views/template.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/unit/assets/banner.tests.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-369

#312 PUB-1166 added BtT to template and extended all components need from it
  src/main/assets/scss/main.scss
  src/main/controllers/CookiePolicyPageController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/cookie-policy.json
  src/main/resources/requests/publicationRequests.ts
  src/main/routes/routes.ts
  src/main/views/account-home.njk
  src/main/views/account-request-submitted.njk
  src/main/views/admin-dashboard.njk
  src/main/views/alphabetical-search.njk
  src/main/views/case-event-glossary.njk
  src/main/views/case-name-search-results.njk
  src/main/views/case-name-search.njk
  src/main/views/case-reference-number-search-results.njk
  src/main/views/case-reference-number-search.njk
  src/main/views/cookie-policy.njk
  src/main/views/court-name-search.njk
  src/main/views/create-media-account.njk
  src/main/views/daily-cause-list.njk
  src/main/views/delete-subscription.njk
  src/main/views/file-upload-summary.njk
  src/main/views/hearing-list.njk
  src/main/views/interstitial.njk
  src/main/views/live-case-alphabet-search.njk
  src/main/views/live-case-status.njk
  src/main/views/pending-subscriptions.njk
  src/main/views/remove-list-search.njk
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/main/views/standard-list.njk
  src/main/views/subscription-add.njk
  src/main/views/subscription-confirmed.njk
  src/main/views/subscription-management.njk
  src/main/views/subscription-urn-search-results.njk
  src/main/views/subscription-urn-search.njk
  src/main/views/success-view.njk
  src/main/views/summary-of-publications.njk
  src/main/views/template.njk
  src/main/views/unsubscribe-confirmation.njk
  src/main/views/warned-list.njk
  src/test/e2e/PageObjects/Common.page.ts
  src/test/e2e/PageObjects/CreateMediaAccount.page.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/unit/controllers/CookiePolicyController.test.ts
  src/test/unit/views/live-case-status.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-312

#343 Pub 1153 filter name update
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/court-name-search.json
  src/main/service/filterService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/court-name-search.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CourtNameSearch.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/service/filterService.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/court-name-search.test.ts
  src/test/unit/views/remove-list-confirmation.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-343

#370 PUB-1068 - Add PR URL to B2C reply URLs
  .github/workflows/close-pr.yml
  .github/workflows/on-pr.yml
  Jenkinsfile_CNP
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-370

#379 PUB-1068 - Correct close script
  .github/workflows/close-pr.yml
  .github/workflows/on-pr.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-379

#368 Pub 1160 accessibility statement page
  src/main/controllers/AccessibilityStatementController.ts
  src/main/resources/locales/en/accessibility-statement.json
  src/main/resources/locales/en/template.json
  src/main/routes/routes.ts
  src/main/views/accessibility-statement.njk
  src/test/routes/accessibility-statement.test.ts
  src/test/unit/controllers/AccessibilityStatementController.test.ts
  src/test/unit/views/accessibility-statement.test.ts
  src/test/unit/views/interstitial.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-368

#373 Pub 1155 welsh translations
  src/main/resources/locales/cy/alphabetical-search.json
  src/main/resources/locales/cy/daily-cause-list.json
  src/main/resources/locales/cy/error.json
  src/main/resources/locales/cy/family-daily-cause-list.json
  src/main/resources/locales/cy/interstitial.json
  src/main/resources/locales/cy/not-found.json
  src/main/resources/locales/cy/search.json
  src/main/resources/locales/cy/single-justice-procedure-press.json
  src/main/resources/locales/cy/single-justice-procedure.json
  src/main/resources/locales/cy/summary-of-publications.json
  src/main/resources/locales/cy/template.json
  src/main/resources/locales/cy/view-option.json
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/court-name-search.json
  src/main/resources/locales/en/template.json
  src/main/service/filterService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/case-name-search-results.njk
  src/main/views/case-name-search.njk
  src/main/views/case-reference-number-search-results.njk
  src/main/views/case-reference-number-search.njk
  src/main/views/court-name-search.njk
  src/main/views/create-admin-account.njk
  src/main/views/create-media-account.njk
  src/main/views/delete-subscription.njk
  src/main/views/manual-upload.njk
  src/main/views/remove-list-confirmation.njk
  src/main/views/remove-list-search.njk
  src/main/views/search.njk
  src/main/views/sign-in.njk
  src/main/views/subscription-add.njk
  src/main/views/subscription-urn-search-results.njk
  src/main/views/subscription-urn-search.njk
  src/main/views/template.njk
  src/main/views/view-option.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/unit/service/filterService.test.ts
  src/test/unit/views/court-name-search.test.ts
  src/test/unit/views/interstitial.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-373

#383 PUB-961 - Updated B2C values
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  config/test.json
  src/main/authentication/authRedirect.ts
  src/main/authentication/authentication-config.json
  src/main/authentication/authentication.ts
  src/main/routes/routes.ts
  src/test/unit/authentication/Authentication.test.ts
  src/test/unit/authentication/authRedirect.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-383

#371 PUB-1259 Addition of court sections
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/daily-cause-list.json
  src/main/resources/locales/en/family-daily-cause-list.json
  src/main/views/daily-cause-list.njk
  src/main/views/family-daily-cause-list.njk
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
  webpack/scss.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-371

#372 PUB-1268 - Adding link and welsh to beta heading
  README.md
  src/main/resources/locales/cy/interstitial.json
  src/main/resources/locales/cy/template.json
  src/main/resources/locales/en/interstitial.json
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
  src/test/unit/views/interstitial.test.ts
  src/test/unit/views/remove-list-search.test.ts
  src/test/unit/views/search.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-372

#375 added user email to the request of manual upload for auditing
  src/main/controllers/ManualUploadSummaryController.ts
  src/main/service/manualUploadService.ts
  src/test/routes/manual-upload-summary.test.ts
  src/test/routes/manual-upload.test.ts
  src/test/unit/controllers/ManualUploadSummaryController.test.ts
  src/test/unit/service/manualUploadService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-375

#389 Pub 1248/1220 update Subs summary screen and add another subscription link
  src/main/resources/locales/en/pending-subscriptions.json
  src/main/resources/locales/en/subscription-management.json
  src/main/views/pending-subscriptions.njk
  src/main/views/subscription-management.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-389

#388 PUB-1251 - Updated subscription confirmation screen
  src/main/resources/locales/en/subscription-confirmed.json
  src/main/views/subscription-confirmed.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/subscription-confirmed.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-388

#376 PUB-1050 Admin Login Page
  Jenkinsfile_CNP
  src/main/authentication/adminAuthentication.ts
  src/main/authentication/authentication-config.json
  src/main/routes/routes.ts
  src/test/a11y/a11y.ts
  src/test/e2e/PageObjects/AdminDashboard.page.ts
  src/test/e2e/PageObjects/SignIn.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/admin-dashboard.test.ts
  src/test/routes/create-admin-account-summary.test.ts
  src/test/routes/create-admin-account.test.ts
  src/test/routes/manual-upload-summary.test.ts
  src/test/routes/manual-upload.test.ts
  src/test/routes/unsubscribe-confirmation.test.ts
  src/test/routes/upload-confirmation.test.ts
  src/test/unit/authentication/adminAuthentication.test.ts
  src/test/unit/views/admin-dashboard.test.ts
  src/test/unit/views/create-admin-account-summary.test.ts
  src/test/unit/views/create-admin-account.test.ts
  src/test/unit/views/file-upload-summary.test.ts
  src/test/unit/views/manual-upload.test.ts
  src/test/unit/views/success-view.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-376

#380 Pub 1063 media applications view
  src/main/controllers/MediaApplicationsController.ts
  src/main/models/MediaAccountApplication.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/admin-dashboard.json
  src/main/resources/locales/en/media-applications.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/service/mediaApplicationService.ts
  src/main/views/media-applications.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AdminDashboard.page.ts
  src/test/e2e/PageObjects/MediaAccountRequests.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/media-applications.test.ts
  src/test/unit/controllers/MediaApplicationsController.test.ts
  src/test/unit/mocks/mediaApplications.json
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/mediaApplicationService.test.ts
  src/test/unit/views/admin-dashboard.test.ts
  src/test/unit/views/media-applications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-380

#378 PUB-1064 - Create Media Account Review Screen
  src/main/assets/scss/main.scss
  src/main/controllers/MediaAccountReviewController.ts
  src/main/models/consts.ts
  src/main/models/mediaAccount.ts
  src/main/resources/locales/en/media-account-review.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/service/mediaAccountApplicationService.ts
  src/main/views/media-account-review.njk
  src/test/routes/media-account-review.test.ts
  src/test/unit/controllers/MediaAccountReviewController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/mediaAccountApplicationService.ts
  src/test/unit/views/media-account-review.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-378

#381 Pub 1095 post application to backend
  manualUpload/tmp/testImage.png
  src/main/controllers/CreateMediaAccountController.ts
  src/main/controllers/ManualUploadController.ts
  src/main/controllers/ManualUploadSummaryController.ts
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/routes/routes.ts
  src/main/service/createAccountService.ts
  src/main/service/fileHandlingService.ts
  src/main/service/manualUploadService.ts
  src/main/views/create-media-account.njk
  src/test/routes/manual-upload-summary.test.ts
  src/test/routes/manual-upload.test.ts
  src/test/unit/controllers/CreateMediaAccountController.test.ts
  src/test/unit/controllers/ManualUploadController.test.ts
  src/test/unit/controllers/ManualUploadSummaryController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/service/fileHandlingService.test.ts
  src/test/unit/service/manualUploadService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-381

#393 Pub 1116 Error handling on create media account page
  src/main/models/consts.ts
  src/main/resources/locales/en/create-media-account.json
  src/main/service/createAccountService.ts
  src/main/service/fileHandlingService.ts
  src/main/views/account-request-submitted.njk
  src/main/views/create-media-account.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/service/fileHandlingService.test.ts
  src/test/unit/views/create-media-account.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-393

#397 Superagent / issue fix
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-397

#394 PUB-1204 - Updated page titles
  src/main/controllers/StandardListController.ts
  src/main/controllers/WarnedListController.ts
  src/main/resources/locales/en/account-request-submitted.json
  src/main/resources/locales/en/admin-dashboard.json
  src/main/resources/locales/en/case-name-search-results.json
  src/main/resources/locales/en/case-name-search.json
  src/main/resources/locales/en/case-reference-number-search-results.json
  src/main/resources/locales/en/case-reference-number-search.json
  src/main/resources/locales/en/create-media-account.json
  src/main/resources/locales/en/sign-in.json
  src/main/resources/locales/en/standard-list.json
  src/main/resources/locales/en/subscription-urn-search-results.json
  src/main/resources/locales/en/subscription-urn-search.json
  src/main/resources/locales/en/warned-list.json
  src/main/routes/routes.ts
  src/main/views/case-name-search-results.njk
  src/main/views/case-reference-number-search-results.njk
  src/main/views/create-media-account.njk
  src/main/views/standard-list.njk
  src/main/views/subscription-urn-search-results.njk
  src/main/views/unsubscribe-confirmation.njk
  src/main/views/warned-list.njk
  src/test/routes/standard-list.test.ts
  src/test/routes/warned-list.test.ts
  src/test/unit/controllers/StandardListController.test.ts
  src/test/unit/controllers/WarnedListController.test.ts
  src/test/unit/views/account-request-submitted.test.ts
  src/test/unit/views/admin-dashboard.test.ts
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/case-name-search.test.ts
  src/test/unit/views/case-reference-number-search-results.test.ts
  src/test/unit/views/case-reference-number-search.test.ts
  src/test/unit/views/create-media-account.test.ts
  src/test/unit/views/sign-in.test.ts
  src/test/unit/views/standard-list.test.ts
  src/test/unit/views/subscription-urn-search-results.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
  src/test/unit/views/unsubscribe-confirmation.test.ts
  src/test/unit/views/warned-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-394

#405 Add known-issues file
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-405

#392 Pub 1275 a z changes
  src/main/controllers/RemoveListSearchController.ts
  src/main/controllers/SearchController.ts
  src/main/models/court.ts
  src/main/resources/locales/cy/alphabetical-search.json
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/court-name-search.json
  src/main/resources/requests/courtRequests.ts
  src/main/resources/requests/utils/pendingSubscriptionsFromCache.ts
  src/main/service/courtService.ts
  src/main/service/manualUploadService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/court-name-search.njk
  src/main/views/remove-list-confirmation.njk
  src/test/routes/remove-list-search-results.test.ts
  src/test/routes/remove-list-search.test.ts
  src/test/routes/sjp-public-list.ts
  src/test/unit/controllers/RemoveListSearchController.test.ts
  src/test/unit/controllers/SearchController.test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/requests/courtRequests.test.ts
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/court-name-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-392

#399 PUB-1330 Add App Insights Key
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/modules/appinsights/index.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-399
