Repository hmcts/pip-frontend, pull requests merged in 2022-01, with the labels that each got.

#211 PUB-969 - Updates to search a court page
  src/main/controllers/SearchOptionController.ts
  src/main/controllers/ViewOptionController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/account-home.json
  src/main/resources/locales/en/search-option.json
  src/main/resources/locales/en/search.json
  src/main/routes/routes.ts
  src/main/views/case-event-glossary.njk
  src/main/views/hearing-list.njk
  src/main/views/search-option.njk
  src/main/views/search.njk
  src/main/views/subscription-add.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/pageobjects/Search.page.ts
  src/test/e2e/pageobjects/SearchOptions.page.ts
  src/test/e2e/pageobjects/ViewOption.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/hearing-list.test.ts
  src/test/routes/search-option.test.ts
  src/test/routes/view-option.test.ts
  src/test/unit/controllers/SearchOptionController.test.ts
  src/test/unit/controllers/ViewOptionController.test.ts
  src/test/unit/views/account-home.test.ts
  src/test/unit/views/hearing-list.test.ts
  src/test/unit/views/search-option.test.ts
  src/test/unit/views/subscription-add.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-211

#204 PUB-968 - Input error
  src/main/assets/scss/main.scss
  src/main/views/search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-204

#213 Pub 1002 - updates to start page & service name change
  src/main/assets/scss/home.scss
  src/main/bundles/index.js
  src/main/resources/locales/en/template.json
  src/main/views/home.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/pageobjects/Home.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-213

#210 PUB-998 - Updates to View Option and List Option pages
  src/main/resources/locales/en/list-option.json
  src/main/resources/locales/en/view-option.json
  src/main/views/list-option.njk
  src/main/views/view-option.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/pageobjects/LiveCaseCourtSearchController.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/list-option.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-210

#221 PUB-871 - Re-order radio buttons on Subscription Add page
  package.json
  src/main/views/subscription-add.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/subscription-add.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-221

#218 PUB-979 - Add banner navigation unit tests
  src/test/unit/assets/banner.tests.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-218

#219 PUB-937 - Court search resubmission
  src/main/views/court-name-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-219

#222 PUB-870 - URN Content Updates
  src/main/resources/locales/en/subscription-add.json
  src/main/resources/locales/en/subscription-urn-search.json
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/subscription-add.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-222

#228 PUB-1020: Vulnerability Fix
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-228

#225 PUB-956 - SJP Cases Subscription Option
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/court-name-search.json
  src/main/resources/requests/utils/pendingSubscriptionsFromCache.ts
  src/main/views/alphabetical-search.njk
  src/main/views/court-name-search.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CourtNameSearch.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/court-name-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-225

#231 PUB-887 - Reset Checkboxes
  src/main/views/alphabetical-search.njk
  src/main/views/case-name-search-results.njk
  src/main/views/court-name-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-231

#214 Pub-939 - build routing screens
  src/main/controllers/SignInController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/sign-in.json
  src/main/routes/routes.ts
  src/main/views/sign-in.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/SignIn.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/sign-in.test.ts
  src/test/unit/controllers/SignInController.test.ts
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-214

#232 PUB-962 - P&I redirect URL
  config/default.json
  src/main/authentication/authRedirect.ts
  src/main/controllers/SignInController.ts
  src/main/resources/locales/en/sign-in.json
  src/main/views/sign-in.njk
  src/test/e2e/tests/specs.test.ts
  src/test/routes/sign-in.test.ts
  src/test/unit/controllers/SignInController.test.ts
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-232

#208 Pub 654 - Retrieve existing subscription criteria
  package.json
  src/main/controllers/SubscriptionManagementController.ts
  src/main/controllers/SubscriptionUrnSearchController.ts
  src/main/controllers/SubscriptionUrnSearchResultController.ts
  src/main/models/SubscriptionSearchType.ts
  src/main/models/UserSubscriptions.ts
  src/main/models/hearing.ts
  src/main/resources/locales/en/subscription-management.json
  src/main/resources/mocks/userSubscriptions.json
  src/main/resources/requests/hearingRequests.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/service/hearingService.ts
  src/main/service/subscriptionService.ts
  src/main/views/subscription-management.njk
  src/test/e2e/tests/specs.test.ts
  src/test/routes/subscription-add.test.ts
  src/test/routes/subscription-confirmed.test.ts
  src/test/routes/subscription-management.test.ts
  src/test/unit/controllers/SubscriptionAddController.test.ts
  src/test/unit/controllers/SubscriptionConfirmedController.test.ts
  src/test/unit/controllers/SubscriptionManagementController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchResultController.test.ts
  src/test/unit/mocks/userSubscriptions.json
  src/test/unit/requests/hearingRequests.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/hearingService.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/subscription-add.test.ts
  src/test/unit/views/subscription-confirmed.test.ts
  src/test/unit/views/subscription-management.test.ts
  src/test/unit/views/subscription-urn-search-results.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-208

#233 PUB-839 - Enable E2E Firefox
  wdio.conf.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-233

#229 PUB-1004 block crawlers
  src/main/routes/routes.ts
  src/main/views/template.njk
  src/test/a11y/a11y.ts
  src/test/unit/crawlers/robotsCheck.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-229

#184 PUB-742 - Delete Subscription Flow
  src/main/controllers/DeleteSubscriptionController.ts
  src/main/controllers/UnsubscribeConfirmationController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/delete-subscription.json
  src/main/resources/locales/en/unsubscribe-confirmation.json
  src/main/resources/requests/subscriptionRequests.ts
  src/main/routes/routes.ts
  src/main/service/subscriptionService.ts
  src/main/views/delete-subscription.njk
  src/main/views/unsubscribe-confirmation.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/DeleteSubscription.page.ts
  src/test/e2e/PageObjects/SubscriptionAdd.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/PageObjects/UnsubscribeConfirmation.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/delete-subscription.test.ts
  src/test/routes/unsubscribe-confirmation.test.ts
  src/test/unit/controllers/DeleteSubscriptionController.test.ts
  src/test/unit/controllers/UnsubscribeConfirmationController.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/delete-subscription.test.ts
  src/test/unit/views/subscription-management.test.ts
  src/test/unit/views/unsubscribe-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-184

#234 PUB-1026 - Remove Heroku Stitching
  .nvmrc
  config/default.json
  package.json
  src/main/routes/routes.ts
  src/main/views/sign-in.njk
  src/main/views/template.njk
  src/test/unit/assets/banner.tests.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-234
