Repository hmcts/pip-frontend, pull requests merged in 2022-12, with the labels that each got.

#617 PUB-1649 Family Daily cause list clean up
  src/main/resources/locales/bill/family-daily-cause-list.json
  src/main/resources/locales/cy/family-daily-cause-list.json
  src/main/resources/locales/en/family-daily-cause-list.json
  src/main/service/dataManipulationService.ts
  src/main/views/family-daily-cause-list.njk
  src/test/unit/service/dataManipulationService.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-617

#618 PUB-1650 Civil and Family Daily cause list clean up
  src/main/resources/locales/bill/civil-and-family-daily-cause-list.json
  src/main/resources/locales/cy/civil-and-family-daily-cause-list.json
  src/main/resources/locales/en/civil-and-family-daily-cause-list.json
  src/main/views/civil-and-family-daily-cause-list.njk
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-618

#615 PUB-1614 System admin bulk create media accounts
  manualUpload/tmp/validationFile.csv
  src/main/controllers/BulkCreateMediaAccountsConfirmationController.ts
  src/main/controllers/BulkCreateMediaAccountsConfirmedController.ts
  src/main/controllers/BulkCreateMediaAccountsController.ts
  src/main/controllers/ManualReferenceDataUploadController.ts
  src/main/models/consts.ts
  src/main/resources/locales/cy/bulk-create-media-accounts-confirmation.json
  src/main/resources/locales/cy/bulk-create-media-accounts-confirmed.json
  src/main/resources/locales/cy/bulk-create-media-accounts.json
  src/main/resources/locales/en/bulk-create-media-accounts-confirmation.json
  src/main/resources/locales/en/bulk-create-media-accounts-confirmed.json
  src/main/resources/locales/en/bulk-create-media-accounts.json
  src/main/resources/locales/en/system-admin-dashboard.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/service/createAccountService.ts
  src/main/service/fileHandlingService.ts
  src/main/views/bulk-create-media-accounts-confirmation.njk
  src/main/views/bulk-create-media-accounts-confirmed.njk
  src/main/views/bulk-create-media-accounts.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/BulkCreateMediaAccounts.page.ts
  src/test/e2e/PageObjects/BulkCreateMediaAccountsConfirmation.page.ts
  src/test/e2e/PageObjects/SystemAdminDashboard.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/bulk-create-media-accounts-confirmation.test.ts
  src/test/routes/bulk-create-media-accounts-confirmed.test.ts
  src/test/routes/bulk-create-media-accounts.test.ts
  src/test/unit/controllers/BulkCreateMediaAccountsConfirmationController.test.ts
  src/test/unit/controllers/BulkCreateMediaAccountsConfirmedController.test.ts
  src/test/unit/controllers/BulkCreateMediaAccountsController.test.ts
  src/test/unit/mocks/testBulkMediaUpload.csv
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/service/fileHandlingService.test.ts
  src/test/unit/views/bulk-create-media-accounts-confirmation.test.ts
  src/test/unit/views/bulk-create-media-accounts-confirmed.test.ts
  src/test/unit/views/bulk-create-media-accounts.test.ts
  src/test/unit/views/system-admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-615

#583 1630 - care standards list name fix
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/care-standards-list.json
  src/main/resources/locales/cy/care-standards-list.json
  src/main/resources/locales/en/care-standards-list.json
  src/main/routes/routes.ts
  src/main/service/fileHandlingService.ts
  src/main/views/care-standards-list.njk
  src/test/routes/care-standards-list.test.ts
  src/test/unit/controllers/ManualUploadController.test.ts
  src/test/unit/helpers/dateTimeHelper.test.ts
  src/test/unit/service/listManipulation/tribunalNationalListsService.test.ts
  src/test/unit/views/case-standards-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-583

#614 PUB-1648 Daily cause list clean up
  src/main/resources/locales/bill/daily-cause-list.json
  src/main/resources/locales/cy/daily-cause-list.json
  src/main/resources/locales/en/daily-cause-list.json
  src/main/service/dataManipulationService.ts
  src/main/views/daily-cause-list.njk
  src/test/unit/views/daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-614

#644 PUB-1701 Use e2e selector on partial text for SJP summary of publication page
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CourtList.page.ts
  src/test/e2e/PageObjects/DailyCauseList.page.ts
  src/test/e2e/PageObjects/SingleJusticeProcedure.page.ts
  src/test/e2e/PageObjects/SummaryOfPublications.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-644

#616 PUB-1590 Archive artefacts
  src/main/resources/requests/publicationRequests.ts
  src/main/service/publicationService.ts
  src/test/unit/requests/publicationRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-616

#650 yarn updates
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-650

#651 Fix E2E tests
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-651

#646 PUB-1656 Upgrade Node.js to 16
  Dockerfile
  README.md
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-646

#623 PUB-1700 Clean up COP daily cause list
  src/main/resources/locales/bill/cop-daily-cause-list.json
  src/main/resources/locales/en/cop-daily-cause-list.json
  src/main/service/listManipulation/CopDailyListService.ts
  src/main/views/cop-daily-cause-list.njk
  src/test/unit/views/cop-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-623

#620 PUB-1631-content-date
  src/main/controllers/RemoveListConfirmationController.ts
  src/main/models/listType.ts
  src/main/resources/locales/en/remove-list-confirmation.json
  src/main/resources/locales/en/remove-list-search-results.json
  src/main/service/manualUploadService.ts
  src/main/views/remove-list-confirmation.njk
  src/main/views/remove-list-search-results.njk
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/views/remove-list-confirmation.test.ts
  src/test/unit/views/remove-list-search-results.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-620

#647 PUB-1682 Remove image ID from media application approval/rejection success page
  src/main/views/media-account-approval-confirmation.njk
  src/main/views/media-account-rejection-confirmation.njk
  src/test/unit/views/media-account-approval-confirmation.test.ts
  src/test/unit/views/media-account-rejection-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-647

#649 PUB-1685 Updated Jenkins files
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-649

#656 PUB-1724 fix 404
  src/main/views/webpack/css.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-656

#648 PUB-1057 User management for super admins
  src/main/controllers/AdminManagementController.ts
  src/main/controllers/DeleteUserConfirmationController.ts
  src/main/controllers/UpdateUserConfirmationController.ts
  src/main/resources/locales/cy/admin-dashboard.json
  src/main/resources/locales/cy/admin-management.json
  src/main/resources/locales/cy/delete-user-confirmation.json
  src/main/resources/locales/cy/update-user-confirmation.json
  src/main/resources/locales/en/admin-dashboard.json
  src/main/resources/locales/en/admin-management.json
  src/main/resources/locales/en/delete-user-confirmation.json
  src/main/resources/locales/en/update-user-confirmation.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/service/createAccountService.ts
  src/main/views/admin-dashboard.njk
  src/main/views/admin-management.njk
  src/main/views/delete-user-confirmation.njk
  src/main/views/update-user-confirmation.njk
  src/test/a11y/a11y.ts
  src/test/routes/adminManagement.test.ts
  src/test/unit/controllers/AdminManagementController.test.ts
  src/test/unit/controllers/CreateAdminAccountController.test.ts
  src/test/unit/controllers/DeleteUserConfirmationController.test.ts
  src/test/unit/controllers/UpdateUserConfirmationController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/views/admin-dashboard.test.ts
  src/test/unit/views/admin-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-648

#658 PUB-1726 - Removal of old back to top code
  src/main/assets/scss/main.scss
  src/main/assets/ts/back-to-top.ts
  src/main/bundles/alphabetical.ts
  src/main/views/template.njk
  src/test/unit/assets/back-to-top.test.ts
  webpack.config.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-658

#665 Pub 1748 Added test framework with CodeceptJs and Playwright
  .gitignore
  package.json
  src/test/config.ts
  src/test/end-to-end/functional.conf.js
  src/test/end-to-end/functional.conf.ts
  src/test/end-to-end/shared/random-data.ts
  src/test/end-to-end/steps.d.ts
  src/test/end-to-end/tests/access-home-page.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/tsconfig.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-665

#659 PUB-1712 Updates to the accessibility statement casing
  src/main/resources/locales/cy/accessibility-statement.json
  src/main/resources/locales/en/accessibility-statement.json
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-659

#660 PUB-1758 temp removed bullet from home screen
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-660

#661 PUB-1713 Updated to case name on subscription screens
  src/main/resources/locales/en/case-name-search.json
  src/main/resources/locales/en/subscription-add.json
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/case-name-search.test.ts
  src/test/unit/views/subscription-add.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-661

#662 PUB-1639 Auto reconnect redis
  src/main/cacheManager.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-662

#666 PUB-1715 - Changed Bulk Delete to Bulk Unsubscribe
  src/main/controllers/BulkDeleteSubscriptionsConfirmedController.ts
  src/main/controllers/BulkUnsubscribeConfirmationController.ts
  src/main/controllers/BulkUnsubscribeConfirmedController.ts
  src/main/controllers/BulkUnsubscribeController.ts
  src/main/resources/locales/cy/bulk-unsubscribe-confirmation.json
  src/main/resources/locales/cy/bulk-unsubscribe-confirmed.json
  src/main/resources/locales/cy/bulk-unsubscribe.json
  src/main/resources/locales/en/bulk-unsubscribe-confirmation.json
  src/main/resources/locales/en/bulk-unsubscribe-confirmed.json
  src/main/resources/locales/en/bulk-unsubscribe.json
  src/main/resources/locales/en/subscription-management.json
  src/main/routes/routes.ts
  src/main/views/bulk-unsubscribe-confirmation.njk
  src/main/views/bulk-unsubscribe-confirmed.njk
  src/main/views/bulk-unsubscribe.njk
  src/main/views/subscription-management.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/BulkDeleteSubscriptions.page.ts
  src/test/e2e/PageObjects/BulkDeleteSubscriptionsConfirmation.page.ts
  src/test/e2e/PageObjects/BulkUnsubscribe.page.ts
  src/test/e2e/PageObjects/BulkUnsubscribeConfirmation.page.ts
  src/test/e2e/PageObjects/BulkUnsubscribeConfirmed.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/bulk-unsubscribe-confirmation.test.ts
  src/test/routes/bulk-unsubscribe-confirmed.test.ts
  src/test/routes/bulk-unsubscribe.test.ts
  src/test/unit/controllers/BulkUnsubscribeConfirmationController.test.ts
  src/test/unit/controllers/BulkUnsubscribeConfirmedController.test.ts
  src/test/unit/controllers/BulkUnsubscribeController.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/bulk-unsubscribe-confirmation.test.ts
  src/test/unit/views/bulk-unsubscribe-confirmed.test.ts
  src/test/unit/views/bulk-unsubscribe.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-666

#670 PUB-1746 Fixed blob viewer unit tests
  src/test/unit/mocks/returnedArtefacts.json
  src/test/unit/views/blob-view-json.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-670

#674 PUB-1764 SonarCloud workflow
  .github/workflows/build.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-674

#669 PUB-1705 - Fortnightly list clean up
  src/main/resources/locales/bill/et-fortnightly-list.json
  src/main/resources/locales/cy/et-fortnightly-list.json
  src/main/resources/locales/en/et-fortnightly-list.json
  src/main/views/et-fortnightly-list.njk
  src/test/unit/views/et-fortnightly-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-669

#668 PUB-1704 Tidy up ET daily list style guide
  src/main/resources/locales/bill/et-daily-list.json
  src/main/resources/locales/cy/et-daily-list.json
  src/main/resources/locales/en/et-daily-list.json
  src/main/views/et-daily-list.njk
  src/test/unit/views/et-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-668

#664 PUB-1714 Sort subscriptions by case name or court name
  src/main/service/subscriptionService.ts
  src/test/unit/mocks/userSubscriptions.json
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/bulk-unsubscribe.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-664

#663 PUB-1760 Remove MOJ initialisation from the main nunjucks template
  src/main/views/template.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-663

#672 PUB-1721 - Upgrade Axios
  jest.a11y.config.js
  jest.config.js
  jest.routes.config.js
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-672
