Repository hmcts/pip-frontend, pull requests merged in 2022-02, with the labels that each got.

#235 PUB-1028 - P&I Authentication
  src/main/authentication/authRedirect.ts
  src/main/authentication/authentication-config.json
  src/main/authentication/authentication.ts
  src/main/controllers/SignInController.ts
  src/main/routes/routes.ts
  src/test/routes/sign-in.test.ts
  src/test/unit/authentication/authRedirect.test.ts
  src/test/unit/controllers/SignInController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-235

#245 Pre release fix
  src/test/e2e/PageObjects/AlphabeticalSearch.page.ts
  src/test/e2e/PageObjects/CaseNameSearch.page.ts
  src/test/e2e/PageObjects/CaseNameSearchResults.page.ts
  src/test/e2e/PageObjects/CaseReferenceNumberSearchResults.page.ts
  src/test/e2e/PageObjects/CourtNameSearch.page.ts
  src/test/e2e/PageObjects/Home.page.ts
  src/test/e2e/PageObjects/LiveCaseCourtSearchController.page.ts
  src/test/e2e/PageObjects/MockSession.page.ts
  src/test/e2e/PageObjects/SingleJusticeProcedure.page.ts
  src/test/e2e/PageObjects/SubscriptionAdd.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/pageobjects/CaseEventGlossary.page.ts
  src/test/e2e/pageobjects/CaseReferenceNumberSearch.page.ts
  src/test/e2e/pageobjects/Common.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-245

#246 add pending subscription subscribe e2e tests
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-246

#247 Add logging for staging and additional e2e tests
  src/main/cacheManager.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/assets/cacheManager.test.ts
  wdio.conf.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-247

#256 Trigger master build to Staging
  charts/pip-frontend/Chart.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-256

#244 Pub 546 admin upload
  .gitignore
  package.json
  src/main/assets/scss/main.scss
  src/main/controllers/ManualUploadController.ts
  src/main/models/consts.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/manual-upload.json
  src/main/routes/routes.ts
  src/main/service/manualUploadService.ts
  src/main/views/manual-upload.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/e2e/pageobjects/CaseReferenceNumberSearchResults.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/manual-upload.test.ts
  src/test/unit/controllers/ManualUploadController.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/multerFile.ts
  src/test/unit/mocks/testFile.pdf
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/views/manual-upload.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-244

#236 PUB-875 - Filter hide functionality in small screen
  package.json
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/alphabetical-search.json
  src/main/views/alphabetical-search.njk
  src/main/views/single-justice-procedure.njk
  src/test/e2e/PageObjects/AlphabeticalSearch.page.ts
  src/test/e2e/tests/specs.test.ts
  wdio.conf.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-236

#262 PUB-1062 - AAD on e2e
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.stg.template.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/authentication/authentication.ts
  src/main/controllers/PendingSubscriptionsController.ts
  src/main/controllers/SubscriptionConfirmedController.ts
  src/main/controllers/SubscriptionManagementController.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/main/service/subscriptionService.ts
  src/main/views/account-home.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AccountHome.page.ts
  src/test/e2e/PageObjects/SignIn.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/controllers/PendingSubscriptionsController.test.ts
  src/test/unit/controllers/SubscriptionConfirmedController.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/subscription-management.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-262

#258 PUB-1035 - Account Home Amends
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/account-home.json
  src/test/unit/views/account-home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-258

#275 Fix pageobjects Directory
  src/test/e2e/pageobjects/CaseReferenceNumberSearchResults.page.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-275

#260 PUB-1041 - Add Links to Banners
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
  src/test/unit/assets/banner.tests.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-260

#257 PUB-517 - Interstitial Page
  src/main/controllers/InterstitialController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/cy/interstitial.json
  src/main/resources/locales/cy/template.json
  src/main/resources/locales/en/interstitial.json
  src/main/routes/routes.ts
  src/main/views/home.njk
  src/main/views/interstitial.njk
  src/test/e2e/PageObjects/Home.page.ts
  src/test/e2e/PageObjects/Interstitial.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/interstitial.test.ts
  src/test/unit/controllers/InterstitialController.test.ts
  src/test/unit/views/interstitial.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-257

#266 PUB-1021 Change to dynamically change auth_return_url based on env
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.sbox.template.yaml
  charts/pip-frontend/values.stg.template.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-266

#237 Pub-886 - back to top link in sjp page
  src/main/assets/scss/main.scss
  src/main/views/single-justice-procedure.njk
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-237

#283 Dev PR Fix
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.stg.template.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-283

#239 Pub-874 - back to top button
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/court-name-search.json
  src/main/service/manualUploadService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/court-name-search.njk
  src/main/views/live-case-alphabet-search.njk
  src/main/views/macros/common-components.njk
  src/main/views/single-justice-procedure.njk
  src/main/views/standard-list.njk
  src/main/views/warned-list.njk
  src/test/unit/views/court-name-search.test.ts
  src/test/unit/views/live-case-alphabet-search.test.ts
  wdio.conf.js
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-239

#242 Pub 985 - Summary of publications / lists
  .gitignore
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  package.json
  src/main/controllers/ListOptionController.ts
  src/main/controllers/SearchController.ts
  src/main/controllers/SingleJusticeProcedureController.ts
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/controllers/ViewOptionController.ts
  src/main/models/publication.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/listTypeLookup.json
  src/main/resources/locales/en/account-home.json
  src/main/resources/locales/en/summary-of-publications.json
  src/main/resources/requests/summaryOfPublicationsRequests.ts
  src/main/routes/routes.ts
  src/main/service/summaryOfPublicationsService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/list-option.njk
  src/main/views/summary-of-publications.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AlphabeticalSearch.page.ts
  src/test/e2e/PageObjects/Common.page.ts
  src/test/e2e/PageObjects/SummaryOfPublications.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/summary-of-publications.ts
  src/test/routes/view-option.test.ts
  src/test/unit/controllers/ListOptionController.test.ts
  src/test/unit/controllers/SearchController.test.ts
  src/test/unit/controllers/SingleJusticeProcedureSearchController.test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/controllers/ViewOptionController.test.ts
  src/test/unit/mocks/onePublication.json
  src/test/unit/mocks/summaryOfPublications.json
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/views/account-home.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/list-option.test.ts
  src/test/unit/views/publication.test.ts
  src/test/unit/views/single-justice-procedure.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-242

#254 PUB-544 - Manual Upload Summary
  manualUpload/tmp/validationFile.pdf
  manualUpload/tmp/validationJson.json
  src/main/app.ts
  src/main/authentication/authentication.ts
  src/main/cacheManager.ts
  src/main/controllers/FileUploadConfirmationController.ts
  src/main/controllers/ManualUploadController.ts
  src/main/controllers/ManualUploadSummaryController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/file-upload-confirm.json
  src/main/resources/locales/en/file-upload-summary.json
  src/main/resources/locales/en/manual-upload.json
  src/main/resources/requests/courtRequests.ts
  src/main/resources/requests/dataManagementRequests.ts
  src/main/resources/requests/utils/pendingSubscriptionsFromCache.ts
  src/main/routes/routes.ts
  src/main/service/manualUploadService.ts
  src/main/views/file-upload-summary.njk
  src/main/views/macros/common-components.njk
  src/main/views/subscription-confirmed.njk
  src/main/views/success-view.njk
  src/main/views/unsubscribe-confirmation.njk
  src/test/a11y/a11y.ts
  src/test/e2e/PageObjects/FileUploadConfirmation.page.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/e2e/PageObjects/ManualUploadSummary.page.ts
  src/test/e2e/PageObjects/SingleJusticeProcedure.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/manual-upload-summary.test.ts
  src/test/routes/upload-confirmation.test.ts
  src/test/unit/controllers/FileUploadConfirmationController.test.ts
  src/test/unit/controllers/ManualUploadSummaryController.test.ts
  src/test/unit/requests/dataManagementRequests.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/views/file-upload-summary.test.ts
  src/test/unit/views/success-view.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-254

#263 PUB-1031 - Request Account
  src/main/controllers/CreateMediaAccountController.ts
  src/main/controllers/MediaAccountRequestSubmittedController.ts
  src/main/models/consts.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/account-request-submitted.json
  src/main/resources/locales/en/create-media-account.json
  src/main/resources/locales/en/sign-in.json
  src/main/routes/routes.ts
  src/main/service/createAccountService.ts
  src/main/views/account-request-submitted.njk
  src/main/views/create-media-account.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CreateMediaAccount.page.ts
  src/test/e2e/PageObjects/MediaAccountRequestSubmitted.page.ts
  src/test/e2e/PageObjects/SignIn.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/controllers/CreateMediaAccountController.test.ts
  src/test/unit/controllers/MediaAccountRequestSubmittedController.test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/views/account-request-submitted.test.ts
  src/test/unit/views/create-media-account.test.ts
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-263

#269 Pub-1030 - Connect Court A-Z page with Reference data endpoint
  src/main/controllers/AlphabeticalSearchController.ts
  src/main/controllers/CourtNameSearchController.ts
  src/main/resources/requests/courtRequests.ts
  src/main/service/courtService.ts
  src/main/service/filterService.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/court-name-search.test.ts
  src/test/unit/controllers/AlphabeticalSearchController.test.ts
  src/test/unit/controllers/CourtNameSearchController.test.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/requests/courtRequests.test.ts
  src/test/unit/service/courtService.test.ts
  src/test/unit/service/filterService.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-269

#264 PUB-1072 - File Too Large Handler
  src/main/app.ts
  src/main/controllers/ManualUploadController.ts
  src/main/middlewares/fileErrorHandler.middleware.ts
  src/main/models/request/PipRequest.ts
  src/main/routes/routes.ts
  src/test/a11y/a11y.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/controllers/ManualUploadController.test.ts
  src/test/unit/middlewares/fileErrorHandler.middleware.test.ts
  src/test/unit/views/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-264

#277 PUB-948 updated subscription flow to use new artefact endpoints
  src/main/controllers/CaseNameSearchController.ts
  src/main/controllers/CaseNameSearchResultsController.ts
  src/main/controllers/CaseReferenceNumberSearchController.ts
  src/main/controllers/CaseReferenceNumberSearchResultController.ts
  src/main/controllers/SubscriptionUrnSearchController.ts
  src/main/controllers/SubscriptionUrnSearchResultController.ts
  src/main/models/Artefact.ts
  src/main/models/cases.ts
  src/main/models/searchObject.ts
  src/main/resources/requests/publicationRequests.ts
  src/main/service/publicationService.ts
  src/main/service/subscriptionService.ts
  src/main/views/case-name-search-results.njk
  src/main/views/pending-subscriptions.njk
  src/main/views/subscription-urn-search-results.njk
  src/test/a11y/case-name-search.test.ts
  src/test/unit/controllers/CaseNameSearchController.test.ts
  src/test/unit/controllers/CaseNameSearchResultsController.test.ts
  src/test/unit/controllers/CaseReferenceNumberSearchController.test.ts
  src/test/unit/controllers/CaseReferenceNumberSearchResultController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchResultController.test.ts
  src/test/unit/mocks/returnedArtefacts.json
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/case-name-search.test.ts
  src/test/unit/views/case-reference-number-search-results.test.ts
  src/test/unit/views/case-reference-number-search.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/subscription-urn-search-results.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-277

#272 PUB-1053 - Fix link on unsubscribe success screen
  src/main/views/unsubscribe-confirmation.njk
  src/test/unit/views/unsubscribe-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-272

#285 pub-1096 - filters bug in mobile view
  src/main/views/alphabetical-search.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-285

#287 Add auth logging and change login param on sign in
  src/main/controllers/SignInController.ts
  src/main/routes/routes.ts
  src/test/unit/controllers/SignInController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-287

#278 PUB-997 render sjp
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  package.json
  src/main/controllers/DailyCauseListController.ts
  src/main/controllers/FlatFileController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/listUrlLookup.json
  src/main/resources/locales/en/single-justice-procedure.json
  src/main/resources/requests/publicationRequests.ts
  src/main/routes/routes.ts
  src/main/service/publicationService.ts
  src/main/service/summaryOfPublicationsService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/single-justice-procedure.njk
  src/main/views/summary-of-publications.njk
  src/main/views/template.njk
  src/test/a11y/a11y.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/daily-cause-list.test.ts
  src/test/routes/file-publication.ts
  src/test/routes/sjp-public-list.ts
  src/test/routes/summary-of-publications.test.ts
  src/test/unit/assets/banner.tests.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/FlatFileController.test.ts
  src/test/unit/controllers/SJPPublicListController.test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/mocks/SJPMockPage.json
  src/test/unit/mocks/onePublication.json
  src/test/unit/mocks/returnedArtefacts.json
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/service/SummaryOfPublicationsService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/account-home.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/publication.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-278

#289 updated content for hint court, results pluralisation and capital letter
  src/main/resources/locales/en/case-name-search-results.json
  src/main/resources/locales/en/interstitial.json
  src/main/resources/locales/en/search.json
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/interstitial.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-289

#286 pub-1097 - added new back to top button
  src/main/views/summary-of-publications.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-286

#290 PUB-1105 DACUI changes
  src/main/resources/locales/en/subscription-add.json
  src/main/resources/requests/dataManagementRequests.ts
  src/main/routes/routes.ts
  src/main/views/daily-cause-list.njk
  src/main/views/interstitial.njk
  src/main/views/subscription-add.njk
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/subscription-add.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-290

#291 PUB-1103 Re-order File Formats
  src/main/resources/locales/en/create-media-account.json
  src/main/resources/locales/en/manual-upload.json
  src/main/views/manual-upload.njk
  src/test/unit/views/create-media-account.test.ts
  src/test/unit/views/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-291

#268 PUB-1036: Remove List Search
  src/main/controllers/RemoveListSearchController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/remove-list-search.json
  src/main/routes/routes.ts
  src/main/views/remove-list-search.njk
  src/test/routes/remove-list-search.test.ts
  src/test/unit/controllers/RemoveListSearchController.test.ts
  src/test/unit/views/remove-list-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-268
