Repository hmcts/pip-frontend, pull requests merged in 2022-09, with the labels that each got.

#523 Updated moment dependency
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-523

#500 PUB-1494-Back-To-Top-Fix
  src/main/assets/scss/main.scss
  src/main/assets/ts/back-to-top.ts
  src/main/views/accessibility-statement.njk
  src/main/views/admin-dashboard.njk
  src/main/views/cookie-policy.njk
  src/main/views/create-admin-account.njk
  src/main/views/hearing-list.njk
  src/main/views/macros/common-components.njk
  src/main/views/summary-of-publications.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/assets/back-to-top.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-500

#510 PUB-1512 Confirmation screen for list type
  src/main/app.ts
  src/main/authentication/authentication.ts
  src/main/controllers/SubscriptionConfigureListConfirmedController.ts
  src/main/controllers/SubscriptionConfigureListController.ts
  src/main/helpers/aToZHelper.ts
  src/main/models/listType.ts
  src/main/models/location.ts
  src/main/models/request/PipRequest.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/listTypeLookup.json
  src/main/modules/nunjucks/listUrlLookup.json
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/subscription-configure-list-confirmed.json
  src/main/resources/locales/cy/subscription-configure-list.json
  src/main/resources/locales/cy/subscription-management.json
  src/main/resources/locales/en/subscription-configure-list-confirmed.json
  src/main/resources/locales/en/subscription-configure-list.json
  src/main/resources/locales/en/subscription-management.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/main/routes/routes.ts
  src/main/service/caseEventGlossaryService.ts
  src/main/service/filterService.ts
  src/main/service/locationService.ts
  src/main/service/manualUploadService.ts
  src/main/service/publicationService.ts
  src/main/service/subscriptionService.ts
  src/main/views/subscription-configure-list-confirmed.njk
  src/main/views/subscription-configure-list.njk
  src/main/views/subscription-management.njk
  src/test/e2e/PageObjects/SubscriptionConfigureList.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/helpers/aToZHelper.test.ts
  src/test/routes/subscription-configure-list-confirmed.test.ts
  src/test/routes/subscription-configure-list.test.ts
  src/test/unit/authentication/Authentication.test.ts
  src/test/unit/controllers/SubscriptionConfigureListConfirmedController.test.ts
  src/test/unit/controllers/SubscriptionConfigureListController.test.ts
  src/test/unit/mocks/listTypeSubscriptions/listTypeSubscriptions.json
  src/test/unit/mocks/userSubscriptions.json
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/filterService.test.ts
  src/test/unit/service/locationService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/service/publicationService.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/subscription-configure-list-confirmed.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-510

#517 PUB-1524 - Admin Remove Search Results - Add Sensitivity
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/cy/remove-list-confirmation.json
  src/main/resources/locales/cy/remove-list-search-results.json
  src/main/resources/locales/en/remove-list-confirmation.json
  src/main/resources/locales/en/remove-list-search-results.json
  src/main/views/remove-list-confirmation.njk
  src/main/views/remove-list-search-results.njk
  src/test/routes/remove-list-confirmation.test.ts
  src/test/unit/views/remove-list-confirmation.test.ts
  src/test/unit/views/remove-list-search-results.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-517

#526 PUB-1528 Update Welsh text for "Court or tribunal name"
  src/main/resources/locales/cy/subscription-management.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-526

#512 Pub 1508 inconsistent remove list
  sonar-project.properties
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/bill/cop-daily-cause-list.json
  src/main/resources/locales/cy/cop-daily-cause-list.json
  src/main/resources/locales/cy/remove-list-confirmation.json
  src/main/resources/locales/cy/remove-list-search-results.json
  src/main/resources/locales/en/cop-daily-cause-list.json
  src/main/resources/locales/en/remove-list-confirmation.json
  src/main/resources/locales/en/remove-list-search-results.json
  src/main/views/remove-list-confirmation.njk
  src/main/views/remove-list-search-results.njk
  src/test/routes/remove-list-confirmation.test.ts
  src/test/unit/views/remove-list-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-512

#514 PUB-1498 - Fixed table rows not appearing in safari
  src/main/views/media-account-approval-confirmation.njk
  src/main/views/media-account-approval.njk
  src/main/views/media-account-rejection-confirmation.njk
  src/main/views/media-account-rejection.njk
  src/main/views/media-account-review.njk
  src/test/unit/views/media-account-approval.test.ts
  src/test/unit/views/media-account-confirmation.test.ts
  src/test/unit/views/media-account-rejection-confirmation.test.ts
  src/test/unit/views/media-account-rejection.test.ts
  src/test/unit/views/media-account-review.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-514

#520 PUB-1530 - Fix Language switch
  src/main/modules/i18next/index.ts
  src/main/resources/locales/cy/password-change-confirmation.json
  src/main/routes/routes.ts
  src/test/routes/logout.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-520

#521 PUB-1519 Reintroduce 'Create an account' journey
  src/main/views/sign-in.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-521

#511 PUB-1517 & 1523 Service timeout for media users + Admin logout fixes
  config/default.json
  src/main/app.ts
  src/main/authentication/authentication.ts
  src/main/authentication/authenticationHandler.ts
  src/main/helpers/envUrls.ts
  src/main/routes/routes.ts
  src/main/service/sessionManagementService.ts
  src/test/unit/authentication/authenticationHandler.test.ts
  src/test/unit/service/sessionManagementService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-511

#505 PUB-1213 to PUB-1217 Handling of inactive AAD admin and IDAM user account notification and deletion
  src/main/authentication/authenticationHandler.ts
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/test/unit/authentication/authenticationHandler.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-505

#527 PUB-1544 Fix MultiParties bug in cause lists
  src/main/service/dataManipulationService.ts
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/service/dataManipulationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-527

#524 PUB-1526 Add SJP press register take 2
  src/main/resources/listLookup.json
  src/main/service/manualUploadService.ts
  src/main/service/publicationService.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-524

#516 PUB-1486 Staging custom domain
  config/default.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-516

#529 Remove 'Hearing' from 'Hearing lists' header in manual upload screen
  src/main/resources/locales/cy/manual-upload.json
  src/main/resources/locales/en/manual-upload.json
  src/test/unit/views/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-529

#534 PUB-1460 Summary of subs Welsh updates
  src/main/controllers/HearingListController.ts
  src/main/models/location.ts
  src/main/models/request/PipRequest.ts
  src/main/modules/i18next/index.ts
  src/main/resources/locales/cy/subscription-management.json
  src/main/resources/locales/en/hearing-list.json
  src/main/routes/routes.ts
  src/main/service/locationService.ts
  src/main/service/subscriptionService.ts
  src/main/views/hearing-list.njk
  src/test/e2e/PageObjects/AlphabeticalSearch.page.ts
  src/test/e2e/PageObjects/HearingList.page.ts
  src/test/routes/hearing-list.test.ts
  src/test/unit/controllers/HearingListController.test.ts
  src/test/unit/mocks/userSubscriptions.json
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/hearing-list.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-534

#533 PUB-1556 Add missing Welsh translations
  src/main/resources/locales/cy/session-expired.json
  src/main/resources/locales/cy/session-expiring.json
  src/main/resources/locales/cy/subscription-management.json
  src/main/resources/locales/en/session-expired.json
  src/main/resources/locales/en/session-expiring.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-533

#530 PUB-1553 - Welsh toggle.
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/cy/template.json
  src/main/resources/locales/en/template.json
  src/main/routes/routes.ts
  src/main/views/admin-dashboard.njk
  src/main/views/template.njk
  src/test/routes/case-event-glossary.ts
  src/test/routes/live-case-alphabet-search.test.ts
  src/test/routes/live-case-status.test.ts
  src/test/unit/controllers/CaseEventGlossaryController.test.ts
  src/test/unit/controllers/LiveCaseCourtSearchController.test.ts
  src/test/unit/controllers/LiveCaseStatusController.test.ts
  src/test/unit/controllers/MockSessionController.test.ts
  src/test/unit/controllers/RemoveListConfirmationController.test.ts
  src/test/unit/service/caseEventGlossaryService.test.ts
  src/test/unit/views/case-event-glossary.test.ts
  src/test/unit/views/file-upload-confirm.test.ts
  src/test/unit/views/home.test.ts
  src/test/unit/views/live-case-alphabet-search.test.ts
  src/test/unit/views/live-case-status.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/remove-list-search.test.ts
  src/test/unit/views/remove-list-success.test.ts
  src/test/unit/views/search.test.ts
  src/test/unit/views/sign-in.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-530
