Repository hmcts/pip-frontend, pull requests merged in 2022-03, with the labels that each got.

#297 Add cert
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-297

#302 remove certs from charts
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-302

#274 PUB-543 - Admin Dashboard
  src/main/assets/scss/main.scss
  src/main/controllers/AdminDashboardController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/admin-dashboard.json
  src/main/routes/routes.ts
  src/main/views/admin-dashboard.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AdminDashboard.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/admin-dashboard.test.ts
  src/test/unit/controllers/AdminDashboardController.test.ts
  src/test/unit/views/admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-274

#294 PUB-1107 - Re-implement sort function
  src/main/service/courtService.ts
  src/test/unit/service/courtService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-294

#296 PUB-1017 - Confirm Subscriptions Error Screen
  src/main/controllers/PendingSubscriptionsController.ts
  src/main/controllers/SubscriptionConfirmedController.ts
  src/main/resources/locales/en/pending-subscriptions.json
  src/main/views/pending-subscriptions.njk
  src/test/routes/pending-subscriptions.test.ts
  src/test/routes/subscription-confirmed.test.ts
  src/test/unit/controllers/PendingSubscriptionsController.test.ts
  src/test/unit/controllers/SubscriptionConfirmedController.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/subscription-confirmed.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-296

#300 PUB-1110 - UI Changes
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/case-name-search.json
  src/main/resources/locales/en/case-reference-number-search.json
  src/main/resources/locales/en/interstitial.json
  src/main/resources/locales/en/subscription-add.json
  src/main/resources/locales/en/subscription-urn-search.json
  src/main/resources/locales/en/view-option.json
  src/main/views/interstitial.njk
  src/main/views/subscription-add.njk
  src/main/views/subscription-urn-search.njk
  src/main/views/view-option.njk
  src/test/unit/views/case-name-search.test.ts
  src/test/unit/views/case-reference-number-search.test.ts
  src/test/unit/views/interstitial.test.ts
  src/test/unit/views/subscription-add.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-300

#308 UT content update on the admin dashboard
  src/main/resources/locales/en/admin-dashboard.json
  src/test/unit/views/admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-308

#295 PUB-1040 - Update SJP to use Array
  src/main/views/single-justice-procedure.njk
  src/test/unit/mocks/SJPMockPage.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-295

#299 PUB-974 - SJP Media List Template
  src/main/controllers/SjpPressListController.ts
  src/main/resources/locales/en/single-justice-procedure-press.json
  src/main/routes/routes.ts
  src/main/service/publicationService.ts
  src/main/views/single-justice-procedure-press.njk
  src/test/routes/single-justice-procedure-press.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/mocks/SJPMockPage.json
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-299

#292 PUB-1077 Complete E2E Journey
  Jenkinsfile_CNP
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.stg.template.yaml
  src/main/assets/scss/home.scss
  src/main/authentication/authentication.ts
  src/main/routes/routes.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AccountHome.page.ts
  src/test/e2e/PageObjects/AlphabeticalSearch.page.ts
  src/test/e2e/PageObjects/DailyCauseList.page.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/e2e/PageObjects/SJPPublicList.page.ts
  src/test/e2e/PageObjects/Search.page.ts
  src/test/e2e/PageObjects/SingleJusticeProcedure.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/PageObjects/SummaryOfPublications.page.ts
  src/test/e2e/PageObjects/ViewOption.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/authentication/Authentication.test.ts
  wdio.conf.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-292

#310 PUB-1162 - R1 - Error summary on the view option page
  src/main/controllers/ViewOptionController.ts
  src/main/resources/locales/en/view-option.json
  src/main/views/view-option.njk
  src/test/unit/controllers/ViewOptionController.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-310

#313 PUB-974 - Updated Press List
  src/main/modules/nunjucks/listUrlLookup.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-313

#320 Fix minimist vulnerability
  package.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-320

#317 PUB-1156 - Add and
  src/main/resources/locales/en/interstitial.json
  src/test/unit/views/interstitial.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-317

#316 PUB-1182 - Split date inputs into own rows
  src/main/resources/locales/en/manual-upload.json
  src/main/views/manual-upload.njk
  src/test/unit/views/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-316

#321 PUB-1174 - Change Page Titles
  src/main/resources/locales/en/account-home.json
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/court-name-search.json
  src/main/resources/locales/en/interstitial.json
  src/main/resources/locales/en/pending-subscriptions.json
  src/main/resources/locales/en/search.json
  src/main/resources/locales/en/subscription-add.json
  src/main/resources/locales/en/subscription-confirmed.json
  src/main/resources/locales/en/subscription-management.json
  src/main/views/account-home.njk
  src/main/views/court-name-search.njk
  src/main/views/error.njk
  src/main/views/interstitial.njk
  src/main/views/not-found.njk
  src/main/views/pending-subscriptions.njk
  src/main/views/search.njk
  src/main/views/subscription-add.njk
  src/main/views/subscription-management.njk
  src/test/a11y/a11y.ts
  src/test/unit/views/account-home.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/court-name-search.test.ts
  src/test/unit/views/interstitial.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/search.test.ts
  src/test/unit/views/subscription-add.test.ts
  src/test/unit/views/subscription-confirmed.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-321

#325 PUB-1159 - Footer Links
  src/main/resources/locales/en/template.json
  src/main/views/template.njk
  src/test/unit/views/interstitial.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-325

#323 PUB-1173 - Add Manual Upload Anchors
  src/main/views/file-upload-summary.njk
  src/test/unit/views/file-upload-summary.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-323

#330 Point to Demo instead of Staging
  src/main/authentication/authentication.ts
  src/main/resources/requests/dataManagementRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/routes/routes.ts
  src/test/unit/authentication/Authentication.test.ts
  src/test/unit/requests/dataManagementRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-330

#326 PUB-1113: Remove Suppression
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-326

#305 PUB-1152 - Hidden fields
  src/main/service/filterService.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-305
