Repository hmcts/pip-frontend, pull requests merged in 2022-06, with the labels that each got.

#404 Pub 1292 add tand cs to media accounts
  src/main/resources/locales/cy/create-media-account.json
  src/main/resources/locales/en/create-media-account.json
  src/main/service/createAccountService.ts
  src/main/views/create-media-account.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CreateMediaAccount.page.ts
  src/test/routes/view-option.test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/views/create-media-account.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-404

#417 Add Temp fix for Github Task
  .github/workflows/on-pr.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-417

#418 PUB-1350 - Fix On PR Task
  .github/workflows/close-pr.yml
  .github/workflows/on-pr.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-418

#412 PUB-1255 Change admin error
  src/main/resources/locales/en/create-admin-account-summary.json
  src/main/views/create-admin-account-summary.njk
  src/test/unit/views/create-admin-account-summary.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-412

#406 PUB 1278 Align error handles on Subs
  README.md
  src/main/resources/locales/cy/case-name-search.json
  src/main/resources/locales/cy/case-reference-number-search.json
  src/main/resources/locales/cy/subscription-urn-search.json
  src/main/resources/locales/en/case-name-search.json
  src/main/resources/locales/en/case-reference-number-search.json
  src/main/resources/locales/en/subscription-urn-search.json
  src/main/views/case-name-search.njk
  src/main/views/case-reference-number-search.njk
  src/main/views/subscription-urn-search.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/case-name-search.test.ts
  src/test/unit/views/case-reference-number-search.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-406

#398 PUB-1301 - Removed reference number
  src/main/views/account-request-submitted.njk
  src/test/unit/views/account-request-submitted.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-398

#411 PUB-1345 - Fix dot filenames
  src/main/service/fileHandlingService.ts
  src/test/unit/service/fileHandlingService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-411

#396 PUB-1304 Add find court link to Subscription confirmation page
  src/main/views/subscription-confirmed.njk
  src/test/unit/views/subscription-confirmed.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-396

#402 PUB-1299 - remove single publication SoP behaviour.
  src/main/controllers/SummaryOfPublicationsController.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-402

#409 Pub 1282 Fix vulnurabilities
  .eslintrc.js
  .stylelintrc.json
  package.json
  src/main/assets/scss/accessible-autocomplete.min.scss
  src/main/assets/scss/home.scss
  src/main/assets/scss/main.scss
  src/main/authentication/authentication.ts
  src/main/controllers/SubscriptionAddController.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/routes/routes.ts
  src/test/routes/subscription-add.test.ts
  src/test/unit/controllers/SubscriptionAddController.test.ts
  src/test/unit/views/subscription-add.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-409

#395 PUB-950 Consider Verified and User Types to display lists
  src/main/controllers/CaseNameSearchController.ts
  src/main/controllers/CaseNameSearchResultsController.ts
  src/main/controllers/CaseReferenceNumberSearchController.ts
  src/main/controllers/CaseReferenceNumberSearchResultController.ts
  src/main/controllers/DailyCauseListController.ts
  src/main/controllers/FlatFileController.ts
  src/main/controllers/RemoveListConfirmationController.ts
  src/main/controllers/RemoveListSearchResultsController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/controllers/SubscriptionUrnSearchController.ts
  src/main/controllers/SubscriptionUrnSearchResultController.ts
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/resources/requests/publicationRequests.ts
  src/main/service/publicationService.ts
  src/main/service/subscriptionService.ts
  src/main/service/summaryOfPublicationsService.ts
  src/test/routes/daily-cause-list.test.ts
  src/test/routes/family-daily-cause-list.test.ts
  src/test/routes/file-publication.ts
  src/test/routes/remove-list-confirmation.test.ts
  src/test/routes/single-justice-procedure-press.test.ts
  src/test/routes/single-justice-procedure-public.test.ts
  src/test/routes/summary-of-publications.test.ts
  src/test/unit/controllers/CaseNameSearchController.test.ts
  src/test/unit/controllers/CaseNameSearchResultsController.test.ts
  src/test/unit/controllers/CaseReferenceNumberSearchController.test.ts
  src/test/unit/controllers/CaseReferenceNumberSearchResultController.test.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/FlatFileController.test.ts
  src/test/unit/controllers/RemoveListConfrimationController.test.ts
  src/test/unit/controllers/SJPPublicListController.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchResultController.test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/service/SummaryOfPublicationsService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/service/publicationService.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-395

#423 added in falsly exluded e2e tests and fixed urn subscruption
  src/main/service/subscriptionService.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/service/subscriptionService.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-423

#419 PUB-1329 Footer legal OGL wording update
  src/main/views/template.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-419

#420 PUB-1311 Remove collections page
  src/main/controllers/HomeController.ts
  src/main/controllers/InterstitialController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/main/resources/locales/en/interstitial.json
  src/main/routes/routes.ts
  src/main/views/home.njk
  src/main/views/interstitial.njk
  src/test/e2e/PageObjects/Home.page.ts
  src/test/e2e/PageObjects/Interstitial.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/home.test.ts
  src/test/routes/interstitial.test.ts
  src/test/unit/controllers/HomeController.test.ts
  src/test/unit/controllers/InterstitialController.test.ts
  src/test/unit/views/home.test.ts
  src/test/unit/views/interstitial.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-420

#401 PUB-1286 - Removal of select all checkbox and alignment/text fixes
  package.json
  src/main/cacheManager.ts
  src/main/resources/locales/en/case-name-search-results.json
  src/main/views/case-name-search-results.njk
  src/test/unit/views/case-name-search-results.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-401

#421 Pub 1281 accessibility statement
  src/main/resources/locales/cy/accessibility-statement.json
  src/main/resources/locales/cy/template.json
  src/main/resources/locales/en/accessibility-statement.json
  src/main/views/accessibility-statement.njk
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-421

#427 PUB-1367 Updated request days
  src/main/resources/locales/en/account-request-submitted.json
  src/test/unit/views/account-request-submitted.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-427

#430 PUB-1357 Update interstitial page
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-430

#433 Merging Integration into master
  .nvmrc
  package.json
  src/main/cacheManager.ts
  src/main/controllers/HomeController.ts
  src/main/controllers/InterstitialController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/cy/accessibility-statement.json
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/cy/template.json
  src/main/resources/locales/en/accessibility-statement.json
  src/main/resources/locales/en/account-request-submitted.json
  src/main/resources/locales/en/case-name-search-results.json
  src/main/resources/locales/en/home.json
  src/main/resources/locales/en/interstitial.json
  src/main/resources/locales/en/single-justice-procedure-press.json
  src/main/resources/locales/en/single-justice-procedure.json
  src/main/resources/locales/en/template.json
  src/main/routes/routes.ts
  src/main/service/subscriptionService.ts
  src/main/views/accessibility-statement.njk
  src/main/views/case-name-search-results.njk
  src/main/views/home.njk
  src/main/views/interstitial.njk
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/main/views/template.njk
  src/test/e2e/PageObjects/Home.page.ts
  src/test/e2e/PageObjects/Interstitial.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/home.test.ts
  src/test/routes/interstitial.test.ts
  src/test/unit/controllers/HomeController.test.ts
  src/test/unit/controllers/InterstitialController.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/mocks/sjp-public-list.json
  src/test/unit/views/accessibility-statement.test.ts
  src/test/unit/views/account-request-submitted.test.ts
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/home.test.ts
  src/test/unit/views/interstitial.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
  src/test/unit/views/subscription-management.test.ts
  src/test/unit/views/view-option.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-433

#425 PUB 1290 cookies page updates
  package.json
  sonar-project.properties
  src/main/assets/js/cookie-preferences.js
  src/main/bundles/cookie-preferences.ts
  src/main/bundles/index.js
  src/main/index.d.ts
  src/main/resources/locales/cy/cookie-policy.json
  src/main/resources/locales/en/cookie-policy.json
  src/main/views/cookie-policy.njk
  src/main/views/template.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/unit/assets/cookie-preferences.test.ts
  src/test/unit/views/cookies-page.test.ts
  src/test/unit/views/home.test.ts
  webpack.config.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-425

#437 PUB-1325 - Added language column
  src/main/resources/locales/en/remove-list-search-results.json
  src/main/views/remove-list-search-results.njk
  src/test/unit/views/remove-list-search-results.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-437

#428 PUB-1303 Header changes to Email Subs page
  src/main/views/pending-subscriptions.njk
  src/main/views/subscription-management.njk
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-428

#435 PUB-1394 Family Cause list schema change
  src/main/views/family-daily-cause-list.njk
  src/test/unit/mocks/familyDailyCauseList.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-435

#429 PUB-1277 - add google analytics snippets
  sonar-project.properties
  src/main/modules/helmet/index.ts
  src/main/views/template.njk
  src/test/unit/views/remove-list-search.test.ts
  src/test/unit/views/search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-429

#438 PUB-1422 - Handling UTC times
  package.json
  src/main/controllers/DailyCauseListController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/service/publicationService.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-438

#424 PUB-1300 Content changes for Civil and Family Cause list
  src/main/assets/scss/main.scss
  src/main/resources/locales/cy/daily-cause-list.json
  src/main/resources/locales/cy/family-daily-cause-list.json
  src/main/service/publicationService.ts
  src/main/views/daily-cause-list.njk
  src/main/views/family-daily-cause-list.njk
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/service/publicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-424
