Repository hmcts/pip-frontend, pull requests merged in 2022-10, with the labels that each got.

#532 PUB-1346 Add list template for IAC daily list
  src/main/controllers/IacDailyListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/iac-daily-list.json
  src/main/resources/locales/cy/iac-daily-list.json
  src/main/resources/locales/en/iac-daily-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/views/iac-daily-list.njk
  src/test/routes/iac-daily-list.test.ts
  src/test/unit/controllers/IacDailyListController.test.ts
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/service/dataManipulationService.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/iac-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-532

#539 Pub 1319 et daily list template
  src/main/controllers/EtDailyListController.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/et-daily-list.json
  src/main/resources/locales/cy/et-daily-list.json
  src/main/resources/locales/en/et-daily-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/views/et-daily-list.njk
  src/test/unit/controllers/EtDailyListController.test.ts
  src/test/unit/mocks/etDailyList.json
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/et-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-539

#541 PUB-1550 Handle array of SJP public list cases
  src/main/controllers/SjpPublicListController.ts
  src/main/views/single-justice-procedure.njk
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/mocks/sjp-public-list.json
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-541

#542 PUB-1469 Primary health list template
  src/main/controllers/PrimaryHealthListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/primary-health-list.json
  src/main/resources/locales/cy/primary-health-list.json
  src/main/resources/locales/en/primary-health-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/service/listManipulation/primaryHealthListService.ts
  src/main/views/primary-health-list.njk
  src/test/routes/primary-health-list.test.ts
  src/test/unit/controllers/PrimaryHealthListController.test.ts
  src/test/unit/mocks/primaryHealthList.json
  src/test/unit/service/listManipulation/primaryHealthListService.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/primary-health-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-542

#547 PUB-942 - Updated chart
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-547

#538 PUB-1540 Updated subscription configure list screen with extra information
  src/main/controllers/SubscriptionConfigureListController.ts
  src/main/models/listType.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/subscription-configure-list.json
  src/main/resources/locales/en/subscription-configure-list.json
  src/main/service/subscriptionService.ts
  src/main/views/subscription-configure-list.njk
  src/test/unit/controllers/SubscriptionConfigureListController.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-538

#543 PUB-1548 media app filesize
  src/main/resources/locales/cy/create-media-account.json
  src/main/resources/locales/en/create-media-account.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-543

#550 Update chrome driver version for e2e tests
  wdio.conf.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-550

#545 Pub 1568 - Timezone
  src/main/resources/requests/accountManagementRequests.ts
  src/test/unit/requests/accountManagementRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-545

#544 PUB-1373 Crown daily list template
  src/main/assets/scss/main.scss
  src/main/controllers/CrownDailyListController.ts
  src/main/models/consts.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/crown-daily-list.json
  src/main/resources/locales/cy/crown-daily-list.json
  src/main/resources/locales/en/crown-daily-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/service/listManipulation/crownDailyListService.ts
  src/main/views/crown-daily-list.njk
  src/test/routes/crown-daily-list.test.ts
  src/test/unit/controllers/CrownDailyListController.test.ts
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/service/listManipulation/crownDailyListService.test.ts
  src/test/unit/views/crown-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-544

#546 PUB-1552 Session idle auto sign out
  src/main/controllers/SessionExpiredController.ts
  src/main/controllers/SessionExpiringController.ts
  src/main/controllers/SessionLoggedOutController.ts
  src/main/resources/locales/cy/session-expired.json
  src/main/resources/locales/cy/session-expiring.json
  src/main/resources/locales/cy/session-logged-out.json
  src/main/resources/locales/en/session-expired.json
  src/main/resources/locales/en/session-expiring.json
  src/main/resources/locales/en/session-logged-out.json
  src/main/routes/routes.ts
  src/main/service/sessionManagementService.ts
  src/main/views/session-expired.njk
  src/main/views/session-expiring.njk
  src/main/views/session-logged-out.njk
  src/main/views/template.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AccountHome.page.ts
  src/test/e2e/PageObjects/AdminDashboard.page.ts
  src/test/e2e/PageObjects/SessionLoggedOut.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/session-expired.test.ts
  src/test/routes/session-expiring.test.ts
  src/test/routes/session-logged-out.test.ts
  src/test/unit/controllers/SessionExpiredController.test.ts
  src/test/unit/controllers/SessionExpiringController.test.ts
  src/test/unit/controllers/SessionLoggedOutController.test.ts
  src/test/unit/service/sessionManagementService.test.ts
  src/test/unit/views/session-expired.test.ts
  src/test/unit/views/session-expiring.test.ts
  src/test/unit/views/session-logged-out.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-546

#552 Pub 1573 openjustice
  package.json
  src/main/resources/locales/cy/civil-and-family-daily-cause-list.json
  src/main/resources/locales/cy/daily-cause-list.json
  src/main/resources/locales/cy/family-daily-cause-list.json
  src/main/resources/locales/cy/sscs-daily-list.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-552

#553 PUB-1328 - Updated text to opens in new window
  src/main/resources/locales/cy/media-account-approval-confirmation.json
  src/main/resources/locales/cy/media-account-approval.json
  src/main/resources/locales/cy/media-account-rejection-confirmation.json
  src/main/resources/locales/cy/media-account-rejection.json
  src/main/resources/locales/cy/media-account-review.json
  src/main/resources/locales/en/media-account-approval-confirmation.json
  src/main/resources/locales/en/media-account-approval.json
  src/main/resources/locales/en/media-account-rejection-confirmation.json
  src/main/resources/locales/en/media-account-rejection.json
  src/main/resources/locales/en/media-account-review.json
  src/test/unit/views/media-account-approval.test.ts
  src/test/unit/views/media-account-confirmation.test.ts
  src/test/unit/views/media-account-rejection-confirmation.test.ts
  src/test/unit/views/media-account-rejection.test.ts
  src/test/unit/views/media-account-review.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-553

#551 Pub 1321 fortnightly et list
  package.json
  src/main/controllers/EtFortnightlyListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/et-fortnightly-list.json
  src/main/resources/locales/cy/et-fortnightly-list.json
  src/main/resources/locales/en/et-fortnightly-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/views/et-fortnightly-list.njk
  src/test/routes/et-daily-list.test.ts
  src/test/routes/et-fortnightly-list.test.ts
  src/test/unit/controllers/EtFortnightlyListController.test.ts
  src/test/unit/mocks/etDailyList-withdates.json
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/service/dataManipulationService.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/et-fortnightly-list.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-551
