Repository hmcts/pip-frontend, pull requests merged in 2022-11, with the labels that each got.

#556 PUB-1514 Add Welsh translation to media account submission page
  src/main/resources/locales/cy/account-request-submitted.json
  src/main/resources/locales/en/account-request-submitted.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-556

#559 PUB-1379 List template for Crown Warned List
  src/main/controllers/CrownWarnedListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/crown-warned-list.json
  src/main/resources/locales/cy/crown-warned-list.json
  src/main/resources/locales/en/crown-warned-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/service/listManipulation/crownWarnedListService.ts
  src/main/views/crown-warned-list.njk
  src/test/routes/crown-warned-list.test.ts
  src/test/unit/controllers/CrownWarnedListController.test.ts
  src/test/unit/mocks/crownWarnedList.json
  src/test/unit/service/dataManipulationService.test.ts
  src/test/unit/service/listManipulation/crownWarnedListService.test.ts
  src/test/unit/views/crown-warned-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-559

#562 PUB-1622 removed SSCS temp fix
  src/main/service/dataManipulationService.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-562

#564 PUB-1385 Crime Magistrate Standard List
  src/main/controllers/MagistratesStandardListController.ts
  src/main/helpers/dateTimeHelper.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/magistrates-standard-list.json
  src/main/resources/locales/cy/magistrates-standard-list.json
  src/main/resources/locales/en/magistrates-standard-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/service/listManipulation/magistratesStandardListService.ts
  src/main/views/magistrates-standard-list.njk
  src/test/routes/magistrates-standard-list.test.ts
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/helpers/dateTimeHelper.test.ts
  src/test/unit/mocks/magsStandardList.json
  src/test/unit/service/listManipulation/magsStandardListService.test.ts
  src/test/unit/views/magistrates-standard-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-564

#568 PUB-1199 Bulk delete email subscriptions
  src/main/assets/scss/home.scss
  src/main/controllers/BulkDeleteSubscriptionsConfirmationController.ts
  src/main/controllers/BulkDeleteSubscriptionsConfirmedController.ts
  src/main/controllers/BulkDeleteSubscriptionsController.ts
  src/main/controllers/SubscriptionManagementController.ts
  src/main/resources/locales/cy/bulk-delete-subscriptions-confirmation.json
  src/main/resources/locales/cy/bulk-delete-subscriptions-confirmed.json
  src/main/resources/locales/cy/bulk-delete-subscriptions.json
  src/main/resources/locales/cy/subscription-management.json
  src/main/resources/locales/en/bulk-delete-subscriptions-confirmation.json
  src/main/resources/locales/en/bulk-delete-subscriptions-confirmed.json
  src/main/resources/locales/en/bulk-delete-subscriptions.json
  src/main/resources/locales/en/subscription-management.json
  src/main/resources/requests/subscriptionRequests.ts
  src/main/routes/routes.ts
  src/main/service/subscriptionService.ts
  src/main/views/bulk-delete-subscriptions-confirmation.njk
  src/main/views/bulk-delete-subscriptions-confirmed.njk
  src/main/views/bulk-delete-subscriptions.njk
  src/main/views/macros/common-components.njk
  src/main/views/subscription-management.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/BulkDeleteSubscriptions.page.ts
  src/test/e2e/PageObjects/BulkDeleteSubscriptionsConfirmation.page.ts
  src/test/e2e/PageObjects/BulkDeleteSubscriptionsConfirmed.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/bulk-delete-subscriptions-confirmation.test.ts
  src/test/routes/bulk-delete-subscriptions-confirmed.test.ts
  src/test/routes/bulk-delete-subscriptions.test.ts
  src/test/unit/controllers/BulkDeleteSubscriptionsConfirmationController.test.ts
  src/test/unit/controllers/BulkDeleteSubscriptionsConfirmedController.test.ts
  src/test/unit/controllers/BulkDeleteSubscriptionsController.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/bulk-delete-subscriptions-confirmation.test.ts
  src/test/unit/views/bulk-delete-subscriptions-confirmed.test.ts
  src/test/unit/views/bulk-delete-subscriptions.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-568

#573 PUB-1618 - Updated ref upload to use auth
  src/main/resources/requests/dataManagementRequests.ts
  src/test/unit/requests/dataManagementRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-573

#576 PUB-1327 Media upload fields should not be wiped
  src/main/service/createAccountService.ts
  src/main/views/create-media-account.njk
  src/test/unit/service/createAccountService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-576

#579 Update E2Es to use test court
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-579

#581 Updated display to date for E2Es
  src/test/e2e/PageObjects/ManualUpload.page.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-581

#575 PUB-1607 Various bug fixes for list template
  src/main/helpers/dateTimeHelper.ts
  src/main/service/dataManipulationService.ts
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/service/listManipulation/crownWarnedListService.ts
  src/main/service/listManipulation/magistratesStandardListService.ts
  src/main/service/listManipulation/tribunalNationalListsService.ts
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/cop-daily-cause-list.njk
  src/main/views/crown-warned-list.njk
  src/main/views/daily-cause-list.njk
  src/main/views/et-daily-list.njk
  src/main/views/family-daily-cause-list.njk
  src/main/views/iac-daily-list.njk
  src/main/views/primary-health-list.njk
  src/test/unit/helpers/dateTimeHelper.test.ts
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/copDailyCauseList.json
  src/test/unit/mocks/crimeListParty.json
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/mocks/magistratesPublicList.json
  src/test/unit/service/dataManipulationService.test.ts
  src/test/unit/service/listManipulation/crimeListsService.test.ts
  src/test/unit/views/crown-daily-list.test.ts
  src/test/unit/views/crown-warned-list.test.ts
  src/test/unit/views/iac-daily-list.test.ts
  src/test/unit/views/magistrates-public-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-575

#565 Added dependabot.yml
  .github/dependabot.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-565

#610 PUB-1679 - Updated SOP message
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/resources/locales/cy/summary-of-publications.json
  src/main/resources/locales/en/summary-of-publications.json
  src/main/views/summary-of-publications.njk
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-610

#580 PUB-1611 - 3rd party Subscriptions
  src/main/controllers/ManageThirdPartyUsersController.ts
  src/main/controllers/ManageThirdPartyUsersSubscriptionsController.ts
  src/main/controllers/ManageThirdPartyUsersViewController.ts
  src/main/controllers/UnsubscribeConfirmationController.ts
  src/main/models/UserSubscriptions.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/cy/manage-third-party-users-subscriptions-confirm.json
  src/main/resources/locales/cy/manage-third-party-users-subscriptions.json
  src/main/resources/locales/cy/manage-third-party-users-view.json
  src/main/resources/locales/cy/manage-third-party-users.json
  src/main/resources/locales/cy/system-admin-dashboard.json
  src/main/resources/locales/en/manage-third-party-users-subscriptions-confirm.json
  src/main/resources/locales/en/manage-third-party-users-subscriptions.json
  src/main/resources/locales/en/manage-third-party-users-view.json
  src/main/resources/locales/en/manage-third-party-users.json
  src/main/resources/locales/en/system-admin-dashboard.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/main/routes/routes.ts
  src/main/service/subscriptionService.ts
  src/main/service/thirdPartyService.ts
  src/main/views/manage-third-party-users-subscriptions-confirm.njk
  src/main/views/manage-third-party-users-subscriptions.njk
  src/main/views/manage-third-party-users-view.njk
  src/main/views/manage-third-party-users.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/ManageThirdPartyUsers.page.ts
  src/test/e2e/PageObjects/SystemAdminDashboard.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/manage-third-party-users-subscription.test.ts
  src/test/routes/manage-third-party-users-view.test.ts
  src/test/routes/manage-third-party-users.test.ts
  src/test/unit/controllers/ManageThirdPartyUsersController.test.ts
  src/test/unit/controllers/ManageThirdPartyUsersSubscriptionController.test.ts
  src/test/unit/controllers/ManageThirdPartyUsersViewController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/service/thirdPartyService.test.ts
  src/test/unit/views/manage-third-party-users-subscriptions-confirm.test.ts
  src/test/unit/views/manage-third-party-users-subscriptions.test.ts
  src/test/unit/views/manage-third-party-users-view.test.ts
  src/test/unit/views/manage-third-party-users.test.ts
  src/test/unit/views/system-admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-580

#567 PUB 1382 firm list template
  package.json
  src/main/controllers/CrownFirmListController.ts
  src/main/models/consts.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/crown-firm-list.json
  src/main/resources/locales/cy/crown-firm-list.json
  src/main/resources/locales/en/crown-firm-list.json
  src/main/routes/routes.ts
  src/main/service/dataManipulationService.ts
  src/main/service/fileHandlingService.ts
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/service/listManipulation/crownFirmListService.ts
  src/main/views/crown-firm-list.njk
  src/test/routes/crown-firm-list.test.ts
  src/test/unit/controllers/CrownFirmListController.test.ts
  src/test/unit/mocks/crownFirmList.json
  src/test/unit/mocks/crownFirmSemiDigested.json
  src/test/unit/mocks/firmlistfullyprocessed.json
  src/test/unit/service/listManipulation/crownFirmListService.test.ts
  src/test/unit/views/crown-firm-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-567

#606 PUB-1677 Media ID bug
  src/main/controllers/MediaAccountReviewController.ts
  src/test/unit/controllers/MediaAccountReviewController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-606

#612 PUB-1603 Fix page not found issue for POST-only requests
  src/main/controllers/MediaAccountApprovalConfirmationController.ts
  src/main/controllers/MediaAccountApprovalController.ts
  src/main/controllers/MediaAccountRejectionConfirmationController.ts
  src/main/controllers/MediaAccountRejectionController.ts
  src/main/helpers/envUrls.ts
  src/main/routes/routes.ts
  src/test/a11y/a11y.ts
  src/test/routes/media-account-approval-confirmation.test.ts
  src/test/routes/media-account-rejection-confirmation.test.ts
  src/test/routes/subscription-configure-list-confirmed.test.ts
  src/test/routes/subscription-confirmed.test.ts
  src/test/routes/unsubscribe-confirmation.test.ts
  src/test/unit/controllers/MediaAccountApprovalConfirmationController.test.ts
  src/test/unit/controllers/MediaAccountApprovalController.test.ts
  src/test/unit/controllers/MediaAccountRejectionConfirmationController.test.ts
  src/test/unit/controllers/MediaAccountRejectionController.test.ts
  src/test/unit/helpers/envUrls.ts
  src/test/unit/views/media-account-approval-confirmation.test.ts
  src/test/unit/views/media-account-rejection-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-612

#582 PUB-1570 Media user download SJP public and press list
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/controllers/ListDownloadDisclaimerController.ts
  src/main/controllers/ListDownloadFilesController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/resources/locales/bill/single-justice-procedure-press.json
  src/main/resources/locales/bill/single-justice-procedure.json
  src/main/resources/locales/cy/list-download-disclaimer.json
  src/main/resources/locales/cy/list-download-files.json
  src/main/resources/locales/cy/single-justice-procedure-press.json
  src/main/resources/locales/cy/single-justice-procedure.json
  src/main/resources/locales/en/list-download-disclaimer.json
  src/main/resources/locales/en/list-download-files.json
  src/main/resources/locales/en/single-justice-procedure-press.json
  src/main/resources/locales/en/single-justice-procedure.json
  src/main/resources/requests/channelManagementRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/routes/routes.ts
  src/main/service/listDownloadService.ts
  src/main/views/list-download-disclaimer.njk
  src/main/views/list-download-files.njk
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/ListDownloadDisclaimer.page.ts
  src/test/e2e/PageObjects/ListDownloadFiles.page.ts
  src/test/e2e/PageObjects/SJPPublicList.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/list-download-disclaimer.test.ts
  src/test/routes/list-download-files.test.ts
  src/test/unit/controllers/ListDownloadDisclaimerController.test.ts
  src/test/unit/controllers/ListDownloadFilesController.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/requests/channelManagementRequests.test.ts
  src/test/unit/resources/requests/utils/axiosConfigTest.ts
  src/test/unit/service/listDownloadService.test.ts
  src/test/unit/views/list-download-disclaimer.test.ts
  src/test/unit/views/list-download-files.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-582

#607 PUB-1652 SSCS Daily list clean up
  src/main/resources/locales/bill/sscs-daily-list.json
  src/main/resources/locales/en/sscs-daily-list.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-607

#586 PUB-1636 Download current reference data
  src/main/controllers/ReferenceDataDownloadController.ts
  src/main/resources/locales/cy/manual-reference-data-upload.json
  src/main/resources/locales/en/manual-reference-data-upload.json
  src/main/resources/requests/locationRequests.ts
  src/main/routes/routes.ts
  src/main/views/manual-reference-data-upload.njk
  src/test/a11y/a11y.ts
  src/test/routes/reference-data-download.test.ts
  src/test/unit/controllers/ReferenceDataDownloadController.test.ts
  src/test/unit/requests/locationRequests.test.ts
  src/test/unit/views/manual-reference-data-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-586
