Repository hmcts/pip-frontend, pull requests merged in 2023-12, with the labels that each got.

#1169 PUB-2236 - Updated Link
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1169

#1162 PUB-2001 - Fix configure list confirmation screen
  src/main/routes/routes.ts
  src/test/routes/subscription-configure-list-confirmed.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1162

#1174 PUB-2090 Clean up test data
  src/test/end-to-end/shared/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/dailyCauseEmptyCourtList.json
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/familyDailyCauseListPartyMapping.json
  src/test/unit/mocks/magsStandardList.json
  src/test/unit/service/listManipulation/magsStandardListService.test.ts
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
  src/test/unit/views/magistrates-standard-list.test.ts
  src/test/unit/views/sscs-daily-list-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1174

#1161 PUB-2156 - Modified text for all files affected
  src/main/resources/locales/cy/create-admin-account-summary.json
  src/main/resources/locales/cy/create-super-admin-account-summary.json
  src/main/resources/locales/cy/create-system-admin-account-confirm.json
  src/main/resources/locales/cy/media-account-approval-confirmation.json
  src/main/resources/locales/en/create-admin-account-summary.json
  src/main/resources/locales/en/create-system-admin-account-confirm.json
  src/main/resources/locales/en/media-account-approval-confirmation.json
  src/test/end-to-end/tests/admin/create-new-account-test.ts
  src/test/end-to-end/tests/admin/manage-media-account-request-test.ts
  src/test/unit/views/create-admin-account-summary.test.ts
  src/test/unit/views/create-system-admin-account-confirm.test.ts
  src/test/unit/views/create-system-admin-account-summary.test.ts
  src/test/unit/views/media-account-approval-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1161

#1164 Pub 2221 ET lists
  src/main/resources/locales/bill/et-daily-list.json
  src/main/resources/locales/bill/et-fortnightly-list.json
  src/main/resources/locales/cy/et-daily-list.json
  src/main/resources/locales/cy/et-fortnightly-list.json
  src/main/resources/locales/en/et-daily-list.json
  src/main/resources/locales/en/et-fortnightly-list.json
  src/main/service/listManipulation/EtListsService.ts
  src/main/views/et-daily-list.njk
  src/main/views/et-fortnightly-list.njk
  src/test/end-to-end/shared/mocks/etDailyList.json
  src/test/unit/mocks/etDailyList.json
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/service/listManipulation/etListsService.test.ts
  src/test/unit/views/et-daily-list.test.ts
  src/test/unit/views/et-fortnightly-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1164

#1170 Pub 2007 frontend breaking changes
  package.json
  src/main/modules/helmet/index.ts
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/dataManagementRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1170

#1173 PUB-2092 Modified magistratesPublicList.json to remove JSON fields
  src/test/unit/mocks/magistratesPublicList.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1173

#1177 PUB-1690 Removed HyperLinks to reporting restrictions for crime lists
  src/main/resources/locales/bill/crown-daily-list.json
  src/main/resources/locales/bill/crown-firm-list.json
  src/main/resources/locales/bill/crown-warned-list.json
  src/main/resources/locales/bill/magistrates-public-list.json
  src/main/resources/locales/bill/magistrates-standard-list.json
  src/main/resources/locales/cy/crown-daily-list.json
  src/main/resources/locales/cy/crown-firm-list.json
  src/main/resources/locales/cy/crown-warned-list.json
  src/main/resources/locales/cy/magistrates-public-list.json
  src/main/resources/locales/cy/magistrates-standard-list.json
  src/main/resources/locales/en/crown-daily-list.json
  src/main/resources/locales/en/crown-firm-list.json
  src/main/resources/locales/en/crown-warned-list.json
  src/main/resources/locales/en/magistrates-public-list.json
  src/main/resources/locales/en/magistrates-standard-list.json
  src/main/views/crown-daily-list.njk
  src/main/views/crown-firm-list.njk
  src/main/views/crown-warned-list.njk
  src/main/views/magistrates-public-list.njk
  src/main/views/magistrates-standard-list.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1177

#1171 PUB-2112 Replace console.log with Logger
  src/main/resources/logging/logHelper.ts
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/caseEventGlossaryRequests.ts
  src/main/resources/requests/channelManagementRequests.ts
  src/main/resources/requests/dataManagementRequests.ts
  src/main/resources/requests/liveCaseRequests.ts
  src/main/resources/requests/locationRequests.ts
  src/main/resources/requests/publicationRequests.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/main/service/createAccountService.ts
  src/test/routes/manual-reference-data-upload-summary.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/resources/logging/LogHelper.test.ts
  src/test/unit/service/createAccountService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1171

#1182 PUB-2171 Update Court and tribunal hearings casing for create media account page
  src/main/resources/locales/cy/create-media-account.json
  src/main/resources/locales/cy/media-rejected-login.json
  src/main/resources/locales/cy/sign-in.json
  src/main/resources/locales/en/create-media-account.json
  src/main/views/template.njk
  src/test/unit/views/create-media-account.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1182
