Repository hmcts/pip-frontend, pull requests merged in 2023-05, with the labels that each got.

#886 Pub 1843 Email subscriptions
  src/test/e2e/PageObjects/BulkUnsubscribe.page.ts
  src/test/e2e/PageObjects/BulkUnsubscribeConfirmation.page.ts
  src/test/e2e/PageObjects/BulkUnsubscribeConfirmed.page.ts
  src/test/e2e/PageObjects/CaseNameSearch.page.ts
  src/test/e2e/PageObjects/CaseNameSearchResults.page.ts
  src/test/e2e/PageObjects/CaseReferenceNumberSearch.page.ts
  src/test/e2e/PageObjects/CaseReferenceNumberSearchResults.page.ts
  src/test/e2e/PageObjects/DeleteSubscription.page.ts
  src/test/e2e/PageObjects/LocationNameSearchPage.ts
  src/test/e2e/PageObjects/PendingSubscriptions.page.ts
  src/test/e2e/PageObjects/SubscriptionAdd.page.ts
  src/test/e2e/PageObjects/SubscriptionConfigureList.page.ts
  src/test/e2e/PageObjects/SubscriptionConfirmed.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/PageObjects/SubscriptionUrnSearch.page.ts
  src/test/e2e/PageObjects/SubscriptionUrnSearchResults.page.ts
  src/test/e2e/PageObjects/UnsubscribeConfirmation.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/end-to-end/shared/mocks/civilAndFamilyDailyCauseList.json
  src/test/end-to-end/shared/mocks/etDailyList.json
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-886

#889 Added functional tests for manual upload json file
  src/test/end-to-end/tests/admin/manual-upload-json.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-889

#884 PUB-1830 Add create system admin end2end tests
  Jenkinsfile_CNP
  README.md
  package.json
  src/test/config.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/CreateSystemAdminAccount.page.ts
  src/test/e2e/PageObjects/CreateSystemAdminAccountSummary.page.ts
  src/test/e2e/PageObjects/SystemAdminDashboard.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
  src/test/end-to-end/shared/random-data.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-884

#916 Pub 1838
  src/test/end-to-end/tests/admin/remove-list-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-916

#917 PUB-1892 Add new E2E tests for system admin audit log viewer
  src/test/end-to-end/shared/shared-functions.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/admin/manual-upload-flat-test.ts
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
  src/test/end-to-end/tests/system-admin/system-admin-audit-log-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-917

#915 PUB-1996 - Dependency updates
  charts/pip-frontend/Chart.yaml
  package.json
  src/main/assets/scss/accessible-autocomplete.min.scss
  src/main/assets/scss/main.scss
  src/main/controllers/BlobViewJsonController.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-915

#921 PUB-2016 - Fix master build
  src/main/service/mediaAccountApplicationService.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-921

#914 PUB-1765 - Media User Rejected Flow
  src/main/authentication/authenticationHandler.ts
  src/main/authentication/authenticationHelper.ts
  src/main/controllers/MediaRejectedLoginController.ts
  src/main/resources/locales/cy/media-rejected-login.json
  src/main/resources/locales/en/media-rejected-login.json
  src/main/routes/routes.ts
  src/main/service/sessionManagementService.ts
  src/main/views/media-rejected-login.njk
  src/test/end-to-end/tests/login-test.ts
  src/test/routes/media-rejected-login.test.ts
  src/test/unit/authentication/authenticationHandler.test.ts
  src/test/unit/authentication/authenticationHelper.test.ts
  src/test/unit/controllers/MediaRejectedLoginController.test.ts
  src/test/unit/service/sessionManagementService.test.ts
  src/test/unit/views/media-rejected-login.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-914

#918 PUB-836 Combine case number and case URN subscription creation
  src/main/controllers/CaseReferenceNumberSearchController.ts
  src/main/controllers/CaseReferenceNumberSearchResultController.ts
  src/main/controllers/SubscriptionAddController.ts
  src/main/controllers/SubscriptionUrnSearchController.ts
  src/main/controllers/SubscriptionUrnSearchResultController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/cy/case-name-search-results.json
  src/main/resources/locales/cy/case-reference-number-search-results.json
  src/main/resources/locales/cy/case-reference-number-search.json
  src/main/resources/locales/cy/pending-subscriptions.json
  src/main/resources/locales/cy/subscription-add.json
  src/main/resources/locales/cy/subscription-management.json
  src/main/resources/locales/cy/subscription-urn-search-results.json
  src/main/resources/locales/cy/subscription-urn-search.json
  src/main/resources/locales/en/case-name-search-results.json
  src/main/resources/locales/en/case-reference-number-search-results.json
  src/main/resources/locales/en/case-reference-number-search.json
  src/main/resources/locales/en/pending-subscriptions.json
  src/main/resources/locales/en/subscription-add.json
  src/main/resources/locales/en/subscription-management.json
  src/main/resources/locales/en/subscription-urn-search-results.json
  src/main/resources/locales/en/subscription-urn-search.json
  src/main/resources/requests/utils/pendingSubscriptionsFromCache.ts
  src/main/routes/routes.ts
  src/main/service/subscriptionService.ts
  src/main/views/case-reference-number-search-results.njk
  src/main/views/case-reference-number-search.njk
  src/main/views/pending-subscriptions.njk
  src/main/views/subscription-add.njk
  src/main/views/subscription-urn-search-results.njk
  src/main/views/subscription-urn-search.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/routes/subscription-add.test.ts
  src/test/routes/subscriptionUrnSearch.test.ts
  src/test/routes/subscriptionUrnSearchResults.test.ts
  src/test/unit/controllers/CaseReferenceNumberSearchController.test.ts
  src/test/unit/controllers/CaseReferenceNumberSearchResultController.test.ts
  src/test/unit/controllers/SubscriptionAddController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchController.test.ts
  src/test/unit/controllers/SubscriptionUrnSearchResultController.test.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/requests/utils/pendingSubscriptionsFromCache.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/case-reference-number-search-results.test.ts
  src/test/unit/views/case-reference-number-search.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/subscription-add.test.ts
  src/test/unit/views/subscription-management.test.ts
  src/test/unit/views/subscription-urn-search-results.test.ts
  src/test/unit/views/subscription-urn-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-918

#924 Pub 1842 - functional test for Verified user single Justice Procedure cases
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/admin/change-own-user-test.ts
  src/test/end-to-end/tests/admin/manual-upload-flat-test.ts
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
  src/test/end-to-end/tests/admin/remove-list-test.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
  src/test/end-to-end/tests/system-admin/blob-explorer-test.ts
  src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
  src/test/end-to-end/tests/system-admin/delete-court-test.ts
  src/test/end-to-end/tests/system-admin/upload-reference-data-test.ts
  src/test/end-to-end/tests/system-admin/user-management-test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/end-to-end/tests/verified/single-justice-procedure-cases-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-924

#927 PUB-2024 - Fix width issue
  .stylelintrc.json
  src/main/assets/scss/accessible-autocomplete.min.scss
  src/main/assets/scss/main.scss
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-927

#928 PUB-2019 - Removed unneeded library, updated suppressions
  package.json
  src/main/controllers/InfoController.ts
  src/main/helpers/infoProvider.ts
  src/main/routes/routes.ts
  src/test/routes/info.test.ts
  src/test/unit/helpers/infoProvider.test.ts
  src/test/unit/views/info.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-928

#937 PUB-2036 Fix functional date issue in manual upload test
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-937

#926 Pub 1999
  src/main/controllers/CopDailyCauseListController.ts
  src/main/controllers/CrownDailyListController.ts
  src/main/controllers/CrownFirmListController.ts
  src/main/controllers/CrownWarnedListController.ts
  src/main/controllers/DailyCauseListController.ts
  src/main/controllers/EtDailyListController.ts
  src/main/controllers/EtFortnightlyListController.ts
  src/main/controllers/IacDailyListController.ts
  src/main/controllers/MagistratesPublicListController.ts
  src/main/controllers/MagistratesStandardListController.ts
  src/main/controllers/SscsDailyListController.ts
  src/main/controllers/TribunalNationalListsController.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/care-standards-list.njk
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/cop-daily-cause-list.njk
  src/main/views/crown-daily-list.njk
  src/main/views/crown-firm-list.njk
  src/main/views/crown-warned-list.njk
  src/main/views/daily-cause-list.njk
  src/main/views/et-daily-list.njk
  src/main/views/et-fortnightly-list.njk
  src/main/views/family-daily-cause-list.njk
  src/main/views/iac-daily-list.njk
  src/main/views/magistrates-public-list.njk
  src/main/views/magistrates-standard-list.njk
  src/main/views/primary-health-list.njk
  src/main/views/sscs-daily-list.njk
  src/test/unit/modules/nunjucks/njkFilters.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-926
