Repository hmcts/pip-frontend, pull requests merged in 2023-01, with the labels that each got.

#705 Fixed suppressions
  package.json
  wdio.conf.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-705

#708 Regenerate yarn audit suppression file
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-708

#707 PUB-1723 Bulk media upload max record warning
  manualUpload/tmp/bulkMediaUploadValidationFile.csv
  manualUpload/tmp/bulkMediaUploadValidationFile_30Accounts.csv
  manualUpload/tmp/bulkMediaUploadValidationFile_31Accounts.csv
  src/main/resources/locales/cy/bulk-create-media-accounts-confirmation.json
  src/main/resources/locales/cy/bulk-create-media-accounts.json
  src/main/resources/locales/en/bulk-create-media-accounts-confirmation.json
  src/main/resources/locales/en/bulk-create-media-accounts.json
  src/main/service/createAccountService.ts
  src/main/views/bulk-create-media-accounts-confirmation.njk
  src/main/views/bulk-create-media-accounts.njk
  src/test/e2e/tests/specs.test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/service/fileHandlingService.test.ts
  src/test/unit/views/bulk-create-media-accounts-confirmation.test.ts
  src/test/unit/views/bulk-create-media-accounts.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-707

#716 PUB-1750 functional tests for admin login feature
  src/test/config.ts
  src/test/end-to-end/tests/access-home-page.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/system-admin-login-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-716

#711 PUB-1722 - Update misc dependencies
  charts/pip-frontend/Chart.yaml
  package.json
  webpack/scss.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-711

#719 PUB-1751 functional tests for media user login feature
  src/test/config.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-719

#717 PUB-1781 - CFT sign out page
  src/main/service/sessionManagementService.ts
  src/test/e2e/PageObjects/AccountHome.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/service/sessionManagementService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-717

#728 Updated wdio + ua parser
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-728

#653 (Do not merge) - R4 - Enable CFT IDAM
  charts/pip-frontend/values.stg.template.yaml
  package.json
  src/test/e2e/tests/specs.test.ts
  webpack/scss.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-653

#730 Freeze
  .nvmrc
  charts/pip-frontend/Chart.yaml
  manualUpload/tmp/bulkMediaUploadValidationFile.csv
  manualUpload/tmp/bulkMediaUploadValidationFile_30Accounts.csv
  manualUpload/tmp/bulkMediaUploadValidationFile_31Accounts.csv
  package.json
  src/main/resources/locales/bill/list-template.json
  src/main/resources/locales/bill/single-justice-procedure-press.json
  src/main/resources/locales/bill/single-justice-procedure.json
  src/main/resources/locales/cy/bulk-create-media-accounts-confirmation.json
  src/main/resources/locales/cy/bulk-create-media-accounts.json
  src/main/resources/locales/cy/case-name-search.json
  src/main/resources/locales/cy/list-download-disclaimer.json
  src/main/resources/locales/cy/list-download-files.json
  src/main/resources/locales/cy/list-template.json
  src/main/resources/locales/cy/password-change-confirmation.json
  src/main/resources/locales/cy/single-justice-procedure-press.json
  src/main/resources/locales/cy/single-justice-procedure.json
  src/main/resources/locales/cy/subscription-add.json
  src/main/resources/locales/en/bulk-create-media-accounts-confirmation.json
  src/main/resources/locales/en/bulk-create-media-accounts.json
  src/main/service/createAccountService.ts
  src/main/service/sessionManagementService.ts
  src/main/views/bulk-create-media-accounts-confirmation.njk
  src/main/views/bulk-create-media-accounts.njk
  src/test/config.ts
  src/test/e2e/PageObjects/AccountHome.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/end-to-end/functional.conf.ts
  src/test/end-to-end/tests/access-home-page.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/unit/service/createAccountService.test.ts
  src/test/unit/service/fileHandlingService.test.ts
  src/test/unit/service/sessionManagementService.test.ts
  src/test/unit/views/bulk-create-media-accounts-confirmation.test.ts
  src/test/unit/views/bulk-create-media-accounts.test.ts
  webpack/scss.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-730

#729 PUB-1806 App Restarts when downloading Flat File
  src/main/service/listDownloadService.ts
  src/test/unit/controllers/ListDownloadFilesController.test.ts
  src/test/unit/service/listDownloadService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-729

#718 PUB-1768 Add SSCS daily list - additional hearings
  src/main/controllers/SscsDailyListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/sscs-daily-list-additional-hearings.json
  src/main/resources/locales/bill/sscs-daily-list.json
  src/main/resources/locales/cy/sscs-daily-list-additional-hearings.json
  src/main/resources/locales/cy/sscs-daily-list.json
  src/main/resources/locales/en/sscs-daily-list-additional-hearings.json
  src/main/resources/locales/en/sscs-daily-list.json
  src/main/routes/routes.ts
  src/main/views/sscs-daily-list.njk
  src/test/routes/sscs-daily-list.test.ts
  src/test/unit/controllers/SscsDailyListController.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/sscs-daily-list-test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-718

#734 Updated yarn audit known issues
  src/test/e2e/tests/specs.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-734

#722 PUB-1791 Add test in Civil Cause List
  src/test/unit/mocks/dailyCauseEmptyCourtList.json
  src/test/unit/views/daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-722

#721 PUB-1725 Added changes to helmet config
  src/main/modules/helmet/index.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-721

#736 PUB-1783 Added update PR Github action
  .github/workflows/update-pr.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-736
