Repository hmcts/pip-frontend, pull requests merged in 2023-07, with the labels that each got.

#1007 Pub 1995 test endpoint integration
  package.json
  src/test/config.ts
  src/test/end-to-end/crossbrowser.conf.js
  src/test/end-to-end/crossbrowser.conf.ts
  src/test/end-to-end/functional.conf.ts
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
  src/test/end-to-end/shared/random-data.ts
  src/test/end-to-end/shared/shared-functions.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/admin/create-new-account-test.ts
  src/test/end-to-end/tests/admin/manage-media-account-request-test.ts
  src/test/end-to-end/tests/admin/manual-upload-flat-test.ts
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
  src/test/end-to-end/tests/admin/remove-list-test.ts
  src/test/end-to-end/tests/admin/user-management-test.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
  src/test/end-to-end/tests/system-admin/blob-explorer-test.ts
  src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
  src/test/end-to-end/tests/system-admin/delete-court-test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1007

#982 PUB-2009 Use party organisation name as alternative prosecutor
  src/main/service/listManipulation/SscsDailyListService.ts
  src/main/views/sscs-daily-list.njk
  src/test/unit/mocks/sscsDailyList.json
  src/test/unit/service/listManipulation/sscsListService.test.ts
  src/test/unit/views/sscs-daily-list-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-982

#1009 PUB-2079 Update dependencies
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1009

#1005 Pub 1963 - SJP postcode filters
  src/main/views/macros/sjp-common.njk
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1005

#1021 PUB-1967 Update nightly pipeline env variables
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1021

#1024 PUB-1967 Add test URL to nightly Jenkins file
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1024

#1025 PUB-1986 Update create system admin e2e tests
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
  src/test/end-to-end/shared/random-data.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/admin/create-new-account-test.ts
  src/test/end-to-end/tests/admin/manage-media-account-request-test.ts
  src/test/end-to-end/tests/admin/user-management-test.ts
  src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1025

#1035 Updated nightly + mem limits + chrome driver version
  Jenkinsfile_nightly
  charts/pip-frontend/values.dev.template.yaml
  wdio.conf.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1035

#1018 PUB-1986 SJP Press list party ordering
  src/main/service/listManipulation/SjpPressListService.ts
  src/main/service/listParseHelperService.ts
  src/test/unit/mocks/SJPMockPage.json
  src/test/unit/service/listManipulation/sjpPressListService.test.ts
  src/test/unit/service/listManipulation/sjpPublicListService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1018

#1028 PUB-2010 Redirect to main sign-in page for verified URL
  src/main/authentication/authenticationHandler.ts
  src/main/models/consts.ts
  src/test/unit/authentication/authenticationHandler.test.ts
  src/test/unit/views/session-expired.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1028

#1027 PUB-1985 Allow organisation details for accused party
  src/main/service/listManipulation/SjpPressListService.ts
  src/main/service/listManipulation/SjpPublicListService.ts
  src/main/service/sjpFilterService.ts
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/test/routes/single-justice-procedure-press.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/mocks/sjp-press-list.json
  src/test/unit/service/listManipulation/sjpPressListService.test.ts
  src/test/unit/service/listManipulation/sjpPublicListService.test.ts
  src/test/unit/service/sjpFilterService.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1027

#1031 PUB-2075 - Fixed ordering issue with logging + removed uneeded logs
  src/main/app.ts
  src/main/authentication/authentication.ts
  src/main/cacheManager.ts
  src/main/server.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1031

#1032 PUB-1698 Update jurisdiction of SJP list to Magistrates
  src/main/resources/listLookup.json
  src/test/unit/mocks/listTypeSubscriptions/listTypeSubscriptions.json
  src/test/unit/service/publicationService.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1032
