Repository hmcts/pip-frontend, pull requests merged in 2023-04, with the labels that each got.

#845 PUB-1955 - Sign out screen updates
  src/main/views/session-logged-out.njk
  src/test/e2e/PageObjects/SessionLoggedOut.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/views/session-logged-out.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-845

#847 PUB-1950 - Updated password reset URL
  src/main/authentication/authentication-config.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-847

#868 PUB-1917 - Readme changes
  README.md
  darkLogo.jpg
  frontend-arch.png
  lightLogo.png
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-868

#873 Added upload reference data functional test
  src/test/config.ts
  src/test/end-to-end/shared/mocks/reference-data-invalid.csv
  src/test/end-to-end/shared/mocks/system-admin-upload-reference-data-test.csv
  src/test/end-to-end/tests/system-admin-upload-reference-data-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-873

#872 PUB-1971 Randomise test court ID and name fir E2E tests
  src/test/end-to-end/crossbrowser.conf.ts
  src/test/end-to-end/shared/mocks/delete-court-validations.csv
  src/test/end-to-end/shared/random-data.ts
  src/test/end-to-end/shared/shared-functions.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/delete-court-validations-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-872

#846 PUB-1956 Replace CaTH with court and tribunal hearings service
  src/main/resources/locales/cy/list-download-disclaimer.json
  src/main/resources/locales/en/admin-rejected-login.json
  src/main/resources/locales/en/list-download-disclaimer.json
  src/test/unit/views/admin-rejected-login.test.ts
  src/test/unit/views/list-download-disclaimer.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-846

#877 PUB-1859 - Home Page Updates
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-877

#820 PUB-1056 - Rejection reasons for Media Application
  .eslintrc.js
  jest.config.js
  jest.routes.config.js
  jest.smoke.config.js
  package.json
  src/main/controllers/MediaAccountRejectionConfirmationController.ts
  src/main/controllers/MediaAccountRejectionController.ts
  src/main/controllers/MediaAccountRejectionReasonsController.ts
  src/main/controllers/MediaAccountReviewController.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/resources/locales/cy/media-account-rejection-confirmation.json
  src/main/resources/locales/cy/media-account-rejection-reasons.json
  src/main/resources/locales/cy/media-account-rejection.json
  src/main/resources/locales/en/media-account-rejection-confirmation.json
  src/main/resources/locales/en/media-account-rejection-reasons.json
  src/main/resources/locales/en/media-account-rejection.json
  src/main/resources/media-account-rejection-reasons-lookup.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/service/mediaAccountApplicationService.ts
  src/main/views/media-account-rejection-confirmation.njk
  src/main/views/media-account-rejection-reasons.njk
  src/main/views/media-account-rejection.njk
  src/test/a11y/a11y.ts
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/MediaAccountRejectionReasons.page.ts
  src/test/e2e/PageObjects/MediaAccountReview.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/media-account-rejection-reasons.test.ts
  src/test/unit/controllers/MediaAccountRejectionConfirmationController.test.ts
  src/test/unit/controllers/MediaAccountRejectionController.test.ts
  src/test/unit/controllers/MediaAccountRejectionReasonsController.test.ts
  src/test/unit/controllers/MediaAccountReviewController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/mediaAccountApplicationService.ts
  src/test/unit/views/media-account-rejection-confirmation.test.ts
  src/test/unit/views/media-account-rejection-reasons.test.ts
  src/test/unit/views/media-account-rejection.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-820

#878 Added system admin delete court functional test
  src/test/end-to-end/tests/system-admin-delete-court-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-878

#871 PUB-1930 Beta survey feedback on B2C password reset returned pages
  .github/workflows/close-pr.yml
  .github/workflows/on-pr.yml
  src/main/controllers/CancelledPasswordResetController.ts
  src/main/controllers/PasswordChangeController.ts
  src/main/views/cancelled-password-reset.njk
  src/main/views/macros/common-components.njk
  src/main/views/password-change-confirmation.njk
  src/main/views/template.njk
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/unit/controllers/CancelledPasswordResetController.test.ts
  src/test/unit/controllers/PasswordChangeController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-871

#881 Fix close PR github action
  .github/workflows/close-pr.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-881

#885 Update nunjucks version to 3.2.4
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-885

#876 PUB 1834 - E2E Test for User Management
  README.md
  src/test/e2e/PageObjects/DeleteUser.page.ts
  src/test/e2e/PageObjects/ManageUser.page.ts
  src/test/e2e/PageObjects/SystemAdminDashboard.page.ts
  src/test/e2e/PageObjects/UpdateUser.page.ts
  src/test/e2e/PageObjects/UserManagement.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/end-to-end/crossbrowser.conf.ts
  src/test/end-to-end/functional.conf.ts
  src/test/end-to-end/tests/admin/change-own-user-test.ts
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/system-admin/system-admin-audit-log-test.ts
  src/test/end-to-end/tests/system-admin/system-admin-delete-court-test.ts
  src/test/end-to-end/tests/system-admin/system-admin-upload-reference-data-test.ts
  src/test/end-to-end/tests/system-admin/system-admin-user-management-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-876

#887 Adding back user management delete user e2e tests
  src/test/e2e/PageObjects/DeleteUser.page.ts
  src/test/e2e/PageObjects/ManageUser.page.ts
  src/test/e2e/PageObjects/SystemAdminDashboard.page.ts
  src/test/e2e/PageObjects/UpdateUser.page.ts
  src/test/e2e/PageObjects/UserManagement.page.ts
  src/test/e2e/tests/specs.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-887

#880 PUB-1992 - Updated case type
  src/main/resources/locales/bill/civil-and-family-daily-cause-list.json
  src/main/resources/locales/cy/civil-and-family-daily-cause-list.json
  src/main/resources/locales/en/civil-and-family-daily-cause-list.json
  src/main/views/civil-and-family-daily-cause-list.njk
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-880

#879 PUB-1824 Remove "legal advisor" when constructing party
  src/main/modules/nunjucks/njkFilters.ts
  src/main/service/listManipulation/CivilFamilyAndMixedListService.ts
  src/main/service/listManipulation/EtListsService.ts
  src/main/service/listParseHelperService.ts
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/et-daily-list.njk
  src/main/views/et-fortnightly-list.njk
  src/main/views/family-daily-cause-list.njk
  src/main/views/sscs-daily-list.njk
  src/test/unit/modules/nunjucks/njkFilters.test.ts
  src/test/unit/service/listManipulation/civilFamilyAndMixedListService.test.ts
  src/test/unit/service/listManipulation/etListsService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-879
