Repository hmcts/pip-frontend, pull requests merged in 2023-06, with the labels that each got.

#929 PUB-1975 sorry list no longer available
  src/main/controllers/CopDailyCauseListController.ts
  src/main/controllers/CrownDailyListController.ts
  src/main/controllers/CrownFirmListController.ts
  src/main/controllers/CrownWarnedListController.ts
  src/main/controllers/DailyCauseListController.ts
  src/main/controllers/EtDailyListController.ts
  src/main/controllers/EtFortnightlyListController.ts
  src/main/controllers/FlatFileController.ts
  src/main/controllers/IacDailyListController.ts
  src/main/controllers/MagistratesPublicListController.ts
  src/main/controllers/MagistratesStandardListController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/controllers/SscsDailyListController.ts
  src/main/controllers/TribunalNationalListsController.ts
  src/main/helpers/listHelper.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/cy/list-not-found.json
  src/main/resources/locales/en/list-not-found.json
  src/main/resources/requests/publicationRequests.ts
  src/main/service/publicationService.ts
  src/main/views/list-not-found.njk
  src/test/helpers/listHelper.test.ts
  src/test/unit/controllers/CrownDailyListController.test.ts
  src/test/unit/controllers/CrownFirmListController.test.ts
  src/test/unit/controllers/CrownWarnedListController.test.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/EtDailyListController.test.ts
  src/test/unit/controllers/EtFortnightlyListController.test.ts
  src/test/unit/controllers/IacDailyListController.test.ts
  src/test/unit/controllers/MagistratesPublicListController.test.ts
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/controllers/SscsDailyListController.test.ts
  src/test/unit/controllers/TribunalNationalListsController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-929

#936 PUB-1847 functional test for single justice procedure public flow
  src/test/end-to-end/tests/single-justice-procedure-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-936

#958 Pub 1841
  src/test/end-to-end/tests/admin/user-management-test.ts
  src/test/end-to-end/tests/custom-steps.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-958

#961 Pub 1839 manage media account request
  src/test/e2e/PageObjects/AdminDashboard.page.ts
  src/test/e2e/PageObjects/CreateMediaAccount.page.ts
  src/test/e2e/PageObjects/MediaAccountApproval.page.ts
  src/test/e2e/PageObjects/MediaAccountRejection.page.ts
  src/test/e2e/PageObjects/MediaAccountRejectionConfirmation.page.ts
  src/test/e2e/PageObjects/MediaAccountRejectionReasons.page.ts
  src/test/e2e/PageObjects/MediaAccountRequestSubmitted.page.ts
  src/test/e2e/PageObjects/MediaAccountRequests.page.ts
  src/test/e2e/PageObjects/MediaAccountReview.page.ts
  src/test/e2e/PageObjects/SignIn.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/end-to-end/shared/mocks/testFile.pdf
  src/test/end-to-end/tests/admin/create-new-account-test.ts
  src/test/end-to-end/tests/admin/manage-media-account-request-test.ts
  src/test/end-to-end/tests/admin/user-management-test.ts
  src/test/end-to-end/tests/custom-steps.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-961

#964 Added functional tests for cft-Idam-basic-flow
  src/test/config.ts
  src/test/e2e/PageObjects/CftAuthenticationFailed.page.ts
  src/test/e2e/PageObjects/SignIn.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-964

#973 Update known issues
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-973

#966 PUB-1918 Add brackets to case sequence indicators
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/care-standards-list.njk
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/cop-daily-cause-list.njk
  src/main/views/crown-daily-list.njk
  src/main/views/crown-firm-list.njk
  src/main/views/daily-cause-list.njk
  src/main/views/et-daily-list.njk
  src/main/views/et-fortnightly-list.njk
  src/main/views/family-daily-cause-list.njk
  src/main/views/iac-daily-list.njk
  src/main/views/magistrates-public-list.njk
  src/main/views/magistrates-standard-list.njk
  src/main/views/primary-health-list.njk
  src/test/end-to-end/shared/mocks/civilAndFamilyDailyCauseList.json
  src/test/end-to-end/shared/mocks/etDailyList.json
  src/test/unit/mocks/careStandardsList.json
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/copDailyCauseList.json
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/crownFirmList.json
  src/test/unit/mocks/crownFirmSemiDigested.json
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/etDailyList.json
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/familyDailyCauseListWithReorderedPartyMappings.json
  src/test/unit/mocks/firmlistfullyprocessed.json
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/mocks/magistratesPublicList.json
  src/test/unit/mocks/magsStandardList.json
  src/test/unit/mocks/primaryHealthList.json
  src/test/unit/modules/nunjucks/njkFilters.test.ts
  src/test/unit/service/listManipulation/crownFirmListService.test.ts
  src/test/unit/service/listManipulation/etListsService.test.ts
  src/test/unit/service/listManipulation/tribunalNationalListsService.test.ts
  src/test/unit/views/et-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-966

#968 Pub 2048 configure list
  src/test/end-to-end/tests/cft-idam/sjp-list-type-filtering.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-968

#969 PUB-2026 Remove setting of result count/indexes for IOS devices
  package.json
  src/main/assets/js/LICENSE.txt
  src/main/assets/js/README.md
  src/main/assets/js/accessible-autocomplete.min.js
  src/main/assets/js/accessible-autocomplete.min.js.map
  webpack/accessible-autocomplete.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-969

#967 Pub 1964
  src/main/service/sjpFilterService.ts
  src/test/unit/service/sjpFilterService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-967

#977 Increase memory allocation + remove debug
  charts/pip-frontend/values.dev.template.yaml
  package.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-977

#979 Updated suppression formatting
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-979

#975 Pub 2011 Functional test for banner navigation
  src/test/end-to-end/tests/banner-navigation-test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-975

#981 Fix new vulnurability
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-981

#965 PUB-1953 - Azure B2C Welsh
  config/test.json
  src/main/authentication/authenticationHandler.ts
  src/main/controllers/SignInController.ts
  src/main/resources/locales/cy/account-home.json
  src/main/resources/locales/cy/admin-rejected-login.json
  src/main/routes/routes.ts
  src/test/end-to-end/tests/azure-screen-flow-welsh-test.ts
  src/test/routes/login.test.ts
  src/test/routes/sign-in.test.ts
  src/test/unit/authentication/authenticationHandler.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-965

#983 Fixed vulnerability
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-983

#974 PUB-1844 Remove SJP download button if no PDF and Excel files
  src/main/controllers/ListDownloadFilesController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/service/listDownloadService.ts
  src/main/views/list-download-files.njk
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/test/unit/controllers/ListDownloadFilesController.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/service/listDownloadService.test.ts
  src/test/unit/views/list-download-files.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-974

#980 Pub 1965
  src/main/service/sjpFilterService.ts
  src/test/unit/service/sjpFilterService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-980
