Repository hmcts/pip-frontend, pull requests merged in 2023-10, with the labels that each got.

#1120 PUB-2006 Upgrade govuk frontend to v4.7.0
  package.json
  src/main/assets/scss/main.scss
  src/main/views/cookie-policy.njk
  src/main/views/macros/common-components.njk
  src/main/views/macros/sjp-common.njk
  src/main/views/subscription-management.njk
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1120

#1116 PUB-2115 - Switch to Express Session
  jestEnvVars.js
  package.json
  src/main/app.ts
  src/main/authentication/authenticationHandler.ts
  src/main/bundles/cookie-preferences.ts
  src/main/cacheManager.ts
  src/main/controllers/SessionExpiringController.ts
  src/main/resources/locales/cy/cookie-policy.json
  src/main/resources/locales/en/cookie-policy.json
  src/main/routes/routes.ts
  src/main/service/sessionManagementService.ts
  src/main/views/session-expiring.njk
  src/test/e2e/PageObjects/CourtList.page.ts
  src/test/routes/session-expired-logout.test.ts
  src/test/unit/assets/cacheManager.test.ts
  src/test/unit/authentication/authenticationHandler.test.ts
  src/test/unit/controllers/SessionExpiringController.test.ts
  src/test/unit/requests/utils/pendingSubscriptionsFromCache.test.ts
  src/test/unit/service/sessionManagementService.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1116

#1133 Removed known issues file + updated postcss version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1133

#1131 PUB-2047 - Added hyperlinks to unsubscribe + bulk unsubscribe
  src/main/resources/locales/cy/bulk-unsubscribe-confirmed.json
  src/main/resources/locales/cy/unsubscribe-confirmation.json
  src/main/resources/locales/en/bulk-unsubscribe-confirmed.json
  src/main/resources/locales/en/unsubscribe-confirmation.json
  src/main/views/bulk-unsubscribe-confirmed.njk
  src/main/views/unsubscribe-confirmation.njk
  src/test/unit/views/bulk-unsubscribe-confirmed.test.ts
  src/test/unit/views/unsubscribe-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1131

#1132 Pub 2083
  src/main/controllers/BlobViewJsonController.ts
  src/test/unit/controllers/BlobViewJsonController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1132

#1136 Pub 1833 Manage Third-Party Users
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/system-admin/manage-third-party-users-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1136

#1135 PUB-2195 Added dynatrace script
  src/main/views/template.njk
  src/test/unit/views/delete-court-reference-data.test.ts
  src/test/unit/views/remove-list-search.test.ts
  src/test/unit/views/search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1135, enable_keep_helm

#1130 PUB-2162 Use v2 delete account endpoint to check authorisation
  src/main/resources/requests/accountManagementRequests.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/views/delete-user-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1130

#1137 Removed old test framework
  .eslintrc.js
  README.md
  package.json
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/AccountHome.page.ts
  src/test/e2e/PageObjects/AlphabeticalSearch.page.ts
  src/test/e2e/PageObjects/CaseEventGlossary.page.ts
  src/test/e2e/PageObjects/Common.page.ts
  src/test/e2e/PageObjects/CourtList.page.ts
  src/test/e2e/PageObjects/DeleteUserConfirmation.page.ts
  src/test/e2e/PageObjects/Home.page.ts
  src/test/e2e/PageObjects/LiveCaseCourtSearchController.page.ts
  src/test/e2e/PageObjects/LiveCaseStatus.page.ts
  src/test/e2e/PageObjects/ManageThirdPartyUsers.page.ts
  src/test/e2e/PageObjects/MockSession.page.ts
  src/test/e2e/PageObjects/Search.page.ts
  src/test/e2e/PageObjects/SessionLoggedOut.page.ts
  src/test/e2e/PageObjects/SignIn.page.ts
  src/test/e2e/PageObjects/SingleJusticeProcedure.page.ts
  src/test/e2e/PageObjects/SjpPressList.page.ts
  src/test/e2e/PageObjects/SjpPublicList.page.ts
  src/test/e2e/PageObjects/SubscriptionManagement.page.ts
  src/test/e2e/PageObjects/SummaryOfPublications.page.ts
  src/test/e2e/PageObjects/SystemAdminDashboard.page.ts
  src/test/e2e/PageObjects/UpdateUserConfirmation.page.ts
  src/test/e2e/PageObjects/ViewOption.page.ts
  src/test/e2e/tests/specs.test.ts
  tsconfig.e2e.json
  wdio.conf.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1137

#1140 Fix vulnurability in Babel
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1140

#1134 PUB-2192 - Monthly dependency updates
  .github/workflows/a11y.yml
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/routes.yml
  .nvmrc
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1134

#1141 Increased window count
  package.json
  src/test/end-to-end/tests/single-justice-procedure-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1141
