Repository hmcts/pip-frontend, pull requests merged in 2023-08, with the labels that each got.

#1033 Pub 2054 - Add SJP delta press list
  src/main/controllers/SjpPressListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/single-justice-procedure-press-new-cases.json
  src/main/resources/locales/bill/single-justice-procedure-press.json
  src/main/resources/locales/cy/single-justice-procedure-press-new-cases.json
  src/main/resources/locales/cy/single-justice-procedure-press.json
  src/main/resources/locales/en/single-justice-procedure-press-new-cases.json
  src/main/resources/locales/en/single-justice-procedure-press.json
  src/main/routes/routes.ts
  src/main/views/single-justice-procedure-press.njk
  src/test/e2e/tests/specs.test.ts
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
  src/test/routes/single-justice-procedure-press.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/mocks/SJPMockPage.json
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/publication.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1033

#1056 PUB-2108 - Increase limit + requests
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.stg.template.yaml
  charts/pip-frontend/values.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1056

#1059 PUB-1654 Handle SJP press list with missing address, forename and surname
  src/main/service/listManipulation/SjpPressListService.ts
  src/main/service/listParseHelperService.ts
  src/test/unit/mocks/sjp-press-list.json
  src/test/unit/service/listManipulation/sjpPressListService.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1059

#1063 Pub 2033
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/hmi-publication-receipt-test.ts
  src/test/end-to-end/tests/system-admin/delete-court-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1063

#1061 Pub 1674
  src/main/resources/locales/bill/iac-daily-list.json
  src/main/resources/locales/en/iac-daily-list.json
  src/test/unit/views/iac-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1061

#1062 PUB-1696 Care Standards List clean-up
  src/main/resources/locales/bill/care-standards-list.json
  src/main/resources/locales/cy/care-standards-list.json
  src/main/resources/locales/en/care-standards-list.json
  src/main/service/listManipulation/TribunalNationalListsService.ts
  src/main/views/care-standards-list.njk
  src/test/unit/mocks/primaryHealthList.json
  src/test/unit/service/listManipulation/tribunalNationalListsService.test.ts
  src/test/unit/views/care-standards-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1062

#1064 PUB-1655 Primary Health List clean-up
  src/main/resources/locales/bill/primary-health-list.json
  src/main/resources/locales/cy/primary-health-list.json
  src/main/resources/locales/en/primary-health-list.json
  src/main/views/primary-health-list.njk
  src/test/end-to-end/tests/sorting-list-table-test.ts
  src/test/unit/views/primary-health-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1064

#1069 Pub 2033
  src/test/end-to-end/tests/hmi-publication-receipt-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1069

#1060 PUB-2119 - Dependency updates
  .nvmrc
  package.json
  src/main/views/alphabetical-search.njk
  src/main/views/location-name-search.njk
  src/main/views/macros/sjp-common.njk
  src/main/views/subscription-configure-list.njk
  src/test/routes/single-justice-procedure-press.test.ts
  src/test/routes/sscs-daily-list.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SscsDailyListController.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
  src/test/unit/views/sscs-daily-list-test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1060

#1074 PUB-2072 - Updated welsh for View Options page
  src/main/resources/locales/cy/view-option.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1074

#1071 PUB-2106 COP_DAILY_CAUSE_LIST style guide update
  src/main/service/listManipulation/CopDailyListService.ts
  src/main/views/cop-daily-cause-list.njk
  src/test/unit/mocks/copDailyCauseList.json
  src/test/unit/views/cop-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1071

#1076 PUB-2045 - Pass through of Welsh to CFT IDAM
  src/main/controllers/CftLoginController.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/unit/controllers/CftLoginController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1076

#1073 PUB-2020 Display Welsh months on subscription pages
  src/main/service/subscriptionService.ts
  src/test/unit/service/subscriptionService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1073

#1075 PUB-1989 Update Welsh list name on Subscription Configure List page
  src/main/service/subscriptionService.ts
  src/main/views/subscription-configure-list.njk
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1075

#1078 Pub 2070
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/test/config.ts
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/admin/user-management-test.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1078

#1080 Use Chrome for Testing to auto integrate the e2e tests with the Chrome version
  package.json
  wdio.conf.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1080

#1072 Pub 1904
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/service/listManipulation/iacDailyListService.test.ts
  src/test/unit/views/iac-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1072

#1077 PUB-2038 - Updated language files
  src/main/resources/locales/bill/care-standards-list.json
  src/main/resources/locales/bill/civil-and-family-daily-cause-list.json
  src/main/resources/locales/bill/cop-daily-cause-list.json
  src/main/resources/locales/bill/crown-daily-list.json
  src/main/resources/locales/bill/crown-firm-list.json
  src/main/resources/locales/bill/crown-warned-list.json
  src/main/resources/locales/bill/daily-cause-list.json
  src/main/resources/locales/bill/et-daily-list.json
  src/main/resources/locales/bill/et-fortnightly-list.json
  src/main/resources/locales/bill/family-daily-cause-list.json
  src/main/resources/locales/bill/iac-daily-list.json
  src/main/resources/locales/bill/magistrates-public-list.json
  src/main/resources/locales/bill/magistrates-standard-list.json
  src/main/resources/locales/bill/primary-health-list.json
  src/main/resources/locales/bill/single-justice-procedure-press.json
  src/main/resources/locales/bill/single-justice-procedure.json
  src/main/resources/locales/bill/sscs-daily-list.json
  src/main/resources/locales/cy/account-home.json
  src/main/resources/locales/cy/care-standards-list.json
  src/main/resources/locales/cy/civil-and-family-daily-cause-list.json
  src/main/resources/locales/cy/cop-daily-cause-list.json
  src/main/resources/locales/cy/create-media-account.json
  src/main/resources/locales/cy/crown-daily-list.json
  src/main/resources/locales/cy/crown-firm-list.json
  src/main/resources/locales/cy/crown-warned-list.json
  src/main/resources/locales/cy/daily-cause-list.json
  src/main/resources/locales/cy/et-daily-list.json
  src/main/resources/locales/cy/et-fortnightly-list.json
  src/main/resources/locales/cy/family-daily-cause-list.json
  src/main/resources/locales/cy/iac-daily-list.json
  src/main/resources/locales/cy/magistrates-public-list.json
  src/main/resources/locales/cy/magistrates-standard-list.json
  src/main/resources/locales/cy/media-rejected-login.json
  src/main/resources/locales/cy/primary-health-list.json
  src/main/resources/locales/cy/session-expired.json
  src/main/resources/locales/cy/sign-in.json
  src/main/resources/locales/cy/single-justice-procedure-press.json
  src/main/resources/locales/cy/single-justice-procedure.json
  src/main/resources/locales/cy/sscs-daily-list.json
  src/main/resources/locales/en/session-expired.json
  src/main/service/listManipulation/EtListsService.ts
  src/main/views/create-admin-account-summary.njk
  src/test/end-to-end/tests/login-test.ts
  src/test/routes/manual-upload-summary.test.ts
  src/test/unit/views/et-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1077

#1065 Pub 1651
  src/main/controllers/CrownDailyListController.ts
  src/main/resources/locales/bill/crown-daily-list.json
  src/main/resources/locales/cy/crown-daily-list.json
  src/main/resources/locales/en/crown-daily-list.json
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/views/crown-daily-list.njk
  src/test/unit/controllers/CrownDailyListController.test.ts
  src/test/unit/views/crown-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1065
