Repository hmcts/pip-frontend, pull requests merged in 2023-11, with the labels that each got.

#1144 PUB-2017 - Reporting restrictions for Crown Daily list
  src/main/resources/locales/bill/crown-daily-list.json
  src/main/resources/locales/cy/crown-daily-list.json
  src/main/resources/locales/en/crown-daily-list.json
  src/main/views/crown-daily-list.njk
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/views/crown-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1144

#1145 PUB-2161 - Add Important Info to SJP Lists
  src/main/controllers/SjpPressListController.ts
  src/main/resources/locales/bill/single-justice-procedure-press.json
  src/main/resources/locales/cy/single-justice-procedure-press.json
  src/main/resources/locales/en/single-justice-procedure-press.json
  src/main/views/single-justice-procedure-press.njk
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1145

#1143 PUB-2210 - Removed uptime from info endpoint
  src/main/helpers/infoProvider.ts
  src/test/unit/views/info.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1143

#1142 PUB-2153 OPA Press List style guide
  src/main/controllers/OpaPressListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/opa-press-list.json
  src/main/resources/locales/cy/opa-press-list.json
  src/main/resources/locales/en/opa-press-list.json
  src/main/resources/media-account-rejection-reasons-lookup.json
  src/main/routes/routes.ts
  src/main/service/listManipulation/OpaPressListService.ts
  src/main/views/opa-press-list.njk
  src/test/routes/opa-press-list.test.ts
  src/test/unit/controllers/OpaPressListController.test.ts
  src/test/unit/mocks/opaPressList.json
  src/test/unit/mocks/returnedArtefacts.json
  src/test/unit/service/listManipulation/OpaPressListService.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/opa-press-list.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1142

#1146 PUB-1976 Update no list holding message
  src/main/resources/locales/cy/summary-of-publications.json
  src/main/resources/locales/en/summary-of-publications.json
  src/main/views/summary-of-publications.njk
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1146

#1149 PUB-2191-Text update to identified instances of (s) and full stop in …
  src/main/resources/locales/cy/bulk-unsubscribe-confirmation.json
  src/main/resources/locales/cy/case-name-search-results.json
  src/main/resources/locales/cy/case-reference-number-search-results.json
  src/main/resources/locales/cy/location-name-search.json
  src/main/resources/locales/cy/party-name-search-results.json
  src/main/resources/locales/cy/subscription-configure-list-confirmed.json
  src/main/resources/locales/cy/subscription-configure-list.json
  src/main/resources/locales/cy/subscription-confirmed.json
  src/main/resources/locales/cy/unsubscribe-confirmation.json
  src/main/resources/locales/en/bulk-unsubscribe-confirmation.json
  src/main/resources/locales/en/case-name-search-results.json
  src/main/resources/locales/en/case-reference-number-search-results.json
  src/main/resources/locales/en/location-name-search.json
  src/main/resources/locales/en/party-name-search-results.json
  src/main/resources/locales/en/subscription-configure-list-confirmed.json
  src/main/resources/locales/en/subscription-configure-list.json
  src/main/resources/locales/en/subscription-confirmed.json
  src/main/resources/locales/en/unsubscribe-confirmation.json
  src/main/views/party-name-search-results.njk
  src/main/views/subscription-configure-list-confirmed.njk
  src/main/views/subscription-confirmed.njk
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/unit/views/bulk-unsubscribe-confirmation.test.ts
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/case-reference-number-search-results.test.ts
  src/test/unit/views/location-name-search.test.ts
  src/test/unit/views/party-name-search-results.test.ts
  src/test/unit/views/subscription-configure-list-confirmed.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
  src/test/unit/views/subscription-confirmed.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1149

#1151 PUB-1938 - Remove Hardcoded SJP Message
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/resources/locales/cy/summary-of-publications.json
  src/main/resources/locales/en/summary-of-publications.json
  src/main/views/summary-of-publications.njk
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1151

#1152 PUB-1673 SJP Public List validation schema update
  src/test/end-to-end/shared/mocks/sjp-public-list.json
  src/test/unit/mocks/sjp-public-list.json
  src/test/unit/service/listManipulation/sjpPublicListService.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1152

#1155 PUB-2206 - Dependency Updates
  package.json
  src/main/authentication/cftIdamAuthentication.ts
  src/test/unit/authentication/cftIdamAuthentication.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1155

#1153 PUB-2230 Handle parties for hearing with multiple cases
  src/main/service/listManipulation/CivilFamilyAndMixedListService.ts
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/family-daily-cause-list.njk
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/service/listManipulation/civilFamilyAndMixedListService.test.ts
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1153

#1159 PUB-2235 - Updated common platform message
  src/main/resources/locales/cy/sign-in.json
  src/main/resources/locales/en/sign-in.json
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1159

#1160 PUB-2163 - Media Account Request
  src/main/resources/locales/cy/account-request-submitted.json
  src/main/resources/locales/en/account-request-submitted.json
  src/test/unit/views/account-request-submitted.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1160
