Repository hmcts/pip-frontend, pull requests merged in 2023-02, with the labels that each got.

#759 auto update PR
  .github/workflows/update-pr.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-759

#758 Pub 1810 - nodeLinker
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.3.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-758

#766 Fix security vulnerability CVE-2022-25881
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-766

#732 PUB-1769 Update last signed-in date for media accounts
  src/main/authentication/authenticationHandler.ts
  src/test/unit/authentication/authenticationHandler.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-732

#723 PUB-1759 SIGDEV Failure
  .github/workflows/update-pr.yml
  src/main/controllers/AdminManagementController.ts
  src/test/unit/controllers/AdminManagementController.test.ts
  src/test/unit/views/admin-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-723

#761 Updated the update-pr script
  .github/workflows/update-pr.yml
  .gitignore
  .yarnrc.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-761

#760 PUB-1776 - Update config beyond 3.3.7
  package.json
  src/test/unit/resources/requests/utils/axiosConfigTest.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-760

#772 PUB-1816 update dependencies
  .gitignore
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-772

#774 PUB-1795 Display organisation name party for Family and Mixed list
  src/main/controllers/CrownDailyListController.ts
  src/main/controllers/CrownFirmListController.ts
  src/main/controllers/DailyCauseListController.ts
  src/main/controllers/MagistratesPublicListController.ts
  src/main/controllers/MagistratesStandardListController.ts
  src/main/service/listManipulation/CivilFamilyAndMixedListService.ts
  src/main/service/listParseHelperService.ts
  src/test/routes/civil-and-family-daily-cause-list.test.ts
  src/test/routes/crown-daily-list.test.ts
  src/test/routes/daily-cause-list.test.ts
  src/test/routes/family-daily-cause-list.test.ts
  src/test/unit/controllers/CrownDailyListController.test.ts
  src/test/unit/controllers/CrownFirmListController.test.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/MagistratesPublicListController.test.ts
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/service/listManipulation/civilFamilyAndMixedListService.test.ts
  src/test/unit/service/listParseHelperService.test.ts
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-774

#773 Pub 1753 Pipeline configurations for tests
  Jenkinsfile_nightly
  package.json
  src/test/end-to-end/tests/login-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-773

#770 PUB-1669 System Admin Audit Logs
  .editorconfig
  src/main/controllers/AuditLogViewerController.ts
  src/main/controllers/BlobViewJsonController.ts
  src/main/controllers/BulkCreateMediaAccountsConfirmationController.ts
  src/main/controllers/CreateSystemAdminAccountSummaryController.ts
  src/main/controllers/DeleteCourtReferenceDataConfirmationController.ts
  src/main/controllers/DeleteUserConfirmationController.ts
  src/main/controllers/DeleteUserController.ts
  src/main/controllers/ManageThirdPartyUsersController.ts
  src/main/controllers/ManageThirdPartyUsersSubscriptionsController.ts
  src/main/controllers/ManageThirdPartyUsersViewController.ts
  src/main/controllers/ManageUserController.ts
  src/main/controllers/ManualReferenceDataUploadSummaryController.ts
  src/main/controllers/ReferenceDataDownloadController.ts
  src/main/controllers/UpdateUserConfirmationController.ts
  src/main/controllers/UpdateUserController.ts
  src/main/controllers/UserManagementController.ts
  src/main/resources/locales/bill/system-admin-dashboard.json
  src/main/resources/locales/cy/audit-log-viewer.json
  src/main/resources/locales/cy/system-admin-dashboard.json
  src/main/resources/locales/en/audit-log-viewer.json
  src/main/resources/locales/en/system-admin-dashboard.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/service/auditLogService.ts
  src/main/service/userManagementService.ts
  src/main/views/audit-log-viewer.njk
  src/test/a11y/a11y.ts
  src/test/routes/audit-log-viewer.test.ts
  src/test/unit/controllers/AuditLogViewerController.test.ts
  src/test/unit/controllers/BulkCreateMediaAccountsConfirmationController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/resources/requests/utils/axiosConfigTest.ts
  src/test/unit/service/auditLogService.test.ts
  src/test/unit/service/userManagementService.test.ts
  src/test/unit/views/audit-log-viewer.test.ts
  src/test/unit/views/system-admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-770

#777 PUB-1852 - Selecting sensitivity
  src/main/controllers/ManualUploadController.ts
  src/main/controllers/ManualUploadSummaryController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/file-upload-summary.json
  src/main/resources/locales/cy/manual-upload.json
  src/main/resources/locales/en/file-upload-summary.json
  src/main/resources/locales/en/manual-upload.json
  src/main/service/manualUploadService.ts
  src/main/service/publicationService.ts
  src/main/views/file-upload-summary.njk
  src/main/views/manual-upload.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/manual-upload-sensitivity-test.ts
  src/test/unit/controllers/ManualUploadController.test.ts
  src/test/unit/controllers/ManualUploadSummaryController.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/file-upload-summary.test.ts
  src/test/unit/views/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-777

#757 Pub 1756 - Lefthook
  .github/PULL_REQUEST_TEMPLATE.md
  .lefthook/pre-push/check-for-unsuppressed-vulns.py
  .yarn/releases/yarn-3.3.1.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  lefthook.yml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-757

#781 Nightly pipeline test-url environment variable fix
  Jenkinsfile_nightly
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-781

#783 Date time format fixed in json file
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/magistratesPublicList.json
  src/test/unit/mocks/sscsDailyList.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-783

#667 PUB-1665 Refactor code for all artefacts per location endpoint
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/resources/requests/publicationRequests.ts
  src/main/service/publicationService.ts
  src/test/a11y/a11y.ts
  src/test/end-to-end/tests/manual-upload-sensitivity-test.ts
  src/test/routes/blob-view-locations.test.ts
  src/test/unit/service/publicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-667

#785 PUB-1794 Remove logging of error.request
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/caseEventGlossaryRequests.ts
  src/main/resources/requests/channelManagementRequests.ts
  src/main/resources/requests/dataManagementRequests.ts
  src/main/resources/requests/liveCaseRequests.ts
  src/main/resources/requests/locationRequests.ts
  src/main/resources/requests/publicationRequests.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/requests/caseEventGlossaryRequests.test.ts
  src/test/unit/requests/channelManagementRequests.test.ts
  src/test/unit/requests/dataManagementRequests.test.ts
  src/test/unit/requests/liveCaseRequests.test.ts
  src/test/unit/requests/locationRequests.test.ts
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-785

#790 PUB-1858 NoMatch artefacts in blob explorer
  src/main/controllers/BlobViewJsonController.ts
  src/main/controllers/BlobViewLocationController.ts
  src/main/controllers/BlobViewPublicationsController.ts
  src/main/resources/locales/bill/blob-view-publications.json
  src/main/resources/locales/cy/blob-view-publications.json
  src/main/resources/locales/en/blob-view-publications.json
  src/main/resources/requests/publicationRequests.ts
  src/main/service/publicationService.ts
  src/main/service/summaryOfPublicationsService.ts
  src/main/views/blob-view-json.njk
  src/main/views/blob-view-publications.njk
  src/test/a11y/a11y.ts
  src/test/routes/blob-view-locations.test.ts
  src/test/unit/controllers/BlobViewJsonController.test.ts
  src/test/unit/controllers/BlobViewLocationController.test.ts
  src/test/unit/controllers/BlobViewPublicationsController.test.ts
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/service/SummaryOfPublicationsService.test.ts
  src/test/unit/service/publicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-790

#786 PUB-1799 - List Type Sorting
  src/main/resources/locales/en/manual-upload.json
  src/main/service/manualUploadService.ts
  src/main/views/manual-upload.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/ManualUpload.page.ts
  src/test/unit/service/manualUploadService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-786

#784 PUB-1808 updated download as PDF
  src/main/controllers/ListDownloadFilesController.ts
  src/main/resources/requests/channelManagementRequests.ts
  src/main/service/listDownloadService.ts
  src/main/service/manualUploadService.ts
  src/test/end-to-end/tests/delete-court-validations-test.ts
  src/test/end-to-end/tests/manual-upload-sensitivity-test.ts
  src/test/unit/requests/channelManagementRequests.test.ts
  src/test/unit/service/listDownloadService.test.ts
  wdio.conf.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-784

#794 PUB-1815 Add filter functionality to SJP public list
  src/main/assets/scss/main.scss
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/resources/locales/bill/single-justice-procedure-press.json
  src/main/resources/locales/bill/single-justice-procedure.json
  src/main/resources/locales/bill/sjp-common.json
  src/main/resources/locales/cy/single-justice-procedure-press.json
  src/main/resources/locales/cy/single-justice-procedure.json
  src/main/resources/locales/cy/sjp-common.json
  src/main/resources/locales/en/single-justice-procedure-press.json
  src/main/resources/locales/en/single-justice-procedure.json
  src/main/resources/locales/en/sjp-common.json
  src/main/routes/routes.ts
  src/main/service/filterService.ts
  src/main/service/listManipulation/SjpPressListService.ts
  src/main/service/listManipulation/SjpPublicListService.ts
  src/main/service/sjpFilterService.ts
  src/main/views/macros/sjp-common.njk
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/SingleJusticeProcedure.page.ts
  src/test/e2e/PageObjects/SjpPressList.page.ts
  src/test/e2e/PageObjects/SjpPublicList.page.ts
  src/test/e2e/PageObjects/SummaryOfPublications.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/routes/single-justice-procedure-press.test.ts
  src/test/routes/single-justice-procedure-public.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/mocks/SJPMockPage.json
  src/test/unit/service/listManipulation/sjpPressListService.test.ts
  src/test/unit/service/listManipulation/sjpPublicListService.test.ts
  src/test/unit/service/sjpFilterService.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-794
