Repository hmcts/pip-frontend, pull requests merged in 2023-03, with the labels that each got.

#792 PUB-1798 Fix subscription by case URN
  src/main/resources/locales/cy/bulk-unsubscribe.json
  src/main/resources/locales/cy/subscription-management.json
  src/main/resources/locales/en/bulk-unsubscribe.json
  src/main/resources/locales/en/subscription-management.json
  src/main/resources/requests/utils/pendingSubscriptionsFromCache.ts
  src/main/service/subscriptionService.ts
  src/main/views/pending-subscriptions.njk
  src/test/e2e/Helpers/Selectors.ts
  src/test/e2e/PageObjects/PendingSubscriptions.page.ts
  src/test/e2e/tests/specs.test.ts
  src/test/unit/requests/utils/pendingSubscriptionsFromCache.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/bulk-unsubscribe.test.ts
  src/test/unit/views/subscription-management.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-792

#791 PUB-1850 - Welsh text
  src/main/resources/locales/bill/sscs-daily-list-additional-hearings.json
  src/main/resources/locales/bill/sscs-daily-list.json
  src/main/resources/locales/cy/bulk-unsubscribe.json
  src/main/resources/locales/cy/create-media-account.json
  src/main/resources/locales/cy/sscs-daily-list-additional-hearings.json
  src/main/resources/locales/cy/sscs-daily-list.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-791

#797 PUB-1857
  .github/workflows/a11y.yml
  .github/workflows/routes.yml
  package.json
  src/main/cacheManager.ts
  src/test/a11y/a11y.ts
  src/test/a11y/case-name-search.test.ts
  src/test/a11y/case-reference-number-search.test.ts
  src/test/a11y/civil-daily-cause-list.test.ts
  src/test/a11y/search.test.ts
  src/test/a11y/subscription-urn-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-797

#787 PUB-1881 Display Location Specific Message
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/models/location.ts
  src/main/resources/locales/cy/summary-of-publications.json
  src/main/resources/locales/en/summary-of-publications.json
  src/main/views/summary-of-publications.njk
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-787

#795 PUB-1902 Remove Judiciary info from ET Lists
  src/main/service/listManipulation/EtListsService.ts
  src/test/unit/mocks/etDailyList-withdates.json
  src/test/unit/mocks/etDailyList.json
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/service/listManipulation/etListsService.test.ts
  src/test/unit/views/et-daily-list.test.ts
  src/test/unit/views/et-fortnightly-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-795

#821 PUB-1827 - Updated role from Media to Verified
  src/main/models/consts.ts
  src/test/unit/service/userManagementService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-821

#827 PUB-1910 - Dependency updates and assorted fun
  .nvmrc
  jest.config.js
  jest.routes.config.js
  package.json
  src/main/app.ts
  src/test/config.ts
  src/test/end-to-end/shared/shared-functions.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/delete-court-validations-test.ts
  src/test/end-to-end/tests/manual-upload-sensitivity-test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  webpack.config.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-827

#799 PUB-1895 Update Open Justice Statement
  src/main/controllers/CopDailyCauseListController.ts
  src/main/controllers/DailyCauseListController.ts
  src/main/controllers/SscsDailyListController.ts
  src/main/controllers/TribunalNationalListsController.ts
  src/main/resources/locales/bill/care-standards-list.json
  src/main/resources/locales/bill/civil-and-family-daily-cause-list.json
  src/main/resources/locales/bill/cop-daily-cause-list.json
  src/main/resources/locales/bill/daily-cause-list.json
  src/main/resources/locales/bill/family-daily-cause-list.json
  src/main/resources/locales/bill/open-justice-statement.json
  src/main/resources/locales/bill/sscs-daily-list.json
  src/main/resources/locales/cy/care-standards-list.json
  src/main/resources/locales/cy/civil-and-family-daily-cause-list.json
  src/main/resources/locales/cy/cop-daily-cause-list.json
  src/main/resources/locales/cy/daily-cause-list.json
  src/main/resources/locales/cy/family-daily-cause-list.json
  src/main/resources/locales/cy/open-justice-statement.json
  src/main/resources/locales/cy/sscs-daily-list.json
  src/main/resources/locales/en/care-standards-list.json
  src/main/resources/locales/en/civil-and-family-daily-cause-list.json
  src/main/resources/locales/en/cop-daily-cause-list.json
  src/main/resources/locales/en/daily-cause-list.json
  src/main/resources/locales/en/family-daily-cause-list.json
  src/main/resources/locales/en/open-justice-statement.json
  src/main/resources/locales/en/sscs-daily-list.json
  src/main/views/care-standards-list.njk
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/cop-daily-cause-list.njk
  src/main/views/daily-cause-list.njk
  src/main/views/family-daily-cause-list.njk
  src/main/views/sscs-daily-list.njk
  src/test/unit/controllers/CopDailyCauseListController.test.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/SscsDailyListController.test.ts
  src/test/unit/controllers/TribunalNationalListsController.test.ts
  src/test/unit/views/care-standards-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-799

#822 PUB-1828 Log info when finding CFT IDAM user
  package.json
  src/main/resources/requests/accountManagementRequests.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-822

#823 PUB-1807 - Changing of own account
  src/main/controllers/UpdateUserConfirmationController.ts
  src/main/controllers/UpdateUserController.ts
  src/main/resources/locales/cy/update-user.json
  src/main/resources/locales/en/update-user.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/routes/routes.ts
  src/main/views/update-user.njk
  src/test/end-to-end/tests/change-own-user-test.ts
  src/test/routes/update-user-confirmation.test.ts
  src/test/routes/update-user.test.ts
  src/test/unit/controllers/UpdateUserConfirmationController.test.ts
  src/test/unit/controllers/UpdateUserController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/views/update-user-confirmation.test.ts
  src/test/unit/views/update-user.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-823

#829 PUB-1896 Enhance audit log viewer
  .github/workflows/a11y.yml
  .github/workflows/routes.yml
  src/main/controllers/AuditLogDetailsController.ts
  src/main/controllers/BlobViewJsonController.ts
  src/main/controllers/BulkCreateMediaAccountsConfirmationController.ts
  src/main/controllers/CreateAdminAccountSummaryController.ts
  src/main/controllers/CreateSystemAdminAccountSummaryController.ts
  src/main/controllers/DeleteCourtReferenceDataConfirmationController.ts
  src/main/controllers/DeleteCourtSubscriptionConfirmationController.ts
  src/main/controllers/DeleteUserConfirmationController.ts
  src/main/controllers/DeleteUserController.ts
  src/main/controllers/ManageThirdPartyUsersController.ts
  src/main/controllers/ManageThirdPartyUsersSubscriptionsController.ts
  src/main/controllers/ManageThirdPartyUsersViewController.ts
  src/main/controllers/ManageUserController.ts
  src/main/controllers/ManualReferenceDataUploadSummaryController.ts
  src/main/controllers/ManualUploadSummaryController.ts
  src/main/controllers/MediaAccountApprovalController.ts
  src/main/controllers/MediaAccountRejectionController.ts
  src/main/controllers/ReferenceDataDownloadController.ts
  src/main/controllers/RemoveListConfirmationController.ts
  src/main/controllers/UpdateUserController.ts
  src/main/controllers/UserManagementController.ts
  src/main/resources/locales/cy/audit-log-details.json
  src/main/resources/locales/en/audit-log-details.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/resources/requests/dataManagementRequests.ts
  src/main/routes/routes.ts
  src/main/service/auditLogService.ts
  src/main/service/manualUploadService.ts
  src/main/service/userManagementService.ts
  src/main/views/audit-log-details.njk
  src/main/views/audit-log-viewer.njk
  src/test/a11y/a11y.ts
  src/test/end-to-end/tests/system-admin-audit-log-test.ts
  src/test/routes/audit-log-details.test.ts
  src/test/unit/controllers/AuditLogDetailsController.test.ts
  src/test/unit/controllers/AuditLogViewerController.test.ts
  src/test/unit/controllers/ManualUploadSummaryController.test.ts
  src/test/unit/controllers/UpdateUserController.test.ts
  src/test/unit/mocks/etDailyList-withdates.json
  src/test/unit/mocks/etDailyList.json
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/requests/dataManagementRequests.test.ts
  src/test/unit/service/auditLogService.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/userManagementService.test.ts
  src/test/unit/views/audit-log-details.test.ts
  src/test/unit/views/audit-log-viewer.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-829

#836 PUB-1594 - Updated welsh text
  src/main/models/listType.ts
  src/main/resources/listLookup.json
  src/main/service/subscriptionService.ts
  src/test/unit/service/subscriptionService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-836

#834 PUB-1934 - Webpack/Dart-sass warnings
  jest.config.js
  src/main/app.ts
  src/main/assets/scss/main.scss
  src/test/e2e/tests/specs.test.ts
  webpack/scss.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-834

#841 Implemented allure reports
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/test/end-to-end/functional.conf.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-841

#839 PUB-1961 - Branch name in Dev Env
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/template.njk
  src/test/unit/views/manual-reference-data-upload.test.ts
  src/test/unit/views/manual-upload.test.ts
  src/test/unit/views/view-option.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-839

#843 Implemented cross-browser testing
  Jenkinsfile_nightly
  package.json
  src/test/end-to-end/crossbrowser.conf.ts
  src/test/end-to-end/tests/change-own-user-test.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/manual-upload-sensitivity-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-843
