Repository hmcts/pip-frontend, pull requests merged in 2023-09, with the labels that each got.

#1082 PUB-2129 - Remove court room name from ET Fortnightly
  src/main/resources/locales/bill/et-fortnightly-list.json
  src/main/resources/locales/cy/et-fortnightly-list.json
  src/main/resources/locales/en/et-fortnightly-list.json
  src/main/views/et-fortnightly-list.njk
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/views/et-fortnightly-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1082

#1083 PUB-2128 - Removed Rep from ET Daily List
  src/main/resources/locales/bill/et-daily-list.json
  src/main/resources/locales/cy/et-daily-list.json
  src/main/resources/locales/en/et-daily-list.json
  src/main/views/et-daily-list.njk
  src/test/end-to-end/shared/mocks/etDailyList.json
  src/test/unit/mocks/etDailyList.json
  src/test/unit/service/listManipulation/etListsService.test.ts
  src/test/unit/views/et-daily-list.test.ts
  src/test/unit/views/et-fortnightly-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1083

#1081 PUB-2124 - Updated renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1081

#1084 PUB-1671 Magistrates Public List clean-up
  src/main/controllers/MagistratesPublicListController.ts
  src/main/resources/locales/bill/magistrates-public-list.json
  src/main/resources/locales/cy/magistrates-public-list.json
  src/main/resources/locales/en/magistrates-public-list.json
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/views/crown-daily-list.njk
  src/main/views/magistrates-public-list.njk
  src/test/unit/controllers/MagistratesPublicListController.test.ts
  src/test/unit/mocks/magistratesPublicList.json
  src/test/unit/service/listManipulation/crimeListsService.test.ts
  src/test/unit/views/magistrates-public-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1084

#1079 PUB-1998 Run manual JSON upload e2e test with fixed content date for Courtel
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1079

#1105 PUB-1984 - Updated test files for SJP Public to match schema
  src/test/end-to-end/shared/mocks/sjp-public-list.json
  src/test/unit/mocks/sjp-public-list.json
  src/test/unit/views/blob-view-json.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1105

#1106 PUB-2022 Update to use v2 bulk delete subscription endpoint
  src/main/controllers/BulkUnsubscribeConfirmationController.ts
  src/main/resources/requests/subscriptionRequests.ts
  src/main/service/subscriptionService.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/subscriptionService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1106

#1107 PUB-2147 - Updated dependencies
  .nvmrc
  README.md
  jest.a11y.config.js
  jest.config.js
  jest.routes.config.js
  package.json
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
  src/test/unit/controllers/CopDailyCauseListController.test.ts
  src/test/unit/controllers/CrownDailyListController.test.ts
  src/test/unit/controllers/CrownFirmListController.test.ts
  src/test/unit/controllers/DailyCauseListController.test.ts
  src/test/unit/controllers/IacDailyListController.test.ts
  src/test/unit/controllers/MagistratesPublicListController.test.ts
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/views/summary-of-publications.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1107

#1108 PUB-1982 Allow organisation details in SJP Public List accused party
  src/main/service/listManipulation/SjpPublicListService.ts
  src/test/a11y/a11y.ts
  src/test/end-to-end/shared/mocks/sjp-public-list.json
  src/test/routes/single-justice-procedure-public.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/mocks/SJPMockPage.json
  src/test/unit/mocks/sjp-public-list.json
  src/test/unit/service/listManipulation/sjpPublicListService.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1108

#1111 PUB-2126 Add unprocessed request page for requests blocked by firewall
  src/main/controllers/UnprocessedRequestController.ts
  src/main/resources/locales/cy/unprocessed-request.json
  src/main/resources/locales/en/unprocessed-request.json
  src/main/routes/routes.ts
  src/main/views/unprocessed-request.njk
  src/test/routes/unprocessed-request.test.ts
  src/test/unit/controllers/unprocessedRequestController.test.ts
  src/test/unit/views/unprocessed-request.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1111

#1115 PUB-1666 Crown Warned List clean up
  src/main/controllers/CrownWarnedListController.ts
  src/main/resources/locales/bill/crown-warned-list.json
  src/main/resources/locales/cy/crown-warned-list.json
  src/main/resources/locales/en/crown-warned-list.json
  src/main/views/crown-warned-list.njk
  src/test/unit/controllers/CrownWarnedListController.test.ts
  src/test/unit/views/crown-warned-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1115

#1114 PUB-2003 Update no results text on search court page
  src/main/controllers/SearchController.ts
  src/main/resources/locales/cy/search.json
  src/main/resources/locales/en/search.json
  src/main/views/search.njk
  src/test/end-to-end/tests/search-court-test.ts
  src/test/unit/controllers/SearchController.test.ts
  src/test/unit/views/search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1114

#1113 PUB-2068 Enforce authorised access to PDF/Excel download files page
  src/main/controllers/ListDownloadFilesController.ts
  src/main/resources/locales/cy/unauthorised-access.json
  src/main/resources/locales/en/unauthorised-access.json
  src/main/resources/requests/accountManagementRequests.ts
  src/main/service/listDownloadService.ts
  src/main/views/unauthorised-access.njk
  src/test/routes/list-download-files.test.ts
  src/test/unit/controllers/ListDownloadFilesController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/listDownloadService.test.ts
  src/test/unit/views/list-download-files.test.ts
  src/test/unit/views/unauthorised-access.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1113

#1118 PUB-1672 Magistrates Standard List clean up
  src/main/controllers/CrownDailyListController.ts
  src/main/controllers/CrownWarnedListController.ts
  src/main/controllers/MagistratesPublicListController.ts
  src/main/controllers/MagistratesStandardListController.ts
  src/main/resources/locales/bill/magistrates-standard-list.json
  src/main/resources/locales/cy/magistrates-standard-list.json
  src/main/resources/locales/en/magistrates-standard-list.json
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/service/listManipulation/MagistratesStandardListService.ts
  src/main/views/magistrates-standard-list.njk
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/mocks/address.json
  src/test/unit/service/listManipulation/crimeListsService.test.ts
  src/test/unit/service/listManipulation/magsStandardListService.test.ts
  src/test/unit/views/magistrates-standard-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1118

#1119 PUB-2168 Update accessibility statement
  src/main/resources/locales/cy/accessibility-statement.json
  src/main/resources/locales/en/accessibility-statement.json
  src/main/views/accessibility-statement.njk
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1119

#1117 Pub 1667
  src/main/controllers/CrownFirmListController.ts
  src/main/resources/locales/bill/crown-firm-list.json
  src/main/resources/locales/cy/crown-firm-list.json
  src/main/resources/locales/en/crown-firm-list.json
  src/main/views/crown-firm-list.njk
  src/test/unit/controllers/CrownFirmListController.test.ts
  src/test/unit/views/crown-firm-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1117

#1124 Updated get-func-name version
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1124

#1121 PUB-2145 Added dynatrace to content security policy
  src/main/modules/helmet/index.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1121

#1122 Added new functional test for the feature A-Z list of courts and trib…
  src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1122
