Repository hmcts/pip-frontend, pull requests merged in 2024-12, with the labels that each got.

#1390 PUB-2664 Add ServiceNow link to SSO rejected login page
  src/main/resources/locales/cy/sso-rejected-login.json
  src/main/resources/locales/en/sso-rejected-login.json
  src/main/views/sso-rejected-login.njk
  src/test/unit/views/sso-rejected-login.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1390

#1393 PUB-2699 - Updated dependency + tests
  package.json
  src/test/accessibility/accessibility-admin-test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1393

#1386 PUB-2610 Update service navigation items
  src/main/assets/scss/main.scss
  src/main/controllers/AccountHomeController.ts
  src/main/controllers/SubscriptionManagementController.ts
  src/main/controllers/admin/AdminDashboardController.ts
  src/main/controllers/system-admin/SystemAdminDashboardController.ts
  src/main/resources/locales/cy/cft-rejected-login.json
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/cy/media-rejected-login.json
  src/main/resources/locales/cy/sso-rejected-login.json
  src/main/resources/locales/cy/template.json
  src/main/resources/locales/en/cft-rejected-login.json
  src/main/resources/locales/en/home.json
  src/main/resources/locales/en/media-rejected-login.json
  src/main/resources/locales/en/sso-rejected-login.json
  src/main/resources/locales/en/template.json
  src/main/views/admin-rejected-login.njk
  src/main/views/cancelled-password-reset.njk
  src/main/views/cft-rejected-login.njk
  src/main/views/home.njk
  src/main/views/macros/common-components.njk
  src/main/views/media-rejected-login.njk
  src/main/views/password-change-confirmation.njk
  src/main/views/sso-rejected-login.njk
  src/main/views/template.njk
  src/test/end-to-end/tests/admin/remove-list-test.ts
  src/test/end-to-end/tests/banner-navigation-test.ts
  src/test/end-to-end/tests/single-justice-procedure-test.ts
  src/test/end-to-end/tests/sjp-cases-filter-and-paging-test.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
  src/test/end-to-end/tests/system-admin/bulk-create-media-accounts-test.ts
  src/test/end-to-end/tests/system-admin/manage-third-party-users-test.ts
  src/test/end-to-end/tests/system-admin/user-management-test.ts
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
  src/test/end-to-end/tests/verified/single-justice-procedure-cases-test.ts
  src/test/unit/assets/banner.tests.ts
  src/test/unit/controllers/AccountHomeController.test.ts
  src/test/unit/controllers/SubscriptionManagementController.test.ts
  src/test/unit/controllers/admin/AdminDashboardController.test.ts
  src/test/unit/controllers/system-admin/SystemAdminDashboardController.test.ts
  src/test/unit/views/admin/admin-dashboard.test.ts
  src/test/unit/views/admin/manual-upload.test.ts
  src/test/unit/views/admin/media-account-approval.test.ts
  src/test/unit/views/admin/media-account-rejection-reasons.test.ts
  src/test/unit/views/admin/media-account-review.test.ts
  src/test/unit/views/bulk-unsubscribe.test.ts
  src/test/unit/views/create-media-account.test.ts
  src/test/unit/views/home.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
  src/test/unit/views/subscription-management.test.ts
  src/test/unit/views/system-admin/bulk-create-media-accounts.test.ts
  src/test/unit/views/system-admin/reference-data-upload.test.ts
  src/test/unit/views/system-admin/system-admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1386

#1385 PUB-1909 Modify System Audit Logs
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/main/assets/scss/main.scss
  src/main/controllers/system-admin/AuditLogViewerController.ts
  src/main/models/AuditLogSearchCriteria.ts
  src/main/resources/auditActions.json
  src/main/resources/locales/cy/audit-log-viewer.json
  src/main/resources/locales/en/audit-log-viewer.json
  src/main/routes/routes.ts
  src/main/service/AuditLogService.ts
  src/main/views/system-admin/audit-log-viewer.njk
  src/test/a11y/common/mocks/auditLogPageData.json
  src/test/a11y/tests/system-admin-routes.test.ts
  src/test/config.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
  src/test/routes/system-admin/audit-log-viewer.test.ts
  src/test/unit/controllers/system-admin/AuditLogViewerController.test.ts
  src/test/unit/service/AuditLogService.test.ts
  src/test/unit/views/system-admin/audit-log-viewer.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1385

#1392 PUB-2681 - Update System Admin part 2
  src/main/controllers/system-admin/DeleteCourtReferenceDataConfirmationController.ts
  src/main/controllers/system-admin/DeleteCourtSubscriptionConfirmationController.ts
  src/main/resources/requests/LocationRequests.ts
  src/main/resources/requests/PublicationRequests.ts
  src/main/resources/requests/SubscriptionRequests.ts
  src/main/service/LocationService.ts
  src/main/service/PublicationService.ts
  src/main/service/SubscriptionService.ts
  src/test/unit/controllers/system-admin/DeleteCourtReferenceDataConfirmationController.test.ts
  src/test/unit/controllers/system-admin/DeleteCourtSubscriptionConfirmationController.test.ts
  src/test/unit/requests/locationRequests.test.ts
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/LocationService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/SubscriptionService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1392

#1397 PUB-2698 - Updated language
  src/main/modules/i18next/index.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1397
