Repository hmcts/pip-frontend, pull requests merged in 2024-05, with the labels that each got.

#1265 PUB-2165 - Modified single-justice-procedure-press.njk
  src/main/views/style-guide/single-justice-procedure-press.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1265

#1266 PUB-2440 Removed party name search option
  src/main/controllers/PartyNameSearchController.ts
  src/main/controllers/PartyNameSearchResultsController.ts
  src/main/controllers/SubscriptionAddController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/cy/party-name-search-results.json
  src/main/resources/locales/cy/party-name-search.json
  src/main/resources/locales/cy/subscription-add.json
  src/main/resources/locales/en/party-name-search-results.json
  src/main/resources/locales/en/party-name-search.json
  src/main/resources/locales/en/subscription-add.json
  src/main/routes/routes.ts
  src/main/service/PublicationService.ts
  src/main/views/party-name-search-results.njk
  src/main/views/party-name-search.njk
  src/main/views/subscription-add.njk
  src/test/a11y/tests/media-routes.test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/routes/party-name-search-results.test.ts
  src/test/routes/party-name-search.test.ts
  src/test/unit/controllers/PartyNameSearchController.test.ts
  src/test/unit/controllers/PartyNameSearchResultsController.test.ts
  src/test/unit/controllers/SubscriptionAddController.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/views/party-name-search-results.test.ts
  src/test/unit/views/party-name-search.test.ts
  src/test/unit/views/subscription-add.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1266

#1271 Pub 2455
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1271

#1267 PUB-2196: Adding logic to deal with organisationDetails and updating tests
  src/main/service/ListParseHelperService.ts
  src/test/unit/mocks/etDailyList.json
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/mocks/familyDailyCauseListPartyMapping.json
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/service/ListParseHelperService.test.ts
  src/test/unit/service/listManipulation/EtListsService.test.ts
  src/test/unit/service/listManipulation/IacDailyListService.test.ts
  src/test/unit/views/style-guide/et-daily-list.test.ts
  src/test/unit/views/style-guide/et-fortnightly-list.test.ts
  src/test/unit/views/style-guide/iac-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1267

#1277 PUB-2465 Fixed issue when accessing a publication not exists or inaccessible
  src/main/controllers/BlobViewJsonController.ts
  src/main/controllers/FlatFileController.ts
  src/main/controllers/style-guide/CopDailyCauseListController.ts
  src/main/controllers/style-guide/CrownDailyListController.ts
  src/main/controllers/style-guide/CrownFirmListController.ts
  src/main/controllers/style-guide/CrownWarnedListController.ts
  src/main/controllers/style-guide/DailyCauseListController.ts
  src/main/controllers/style-guide/EtDailyListController.ts
  src/main/controllers/style-guide/EtFortnightlyListController.ts
  src/main/controllers/style-guide/IacDailyListController.ts
  src/main/controllers/style-guide/MagistratesPublicListController.ts
  src/main/controllers/style-guide/MagistratesStandardListController.ts
  src/main/controllers/style-guide/OpaPressListController.ts
  src/main/controllers/style-guide/OpaPublicListController.ts
  src/main/controllers/style-guide/OpaResultsController.ts
  src/main/controllers/style-guide/SjpPressListController.ts
  src/main/controllers/style-guide/SjpPublicListController.ts
  src/main/controllers/style-guide/SscsDailyListController.ts
  src/main/controllers/style-guide/TribunalNationalListsController.ts
  src/main/helpers/listHelper.ts
  src/test/helpers/listHelper.test.ts
  src/test/unit/helpers/aToZHelper.test.ts
  src/test/unit/helpers/listHelper.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1277

#1274 PUB-2459 Handle SJP Press List without offence wording
  src/main/service/listManipulation/SjpPressListService.ts
  src/main/views/style-guide/single-justice-procedure-press.njk
  src/test/unit/mocks/sjp-press-list.json
  src/test/unit/service/listManipulation/SjpPressListService.test.ts
  src/test/unit/views/style-guide/single-justice-procedure-press.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1274

#1272 PUB-2352 Create third party user on system admin dashboard
  src/main/controllers/CreateThirdPartyUserController.ts
  src/main/controllers/CreateThirdPartyUserSuccessController.ts
  src/main/controllers/CreateThirdPartyUserSummaryController.ts
  src/main/resources/locales/cy/create-third-party-user-success.json
  src/main/resources/locales/cy/create-third-party-user-summary.json
  src/main/resources/locales/cy/create-third-party-user.json
  src/main/resources/locales/cy/manage-third-party-users-subscriptions-confirm.json
  src/main/resources/locales/cy/manage-third-party-users.json
  src/main/resources/locales/en/create-third-party-user-success.json
  src/main/resources/locales/en/create-third-party-user-summary.json
  src/main/resources/locales/en/create-third-party-user.json
  src/main/resources/locales/en/manage-third-party-users-subscriptions-confirm.json
  src/main/resources/locales/en/manage-third-party-users.json
  src/main/resources/requests/AccountManagementRequests.ts
  src/main/resources/thirdPartyRoles.json
  src/main/routes/routes.ts
  src/main/service/CreateAccountService.ts
  src/main/service/ThirdPartyService.ts
  src/main/views/create-third-party-user-success.njk
  src/main/views/create-third-party-user-summary.njk
  src/main/views/create-third-party-user.njk
  src/main/views/manage-third-party-users.njk
  src/test/a11y/tests/system-admin-routes.test.ts
  src/test/end-to-end/tests/system-admin/manage-third-party-users-test.ts
  src/test/routes/create-third-party-user-success.test.ts
  src/test/routes/create-third-party-user-summary.test.ts
  src/test/routes/create-third-party-user.test.ts
  src/test/unit/controllers/CreateThirdPartyUserController.test.ts
  src/test/unit/controllers/CreateThirdPartyUserSuccessController.test.ts
  src/test/unit/controllers/CreateThirdPartyUserSummaryController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/service/ThirdPartyService.test.ts
  src/test/unit/views/create-third-party-user-success.test.ts
  src/test/unit/views/create-third-party-user-summary.test.ts
  src/test/unit/views/create-third-party-user.test.ts
  src/test/unit/views/manage-third-party-users-subscriptions-confirm.test.ts
  src/test/unit/views/manage-third-party-users.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1272

#1273 PUB-1661 Delete third party user and subscription
  src/main/controllers/DeleteThirdPartyUserConfirmationController.ts
  src/main/controllers/DeleteThirdPartyUserSuccessController.ts
  src/main/resources/locales/cy/delete-third-party-user-confirmation.json
  src/main/resources/locales/cy/delete-third-party-user-success.json
  src/main/resources/locales/cy/manage-third-party-users-subscriptions.json
  src/main/resources/locales/cy/manage-third-party-users-view.json
  src/main/resources/locales/cy/manage-third-party-users.json
  src/main/resources/locales/cy/system-admin-dashboard.json
  src/main/resources/locales/en/delete-third-party-user-confirmation.json
  src/main/resources/locales/en/delete-third-party-user-success.json
  src/main/resources/locales/en/manage-third-party-users-subscriptions.json
  src/main/resources/locales/en/manage-third-party-users-view.json
  src/main/resources/locales/en/manage-third-party-users.json
  src/main/resources/locales/en/system-admin-dashboard.json
  src/main/routes/routes.ts
  src/main/views/delete-third-party-user-confirmation.njk
  src/main/views/delete-third-party-user-success.njk
  src/main/views/manage-third-party-users-view.njk
  src/main/views/manage-third-party-users.njk
  src/test/a11y/tests/system-admin-routes.test.ts
  src/test/end-to-end/tests/system-admin/manage-third-party-users-test.ts
  src/test/routes/delete-third-party-user-confirmation.test.ts
  src/test/routes/delete-third-party-user-success.test.ts
  src/test/unit/controllers/DeleteThirdPartyUserConfirmationController.test.ts
  src/test/unit/controllers/DeleteThirdPartyUserSuccessController.test.ts
  src/test/unit/views/delete-third-party-user-confirmation.test.ts
  src/test/unit/views/delete-third-party-user-success.test.ts
  src/test/unit/views/manage-third-party-users-subscriptions.test.ts
  src/test/unit/views/manage-third-party-users-view.test.ts
  src/test/unit/views/manage-third-party-users.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1273

#1276 PUB-2458 Add audit logs for create and delete third party user
  src/main/controllers/CreateThirdPartyUserSummaryController.ts
  src/main/controllers/DeleteThirdPartyUserConfirmationController.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1276

#1282 Pub 2453
  src/main/resources/locales/cy/style-guide/iac-daily-list.json
  src/main/resources/locales/en/style-guide/iac-daily-list.json
  src/main/views/style-guide/iac-daily-list.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1282

#1278 PUB-2468 Add style guide for SJP Delta Public List
  src/main/controllers/style-guide/SjpPressListController.ts
  src/main/controllers/style-guide/SjpPublicListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/style-guide/single-justice-procedure-new-cases.json
  src/main/resources/locales/cy/style-guide/single-justice-procedure.json
  src/main/resources/locales/en/style-guide/single-justice-procedure-new-cases.json
  src/main/resources/locales/en/style-guide/single-justice-procedure.json
  src/main/routes/routes.ts
  src/test/a11y/tests/style-guide/sjp-public-list.test.ts
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
  src/test/end-to-end/tests/verified/sjp-list-download-test.ts
  src/test/routes/style-guide/single-justice-procedure-public.test.ts
  src/test/unit/controllers/ManualUploadSummaryController.test.ts
  src/test/unit/controllers/style-guide/SjpPressListController.test.ts
  src/test/unit/controllers/style-guide/SjpPublicListController.test.ts
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/SubscriptionService.test.ts
  src/test/unit/views/publication.test.ts
  src/test/unit/views/style-guide/single-justice-procedure-public.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1278

#1283 Update SJP e2e tests to use future content date
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
  src/test/end-to-end/tests/admin/remove-list-test.ts
  src/test/end-to-end/tests/single-justice-procedure-test.ts
  src/test/end-to-end/tests/sorting-list-table-test.ts
  src/test/end-to-end/tests/system-admin/blob-explorer-test.ts
  src/test/end-to-end/tests/system-admin/delete-court-test.ts
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/end-to-end/tests/verified/single-justice-procedure-cases-test.ts
  src/test/end-to-end/tests/verified/sjp-list-download-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1283

#1284 PUB-2475 Update allowed postcode format for SJP Public List
  src/test/end-to-end/shared/mocks/sjp-public-list.json
  src/test/unit/mocks/sjp-public-list.json
  src/test/unit/service/listManipulation/SjpPublicListService.test.ts
  src/test/unit/views/style-guide/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip

#1287 PUB-2477 Flag e2e tests as nightly tests
  src/test/end-to-end/tests/admin/create-new-account-test.ts
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
  src/test/end-to-end/tests/admin/user-management-test.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/system-admin/bulk-create-media-accounts-test.ts
  src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
  src/test/end-to-end/tests/system-admin/delete-court-test.ts
  src/test/end-to-end/tests/system-admin/upload-reference-data-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1287
