Repository hmcts/pip-frontend, pull requests merged in 2024-11, with the labels that each got.

#1378 PUB-2647 - SSO Rejected Login
  src/main/authentication/authentication.ts
  src/main/controllers/SsoRejectedLoginController.ts
  src/main/helpers/consts.ts
  src/main/resources/locales/cy/sso-rejected-login.json
  src/main/resources/locales/en/sso-rejected-login.json
  src/main/routes/routes.ts
  src/main/views/sso-rejected-login.njk
  src/test/a11y/tests/public-routes.test.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/routes/sso-rejected-login.test.ts
  src/test/unit/authentication/authentication.test.ts
  src/test/unit/controllers/SsoRejectedLoginController.test.ts
  src/test/unit/views/sso-rejected-login.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1378

#1374 Pub 2627 - admin accessibility tests
  package.json
  src/test/accessibility/accessibility-admin-test.ts
  src/test/accessibility/accessibility-public-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1374

#1381 PUB-2364 SSO fix session cookie same site issue
  src/main/authentication/authentication-config.json
  src/main/authentication/authentication.ts
  src/main/authentication/ssoAuthentication.ts
  src/main/routes/routes.ts
  src/test/routes/login.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1381

#1365 PUB-2617 - Fixing session issue
  README.md
  charts/pip-frontend/Chart.yaml
  config/default.json
  jestEnvVars.js
  src/main/app.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1365

#1384 PUB-2561 - Fix AXE findings
  src/main/views/admin/remove-list-search-results.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1384
