Repository hmcts/pip-frontend, pull requests merged in 2024-10, with the labels that each got.

#1332 PUB-2529 - Upgrade to Yarn 4
  .lefthook/pre-push/check-for-unsuppressed-vulns.py
  .yarn/releases/yarn-3.8.3.cjs
  .yarn/releases/yarn-4.4.0.cjs
  .yarnrc.yml
  jest.a11y.config.js
  jest.config.js
  jest.routes.config.js
  jest.smoke.config.js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-frontend-pr-1332

#1347 Pub 2592 axe
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/test/accessibility/accessibility-test.ts
  src/test/accessibility/accessibility.conf.js
  src/test/accessibility/accessibility.conf.ts
  src/test/accessibility/aggregateAccessibilityResults.js
  src/test/accessibility/amendAccessibilityReport.js
  src/test/config.ts
  src/test/end-to-end/tests/custom-steps.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1347

#1362 PUB-2587 Update test files to conform to date field validation in schema
  src/test/end-to-end/shared/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/crownWarnedList.json
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/familyDailyCauseListPartyMapping.json
  src/test/unit/mocks/familyDailyCauseListWithReorderedPartyMappings.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1362

#1359 PUB-2233 Removed parties at hearing level
  src/main/controllers/style-guide/DailyCauseListController.ts
  src/main/helpers/listHelper.ts
  src/main/service/listManipulation/CivilFamilyAndMixedListService.ts
  src/main/service/listManipulation/SscsDailyListService.ts
  src/main/views/style-guide/civil-and-family-daily-cause-list.njk
  src/main/views/style-guide/family-daily-cause-list.njk
  src/main/views/style-guide/sscs-daily-list.njk
  src/test/unit/controllers/style-guide/DailyCauseListController.test.ts
  src/test/unit/controllers/style-guide/hearingparty/DailyCauseListController.test.ts
  src/test/unit/controllers/style-guide/hearingparty/SscsDailyListController.test.ts
  src/test/unit/helpers/listHelper.test.ts
  src/test/unit/mocks/hearingparty/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/hearingparty/familyDailyCauseList.json
  src/test/unit/mocks/hearingparty/familyDailyCauseListPartyMapping.json
  src/test/unit/mocks/hearingparty/familyDailyCauseListWithReorderedPartyMappings.json
  src/test/unit/mocks/hearingparty/sscsDailyList.json
  src/test/unit/service/listManipulation/hearingparty/CivilFamilyAndMixedListService.test.ts
  src/test/unit/service/listManipulation/hearingparty/SscsListService.test.ts
  src/test/unit/views/style-guide/hearingparty/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/style-guide/hearingparty/family-daily-cause-list.test.ts
  src/test/unit/views/style-guide/hearingparty/sscs-daily-list-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1359

#1364 PUB-2616 Update pages with A-Z
  src/main/resources/locales/cy/alphabetical-search.json
  src/main/resources/locales/cy/location-name-search.json
  src/main/resources/locales/cy/subscription-configure-list.json
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/location-name-search.json
  src/main/resources/locales/en/subscription-configure-list.json
  src/main/views/alphabetical-search.njk
  src/main/views/location-name-search.njk
  src/main/views/subscription-configure-list.njk
  src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/location-name-search.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1364

#1361 PUB-2603 Fix SJP filter panel overlapping with main panel
  src/main/assets/scss/main.scss
  src/main/views/macros/sjp-common.njk
  src/main/views/style-guide/single-justice-procedure-press.njk
  src/main/views/style-guide/single-justice-procedure.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1361

#1369 PUB-2595 - Updated hearing type
  src/main/resources/locales/en/magistrates-standard-list.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1369

#1373 Fix E2E Tests Admin
  src/test/end-to-end/tests/system-admin/user-management-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1373

#1366 PUB-2600 Fix Back To Top Accessibility issue
  src/main/assets/scss/main.scss
  src/main/views/admin/admin-dashboard.njk
  src/main/views/alphabetical-search.njk
  src/main/views/home.njk
  src/main/views/location-name-search.njk
  src/main/views/style-guide/single-justice-procedure-press.njk
  src/main/views/style-guide/single-justice-procedure.njk
  src/main/views/summary-of-publications.njk
  src/main/views/system-admin/system-admin-dashboard.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1366

#1292 PUB-2485 Remove WAF custom rule redirection route
  src/main/controllers/UnprocessedRequestController.ts
  src/main/resources/locales/cy/unprocessed-request.json
  src/main/resources/locales/en/unprocessed-request.json
  src/main/routes/routes.ts
  src/main/views/unprocessed-request.njk
  src/test/a11y/tests/public-routes.test.ts
  src/test/routes/unprocessed-request.test.ts
  src/test/unit/controllers/unprocessedRequestController.test.ts
  src/test/unit/views/unprocessed-request.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1292
