Repository hmcts/pip-frontend, pull requests merged in 2024-07, with the labels that each got.

#1301 PUB-2508 - Fix SJP Filters issue
  src/main/controllers/style-guide/SjpPressListController.ts
  src/main/controllers/style-guide/SjpPublicListController.ts
  src/main/service/FilterService.ts
  src/main/views/macros/sjp-common.njk
  src/test/unit/controllers/style-guide/SjpPressListController.test.ts
  src/test/unit/controllers/style-guide/SjpPublicListController.test.ts
  src/test/unit/service/FilterService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1301

#1279 PUB-2302 - Added a11y tests to test suites
  src/test/a11y/tests/admin-routes.test.ts
  src/test/a11y/tests/media-routes.test.ts
  src/test/a11y/tests/public-routes.test.ts
  src/test/a11y/tests/system-admin-routes.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1279

#1304 PUB-2500: Removing party from hearing level and updating style guides…
  src/main/controllers/style-guide/CrownDailyListController.ts
  src/main/controllers/style-guide/CrownFirmListController.ts
  src/main/controllers/style-guide/CrownWarnedListController.ts
  src/main/controllers/style-guide/MagistratesPublicListController.ts
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/service/listManipulation/CrownFirmListService.ts
  src/main/service/listManipulation/CrownWarnedListService.ts
  src/main/views/style-guide/crown-daily-list.njk
  src/main/views/style-guide/magistrates-public-list.njk
  src/test/unit/controllers/style-guide/CrownDailyListController.test.ts
  src/test/unit/controllers/style-guide/MagistratesPublicListController.test.ts
  src/test/unit/controllers/style-guide/hearingparty/CrownDailyListController.test.ts
  src/test/unit/controllers/style-guide/hearingparty/CrownFirmListController.test.ts
  src/test/unit/controllers/style-guide/hearingparty/CrownWarnedListController.test.ts
  src/test/unit/controllers/style-guide/hearingparty/MagistratesPublicListController.test.ts
  src/test/unit/helpers/listHelper.test.ts
  src/test/unit/mocks/hearingparty/crimeListParty.json
  src/test/unit/mocks/hearingparty/crownDailyList.json
  src/test/unit/mocks/hearingparty/crownFirmList.json
  src/test/unit/mocks/hearingparty/crownFirmSemiDigested.json
  src/test/unit/mocks/hearingparty/crownWarnedList.json
  src/test/unit/mocks/hearingparty/magistratesPublicList.json
  src/test/unit/service/listManipulation/hearingparty/CrimeListsService.test.ts
  src/test/unit/service/listManipulation/hearingparty/CrownFirmListService.test.ts
  src/test/unit/service/listManipulation/hearingparty/CrownWarnedListService.test.ts
  src/test/unit/views/style-guide/hearingparty/crown-daily-list.test.ts
  src/test/unit/views/style-guide/hearingparty/crown-firm-list.test.ts
  src/test/unit/views/style-guide/hearingparty/crown-warned-list.test.ts
  src/test/unit/views/style-guide/hearingparty/magistrates-public-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1304

#1307 PUB-2516: Adding FaCT link to start page
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/main/views/home.njk
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1307

#1306 PUB-2507 - Amended text and tests
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1306

#1309 PUB-1825 - Removed inappropriate entries in our tests
  src/test/unit/mocks/crownFirmList.json
  src/test/unit/mocks/crownFirmSemiDigested.json
  src/test/unit/service/listManipulation/CrownFirmListService.test.ts
  src/test/unit/views/style-guide/crown-firm-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1309

#1303 PUB-2487 - Added pagination to the SJP Lists
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  src/main/assets/scss/main.scss
  src/main/controllers/style-guide/SjpPressListController.ts
  src/main/controllers/style-guide/SjpPublicListController.ts
  src/main/models/style-guide/sjp-model.ts
  src/main/service/SjpFilterService.ts
  src/main/service/listManipulation/SjpPressListService.ts
  src/main/service/listManipulation/SjpPublicListService.ts
  src/main/views/macros/sjp-common.njk
  src/main/views/sjp-template.njk
  src/main/views/style-guide/single-justice-procedure-press.njk
  src/main/views/style-guide/single-justice-procedure.njk
  src/test/a11y/tests/style-guide/sjp-press-list.test.ts
  src/test/a11y/tests/style-guide/sjp-public-list.test.ts
  src/test/end-to-end/shared/mocks/sjp-paging-and-filter.json
  src/test/end-to-end/tests/sjp-cases-filter-and-paging-test.ts
  src/test/end-to-end/tests/verified/sjp-list-download-test.ts
  src/test/routes/style-guide/single-justice-procedure-press.test.ts
  src/test/routes/style-guide/single-justice-procedure-public.test.ts
  src/test/unit/controllers/style-guide/SjpPressListController.test.ts
  src/test/unit/controllers/style-guide/SjpPublicListController.test.ts
  src/test/unit/mocks/sjp/extendedSjpPressList.json
  src/test/unit/mocks/sjp/minimalSjpPressList.json
  src/test/unit/mocks/sjp/minimalSjpPublicList.json
  src/test/unit/models/SjpModel.test.ts
  src/test/unit/service/SjpFilterService.test.ts
  src/test/unit/service/listManipulation/SjpPressListService.test.ts
  src/test/unit/service/listManipulation/SjpPublicListService.test.ts
  src/test/unit/views/home.test.ts
  src/test/unit/views/style-guide/single-justice-procedure-press.test.ts
  src/test/unit/views/style-guide/single-justice-procedure-public.test.ts
  src/test/unit/views/system-admin/blob-view-json.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1303

#1308 PUB-2520 Use SJP delta URL when applying filters
  src/main/controllers/style-guide/SjpPressListController.ts
  src/main/controllers/style-guide/SjpPublicListController.ts
  src/main/helpers/listHelper.ts
  src/main/views/style-guide/single-justice-procedure-press.njk
  src/main/views/style-guide/single-justice-procedure.njk
  src/test/routes/style-guide/single-justice-procedure-press.test.ts
  src/test/routes/style-guide/single-justice-procedure-public.test.ts
  src/test/unit/controllers/style-guide/SjpPressListController.test.ts
  src/test/unit/controllers/style-guide/SjpPublicListController.test.ts
  src/test/unit/helpers/listHelper.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1308

#1314 Fixed dependency version
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1314
