Repository hmcts/pip-frontend, pull requests merged in 2024-02, with the labels that each got.

#1194 Pub 2089 - Align JOH functionality
  src/main/service/listManipulation/IacDailyListService.ts
  src/main/service/listManipulation/MagistratesStandardListService.ts
  src/main/service/listManipulation/SscsDailyListService.ts
  src/main/service/listParseHelperService.ts
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/copDailyCauseList.json
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/crownFirmList.json
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/mocks/magistratesPublicList.json
  src/test/unit/mocks/magistratesStandardList.json
  src/test/unit/mocks/sscsDailyList.json
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/service/listManipulation/civilFamilyAndMixedListService.test.ts
  src/test/unit/service/listManipulation/iacDailyListService.test.ts
  src/test/unit/service/listManipulation/magistratesStandardListService.test.ts
  src/test/unit/service/listManipulation/sscsListService.test.ts
  src/test/unit/service/listParseHelperService.test.ts
  src/test/unit/views/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/cop-daily-cause-list.test.ts
  src/test/unit/views/crown-daily-list.test.ts
  src/test/unit/views/crown-firm-list.test.ts
  src/test/unit/views/daily-cause-list.test.ts
  src/test/unit/views/family-daily-cause-list.test.ts
  src/test/unit/views/iac-daily-list.test.ts
  src/test/unit/views/magistrates-public-list.test.ts
  src/test/unit/views/magistrates-standard-list.test.ts
  src/test/unit/views/sscs-daily-list-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1194

#1201 Updating GLlTEM to GLlTEF
  src/main/resources/locales/cy/accessibility-statement.json
  src/main/resources/locales/cy/account-request-submitted.json
  src/main/resources/locales/cy/cookie-policy.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1201

#1203 Update vulnerability suppressions
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1203

#1198 PUB-1619 - Added fortify
  Jenkinsfile_nightly
  README.md
  package.json
  src/main/authentication/authenticationHandler.ts
  src/main/controllers/BulkCreateMediaAccountsController.ts
  src/main/controllers/CreateAdminAccountController.ts
  src/main/controllers/CreateAdminAccountSummaryController.ts
  src/main/controllers/CreateSystemAdminAccountController.ts
  src/main/controllers/CreateSystemAdminAccountSummaryController.ts
  src/main/controllers/ManualReferenceDataUploadController.ts
  src/main/controllers/ManualUploadController.ts
  src/main/server.ts
  src/main/service/sessionManagementService.ts
  src/test/fortify/java/.gitignore
  src/test/fortify/java/build.gradle
  src/test/fortify/java/config/fortify-client.properties
  src/test/fortify/java/gradle/wrapper/gradle-wrapper.jar
  src/test/fortify/java/gradle/wrapper/gradle-wrapper.properties
  src/test/fortify/java/gradlew
  src/test/fortify/java/gradlew.bat
  src/test/fortify/java/settings.gradle
  src/test/unit/authentication/authenticationHandler.test.ts
  src/test/unit/service/sessionManagementService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1198

#1206 PUB-1619 - Updated fortify
  package.json
  src/test/fortify/.gitignore
  src/test/fortify/build.gradle
  src/test/fortify/config/fortify-client.properties
  src/test/fortify/gradle/wrapper/gradle-wrapper.jar
  src/test/fortify/gradle/wrapper/gradle-wrapper.properties
  src/test/fortify/gradlew
  src/test/fortify/gradlew.bat
  src/test/fortify/settings.gradle
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1206

#1199 PUB-2293 - Dependency Updates
  .stylelintrc.json
  .yarn/releases/yarn-3.6.4.cjs
  charts/pip-frontend/Chart.yaml
  package.json
  src/main/controllers/BlobViewJsonController.ts
  src/test/end-to-end/tests/admin/manage-media-account-request-test.ts
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
  src/test/end-to-end/tests/custom-steps.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1199

#1180 PUB-2118 - Updated lax cookie
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.stg.template.yaml
  charts/pip-frontend/values.yaml
  package.json
  src/main/app.ts
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-frontend-pr-1180

#1202 PUB-2035 Implement consistent sorting on subscription pages
  src/main/controllers/CaseNameSearchResultsController.ts
  src/main/controllers/PartyNameSearchResultsController.ts
  src/main/controllers/PendingSubscriptionsController.ts
  src/main/helpers/sortHelper.ts
  src/main/resources/requests/utils/pendingSubscriptionsFromCache.ts
  src/main/service/subscriptionService.ts
  src/test/unit/controllers/CaseNameSearchResultsController.test.ts
  src/test/unit/controllers/PartyNameSearchResultsController.test.ts
  src/test/unit/controllers/PendingSubscriptionsController.test.ts
  src/test/unit/helpers/sortHelper.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/case-name-search-results.test.ts
  src/test/unit/views/pending-subscriptions.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1202

#1207 PUB-2317 - Updated to new crown logo
  src/main/views/template.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1207

#1210 Updated suppressions and codecept js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1210

#1197 PUB-2291- Updated OPA Public and Press Lists
  src/main/service/listManipulation/OpaPressListService.ts
  src/main/service/listManipulation/OpaPublicListService.ts
  src/test/unit/mocks/opaPressList.json
  src/test/unit/mocks/opaPublicList.json
  src/test/unit/service/listManipulation/opaPublicListService.test.ts
  src/test/unit/views/opa-public-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1197

#1215 PUB-2262: Removing Individual Middle Name attribute from iac Daily List
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/service/listManipulation/iacDailyListService.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1215

#1209 PUB-2277: Removing "youth" attribute from opaPressList.json
  src/test/unit/mocks/opaPressList.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1209

#1213 PUB-2338 - Fixed cache issue
  src/main/resources/requests/utils/axiosConfig.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1213

#1212 PUB-2297 - Removed unneeded variable
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1212

#1216 PUB-2339 - SSCS Party Role Respondent
  src/main/service/listManipulation/SscsDailyListService.ts
  src/test/unit/mocks/sscsDailyList.json
  src/test/unit/service/listManipulation/sscsListService.test.ts
  src/test/unit/views/sscs-daily-list-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1216
