Repository hmcts/pip-frontend, pull requests merged in 2024-09, with the labels that each got.

#1333 PUB-2554 Update region for ET lists' style guide
  src/main/controllers/style-guide/EtDailyListController.ts
  src/main/controllers/style-guide/EtFortnightlyListController.ts
  src/main/models/Location.ts
  src/test/unit/controllers/style-guide/EtDailyListController.test.ts
  src/test/unit/controllers/style-guide/EtFortnightlyListController.test.ts
  src/test/unit/mocks/courtAndHearings.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1333

#1341 PUB-2597 - Removed wording from Search page
  src/main/resources/locales/cy/search.json
  src/main/resources/locales/en/search.json
  src/main/views/search.njk
  src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
  src/test/unit/views/search.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1341

#1329 PUB-2226 - Remove Safe keyword from nunjucks files and filters
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/style-guide/care-standards-list.njk
  src/main/views/style-guide/civil-and-family-daily-cause-list.njk
  src/main/views/style-guide/cop-daily-cause-list.njk
  src/main/views/style-guide/daily-cause-list.njk
  src/main/views/style-guide/family-daily-cause-list.njk
  src/main/views/style-guide/sscs-daily-list.njk
  src/test/unit/modules/nunjucks/njkFilters.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1329

#1346 Update versions of express / webpack
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1346

#1349 fix dependency issue
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1349

#1330 PUB-2340-b
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1330

#1351 PUB-2340 - Revert back changes
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  src/main/app.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-frontend-pr-1351

#1353 Fix for fortify
  eslint.config.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1353
