Repository hmcts/pip-frontend, pull requests merged in 2024-01, with the labels that each got.

#1184 PUB-2245 - Updated README
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.yaml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1184

#1186 PUB-1911 Remove a11y and routes github actions
  .github/workflows/a11y.yml
  .github/workflows/routes.yml
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1186

#1181 PUB-2240 Update Magistrates standard list style guide for party and offence
  src/main/controllers/MagistratesStandardListController.ts
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/service/listManipulation/MagistratesStandardListService.ts
  src/main/views/magistrates-standard-list.njk
  src/main/views/opa-press-list.njk
  src/test/routes/magistrates-standard-list.test.ts
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/mocks/magistratesStandardList.json
  src/test/unit/mocks/magsStandardList.json
  src/test/unit/service/listManipulation/magistratesStandardListService.test.ts
  src/test/unit/service/listManipulation/magsStandardListService.test.ts
  src/test/unit/views/magistrates-standard-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1181

#1189 Merge code freeze branch to Master
  .github/workflows/a11y.yml
  .github/workflows/routes.yml
  src/main/controllers/MagistratesStandardListController.ts
  src/main/resources/locales/cy/create-media-account.json
  src/main/resources/locales/cy/media-rejected-login.json
  src/main/resources/locales/cy/sign-in.json
  src/main/resources/locales/en/create-media-account.json
  src/main/service/listManipulation/CrimeListsService.ts
  src/main/service/listManipulation/MagistratesStandardListService.ts
  src/main/views/magistrates-standard-list.njk
  src/main/views/opa-press-list.njk
  src/main/views/template.njk
  src/test/routes/magistrates-standard-list.test.ts
  src/test/unit/controllers/MagistratesStandardListController.test.ts
  src/test/unit/mocks/magistratesStandardList.json
  src/test/unit/mocks/magsStandardList.json
  src/test/unit/service/listManipulation/magistratesStandardListService.test.ts
  src/test/unit/service/listManipulation/magsStandardListService.test.ts
  src/test/unit/views/create-media-account.test.ts
  src/test/unit/views/magistrates-standard-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1189

#1185 PUB-2279 - Fixed code smells
  sonar-project.properties
  src/main/authentication/authenticationHandler.ts
  src/main/authentication/cftIdamAuthentication.ts
  src/main/controllers/AdminManagementController.ts
  src/main/controllers/BlobViewPublicationsController.ts
  src/main/controllers/BulkUnsubscribeController.ts
  src/main/controllers/CaseNameSearchResultsController.ts
  src/main/controllers/DeleteCourtReferenceDataConfirmationController.ts
  src/main/controllers/ListDownloadDisclaimerController.ts
  src/main/controllers/ListDownloadFilesController.ts
  src/main/controllers/ManageUserController.ts
  src/main/controllers/PartyNameSearchResultsController.ts
  src/main/controllers/SessionExpiredController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/resources/requests/utils/pendingSubscriptionsFromCache.ts
  src/main/service/createAccountService.ts
  src/main/service/filterService.ts
  src/main/service/listManipulation/OpaPressListService.ts
  src/main/service/locationService.ts
  src/main/service/publicationService.ts
  src/main/service/sjpFilterService.ts
  src/main/service/subscriptionService.ts
  src/main/service/thirdPartyService.ts
  src/test/unit/authentication/cftIdamAuthentication.test.ts
  src/test/unit/controllers/BulkUnsubscribeController.test.ts
  src/test/unit/controllers/SubscriptionManagementController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1185

#1191 Updated follow redirects
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1191

#1172 Pub 1977b - Add OPA Public List
  src/main/controllers/OpaPublicListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/bill/opa-public-list.json
  src/main/resources/locales/cy/opa-public-list.json
  src/main/resources/locales/en/opa-public-list.json
  src/main/routes/routes.ts
  src/main/service/listManipulation/OpaPressListService.ts
  src/main/service/listManipulation/OpaPublicListService.ts
  src/main/views/opa-public-list.njk
  src/test/routes/opa-public-list.test.ts
  src/test/unit/controllers/OpaPublicListController.test.ts
  src/test/unit/mocks/opaPublicList.json
  src/test/unit/mocks/returnedArtefacts.json
  src/test/unit/service/listManipulation/opaPublicListService.test.ts
  src/test/unit/service/manualUploadService.test.ts
  src/test/unit/service/publicationService.test.ts
  src/test/unit/views/opa-public-list.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1172

#1190 PUB-2093 Mags Public List clean up
  src/test/unit/mocks/magistratesPublicList.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1190

#1195 PUB-1882 - Fix resolution issues
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1195
