Repository hmcts/pip-frontend, pull requests merged in 2024-04, with the labels that each got.

#1238 PUB-2008 - Sort filtered autocomplete results
  src/main/views/search.njk
  src/test/end-to-end/tests/search-court-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1238

#1239 PUB-2355 - Improve SJP performance
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/main/views/sjp-template.njk
  src/test/end-to-end/tests/verified/sjp-list-download-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1239

#1248 PUB-2356 - Updated playwright dependency
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1248

#1247 PUB-2360 - Reorder radio buttons
  src/main/resources/locales/cy/subscription-add.json
  src/main/resources/locales/en/subscription-add.json
  src/main/views/subscription-add.njk
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/unit/views/subscription-add.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1247

#1243 PUB-2368 Fixed sorting of Crown Daily List table content
  src/main/views/crown-daily-list.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1243

#1249 PUB-2211 Removed old LCSU code
  src/main/controllers/CaseEventGlossaryController.ts
  src/main/controllers/LiveCaseCourtSearchController.ts
  src/main/controllers/LiveCaseStatusController.ts
  src/main/controllers/ViewOptionController.ts
  src/main/models/request/PipRequest.ts
  src/main/resources/locales/en/case-event-glossary.json
  src/main/resources/locales/en/live-case-alphabet-search.json
  src/main/resources/locales/en/live-case-status.json
  src/main/resources/locales/en/session-management.json
  src/main/resources/requests/caseEventGlossaryRequests.ts
  src/main/resources/requests/liveCaseRequests.ts
  src/main/routes/routes.ts
  src/main/service/caseEventGlossaryService.ts
  src/main/service/liveCaseService.ts
  src/main/service/locationService.ts
  src/main/views/case-event-glossary.njk
  src/main/views/live-case-alphabet-search.njk
  src/main/views/live-case-status.njk
  src/main/views/session-management.njk
  src/test/routes/case-event-glossary.ts
  src/test/routes/live-case-alphabet-search.test.ts
  src/test/routes/live-case-status.test.ts
  src/test/routes/view-option.test.ts
  src/test/unit/controllers/CaseEventGlossaryController.test.ts
  src/test/unit/controllers/LiveCaseCourtSearchController.test.ts
  src/test/unit/controllers/LiveCaseStatusController.test.ts
  src/test/unit/controllers/ViewOptionController.test.ts
  src/test/unit/mocks/CaseEventGlossary.json
  src/test/unit/mocks/liveCaseStatusUpdates.json
  src/test/unit/requests/caseEventGlossaryRequests.test.ts
  src/test/unit/requests/liveCaseRequests.test.ts
  src/test/unit/service/caseEventGlossaryService.test.ts
  src/test/unit/service/locationService.test.ts
  src/test/unit/views/case-event-glossary.test.ts
  src/test/unit/views/live-case-alphabet-search.test.ts
  src/test/unit/views/live-case-status.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1249

#1253 Update vuln suppression
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1253

#1251 PUB-2357 - Upgraded chai
  jest.a11y.config.js
  jest.config.e2e.js
  jest.config.js
  jest.routes.config.js
  jest.smoke.config.js
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1251

#1250 PUB-2029
  src/main/controllers/AdminDashboardController.ts
  src/main/resources/locales/cy/admin-dashboard.json
  src/main/resources/locales/en/admin-dashboard.json
  src/main/views/admin-dashboard.njk
  src/test/unit/controllers/AdminDashboardController.test.ts
  src/test/unit/views/admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1250

#1244 PUB-2122 Fixed intermittent failure on publication file download
  src/main/controllers/ListDownloadFilesController.ts
  src/main/controllers/MediaAccountReviewController.ts
  src/main/controllers/SjpPressListController.ts
  src/main/controllers/SjpPublicListController.ts
  src/main/models/PublicationFileSizes.ts
  src/main/models/consts.ts
  src/main/resources/requests/channelManagementRequests.ts
  src/main/service/listDownloadService.ts
  src/test/a11y/tests/style-guide/sjp-press-list.test.ts
  src/test/a11y/tests/style-guide/sjp-public-list.test.ts
  src/test/routes/list-download-files.test.ts
  src/test/unit/controllers/ListDownloadFilesController.test.ts
  src/test/unit/controllers/SjpPressListController.test.ts
  src/test/unit/controllers/SjpPublicListController.test.ts
  src/test/unit/requests/channelManagementRequests.test.ts
  src/test/unit/service/listDownloadService.test.ts
  src/test/unit/views/list-download-files.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
  src/test/unit/views/single-justice-procedure-public.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1244

#1257 Cross Browser Test - Admin manual upload sensitivity
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1257

#1254 PUB-2375 - Dependency Updates
  .eslintignore
  .eslintrc.js
  babel.config.json
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  eslint.config.js
  package.json
  src/main/assets/scss/main.scss
  src/main/controllers/AdminDashboardController.ts
  src/main/models/request/PipRequest.ts
  src/main/modules/helmet/index.ts
  src/main/service/listManipulation/crownFirmListService.ts
  src/main/views/bulk-unsubscribe.njk
  src/main/views/case-name-search-results.njk
  src/main/views/location-name-search.njk
  src/main/views/manage-third-party-users-subscriptions.njk
  src/main/views/party-name-search-results.njk
  src/main/views/subscription-configure-list.njk
  src/main/views/template.njk
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
  src/test/unit/views/home.test.ts
  webpack/govukFrontend.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1254

#1258 PUB-2418 Fix HMI publication receipt nightly test
  src/test/end-to-end/tests/hmi-publication-receipt-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1258

#1260 Pub 2304
  src/test/end-to-end/tests/admin/create-new-account-test.ts
  src/test/end-to-end/tests/admin/manage-media-account-request-test.ts
  src/test/end-to-end/tests/admin/manual-upload-sensitivity-test.ts
  src/test/end-to-end/tests/admin/user-management-test.ts
  src/test/end-to-end/tests/banner-navigation-test.ts
  src/test/end-to-end/tests/cft-idam/sjp-list-type-filtering.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
  src/test/end-to-end/tests/system-admin/create-system-admin-test.ts
  src/test/end-to-end/tests/system-admin/delete-court-test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/end-to-end/tests/verified/single-justice-procedure-cases-test.ts
  src/test/end-to-end/tests/verified/sjp-list-download-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1260

#1261 PUB-2377 - Fixed dependency + fortify
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1261

#1262 PUB-2428 SJP Press List DOB and age optional
  src/main/service/listManipulation/SjpPressListService.ts
  src/test/unit/mocks/sjp-press-list.json
  src/test/unit/service/listManipulation/sjpPressListService.test.ts
  src/test/unit/views/single-justice-procedure-press.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1262

#1263 Update SJP list download e2e test
  src/test/end-to-end/tests/verified/sjp-list-download-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1263

#1235 Pub 2186 iac daily cause list updates 5
  src/main/resources/locales/cy/iac-daily-list.json
  src/main/resources/locales/en/iac-daily-list.json
  src/main/service/listManipulation/IacDailyListService.ts
  src/main/views/iac-daily-list.njk
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/service/listManipulation/iacDailyListService.test.ts
  src/test/unit/service/listManipulation/sscsListService.test.ts
  src/test/unit/views/hearingparty/sscs-daily-list-test.ts
  src/test/unit/views/iac-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1235
