Repository hmcts/pip-frontend, pull requests merged in 2024-08, with the labels that each got.

#1312 PUB-2519 Fix SJP filter behaviour
  src/main/views/macros/sjp-common.njk
  src/test/end-to-end/tests/sjp-cases-filter-and-paging-test.ts
  src/test/unit/views/style-guide/single-justice-procedure-press.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1312

#1319 Updated dependency + known issue
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1319

#1321 Updated pipeline
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1321

#1313 PUB-2523 - Error creating audit log when many publications
  src/main/controllers/admin/RemoveListConfirmationController.ts
  src/main/service/RemoveListHelperService.ts
  src/test/unit/controllers/admin/RemoveListConfirmationController.test.ts
  src/test/unit/service/RemoveListHelperService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1313

#1316 PUB-2527 - Display applicant on ET lists
  src/main/service/listManipulation/EtListsService.ts
  src/main/views/style-guide/et-daily-list.njk
  src/main/views/style-guide/et-fortnightly-list.njk
  src/test/end-to-end/shared/mocks/etDailyList.json
  src/test/unit/mocks/etDailyList.json
  src/test/unit/mocks/etFortnightlyList.json
  src/test/unit/service/listManipulation/EtListsService.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1316

#1311 PUB-2359 Removed calls to channel-management
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  frontend-arch.png
  src/main/resources/requests/PublicationFileRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/main/service/ListDownloadService.ts
  src/test/unit/requests/publicationFileRequests.test.ts
  src/test/unit/resources/requests/utils/axiosConfigTest.ts
  src/test/unit/service/ListDownloadService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1311

#1323 Modified test to create random test user accounts with test prefix
  package.json
  src/test/end-to-end/tests/system-admin/bulk-create-media-accounts-test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1323

#1326 PUB-2532 Re-ordering of court search results for admin pages
  src/main/views/admin/manual-upload.njk
  src/main/views/admin/remove-list-search.njk
  src/main/views/macros/common-components.njk
  src/main/views/search.njk
  src/main/views/system-admin/delete-court-reference-data.njk
  src/test/unit/views/admin/remove-list-search.test.ts
  src/test/unit/views/search.test.ts
  src/test/unit/views/system-admin/delete-court-reference-data.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1326

#1320 PUB-2511: Updating dependencies
  Dockerfile
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1320

#1331 PUB-2531 Removed ENABLE_CFT flag from frontend
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.stg.template.yaml
  charts/pip-frontend/values.yaml
  jestEnvVars.js
  src/main/controllers/SignInController.ts
  src/main/routes/routes.ts
  src/main/views/sign-in.njk
  src/test/unit/controllers/SignInController.test.ts
  src/test/unit/views/sign-in.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1331
