Repository hmcts/pip-frontend, pull requests merged in 2024-06, with the labels that each got.

#1293 GHSA-2p57-rm9w-gvfp Suppress security vuln in 'ip' dependency
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1293

#1280 Pub 2361
  src/main/assets/scss/home.scss
  src/main/controllers/RemoveListConfirmationController.ts
  src/main/controllers/RemoveListSearchResultsController.ts
  src/main/controllers/RemoveListSuccessController.ts
  src/main/helpers/listHelper.ts
  src/main/resources/locales/cy/remove-list-confirmation.json
  src/main/resources/locales/cy/remove-list-search-results.json
  src/main/resources/locales/cy/remove-list-success.json
  src/main/resources/locales/en/remove-list-confirmation.json
  src/main/resources/locales/en/remove-list-search-results.json
  src/main/resources/locales/en/remove-list-success.json
  src/main/routes/routes.ts
  src/main/service/RemoveListHelperService.ts
  src/main/views/remove-list-confirmation.njk
  src/main/views/remove-list-search-results.njk
  src/test/end-to-end/tests/admin/remove-list-test.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
  src/test/routes/remove-list-confirmation.test.ts
  src/test/unit/controllers/RemoveListConfirmationController.test.ts
  src/test/unit/controllers/RemoveListSearchResultsController.test.ts
  src/test/unit/controllers/RemoveListSuccessController.test.ts
  src/test/unit/helpers/listHelper.test.ts
  src/test/unit/service/RemoveListHelperService.test.ts
  src/test/unit/views/remove-list-confirmation.test.ts
  src/test/unit/views/remove-list-search-results.test.ts
  src/test/unit/views/remove-list-success.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1280

#1286 PUB-2454 - Added Style Guides for both English and Welsh
  src/main/controllers/style-guide/IacDailyListController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/style-guide/iac-daily-list-additional-cases.json
  src/main/resources/locales/cy/style-guide/iac-daily-list.json
  src/main/resources/locales/en/style-guide/iac-daily-list-additional-cases.json
  src/main/resources/locales/en/style-guide/iac-daily-list.json
  src/main/routes/routes.ts
  src/test/a11y/tests/style-guide/iac-daily-list.test.ts
  src/test/routes/style-guide/iac-daily-list.test.ts
  src/test/unit/controllers/style-guide/IacDailyListController.test.ts
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/views/style-guide/iac-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1286

#1294 PUB-2448 Add case reporting restrictions for Family, Mixed and COP lists
  src/main/resources/locales/cy/style-guide/civil-and-family-daily-cause-list.json
  src/main/resources/locales/cy/style-guide/cop-daily-cause-list.json
  src/main/resources/locales/cy/style-guide/family-daily-cause-list.json
  src/main/resources/locales/en/style-guide/civil-and-family-daily-cause-list.json
  src/main/resources/locales/en/style-guide/cop-daily-cause-list.json
  src/main/resources/locales/en/style-guide/family-daily-cause-list.json
  src/main/service/ListParseHelperService.ts
  src/main/service/listManipulation/CivilFamilyAndMixedListService.ts
  src/main/service/listManipulation/CopDailyListService.ts
  src/main/service/listManipulation/OpaPressListService.ts
  src/main/service/listManipulation/OpaPublicListService.ts
  src/main/service/listManipulation/OpaResultsService.ts
  src/main/views/style-guide/civil-and-family-daily-cause-list.njk
  src/main/views/style-guide/cop-daily-cause-list.njk
  src/main/views/style-guide/family-daily-cause-list.njk
  src/test/end-to-end/shared/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/copDailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/hearingparty/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/hearingparty/familyDailyCauseList.json
  src/test/unit/service/listManipulation/CivilFamilyAndMixedListService.test.ts
  src/test/unit/service/listManipulation/CopDailyListService.test.ts
  src/test/unit/service/listManipulation/hearingparty/CivilFamilyAndMixedListService.test.ts
  src/test/unit/views/style-guide/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/style-guide/cop-daily-cause-list.test.ts
  src/test/unit/views/style-guide/family-daily-cause-list.test.ts
  src/test/unit/views/style-guide/hearingparty/civil-and-family-daily-cause-list.test.ts
  src/test/unit/views/style-guide/hearingparty/family-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1294

#1298 PUB-2490 - Updated nightly time
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1298
