Repository hmcts/pip-frontend, pull requests merged in 2024-03, with the labels that each got.

#1211 PUB-1766 Add Select All for bulk unsubscribe
  src/main/assets/scss/home.scss
  src/main/controllers/BulkUnsubscribeConfirmationController.ts
  src/main/controllers/BulkUnsubscribeController.ts
  src/main/resources/locales/cy/bulk-unsubscribe-confirmation.json
  src/main/resources/locales/cy/bulk-unsubscribe.json
  src/main/resources/locales/en/bulk-unsubscribe-confirmation.json
  src/main/resources/locales/en/bulk-unsubscribe.json
  src/main/service/subscriptionService.ts
  src/main/views/bulk-unsubscribe-confirmation.njk
  src/main/views/bulk-unsubscribe.njk
  src/test/a11y/tests/media-routes.test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/unit/controllers/BulkUnsubscribeConfirmationController.test.ts
  src/test/unit/controllers/BulkUnsubscribeController.test.ts
  src/test/unit/service/subscriptionService.test.ts
  src/test/unit/views/bulk-unsubscribe-confirmation.test.ts
  src/test/unit/views/bulk-unsubscribe.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1211

#1223 Pub 2341 remove informant from sscs daily lists
  src/main/service/listManipulation/SscsDailyListService.ts
  src/test/unit/mocks/sscsDailyList.json
  src/test/unit/service/listManipulation/sscsListService.test.ts
  src/test/unit/views/sscs-daily-list-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1223

#1232 Fix build pipeline
  package.json
  src/test/end-to-end/shared/mocks/etDailyList.json
  src/test/end-to-end/shared/mocks/invalidEtDailyList.json
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
  src/test/end-to-end/tests/custom-steps.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1232

#1222 PUB-2264: Adding sessionChannel to IAC Daily List mock and updating t…
  src/test/unit/mocks/iacDailyList.json
  src/test/unit/views/iac-daily-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1222

#1228 PUB-2344 - Fixed SSCS bug
  src/main/service/listManipulation/SscsDailyListService.ts
  src/main/service/listParseHelperService.ts
  src/test/unit/mocks/hearingparty/sscsDailyList.json
  src/test/unit/mocks/sscsDailyList.json
  src/test/unit/service/listManipulation/hearingparty/sscsListService.test.ts
  src/test/unit/service/listManipulation/sscsListService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1228

#1218 PUB-2179 - Remove non-functional scrollbars
  src/main/assets/scss/main.scss
  src/main/views/care-standards-list.njk
  src/main/views/civil-and-family-daily-cause-list.njk
  src/main/views/cop-daily-cause-list.njk
  src/main/views/crown-daily-list.njk
  src/main/views/crown-firm-list.njk
  src/main/views/crown-warned-list.njk
  src/main/views/daily-cause-list.njk
  src/main/views/et-daily-list.njk
  src/main/views/et-fortnightly-list.njk
  src/main/views/family-daily-cause-list.njk
  src/main/views/iac-daily-list.njk
  src/main/views/magistrates-public-list.njk
  src/main/views/opa-public-list.njk
  src/main/views/primary-health-list.njk
  src/main/views/single-justice-procedure-press.njk
  src/main/views/single-justice-procedure.njk
  src/main/views/sscs-daily-list.njk
  src/test/end-to-end/tests/admin/manual-upload-json-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1218

#1230 PUB-2334 Dependency updates
  .yarn/releases/yarn-3.6.4.cjs
  .yarn/releases/yarn-3.8.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1230

#1242 Force upgrade of express to 4.19.2
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1242

#1226 PUB-2303: Removed remaining @schemaLocation fields from schemas
  src/test/end-to-end/shared/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/civilAndFamilyDailyCauseList.json
  src/test/unit/mocks/crownDailyList.json
  src/test/unit/mocks/crownWarnedList.json
  src/test/unit/mocks/dailyCauseEmptyCourtList.json
  src/test/unit/mocks/dailyCauseList.json
  src/test/unit/mocks/familyDailyCauseList.json
  src/test/unit/mocks/familyDailyCauseListPartyMapping.json
  src/test/unit/mocks/hearingparty/crownDailyList.json
  src/test/unit/mocks/hearingparty/crownWarnedList.json
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1226
