Repository hmcts/pip-frontend, pull requests merged in 2025-07, with the labels that each got.

#1501 PUB-2901 Remove Care Standards and Primary Health list types
  src/main/controllers/style-guide/TribunalNationalListsController.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/care-standards-list.json
  src/main/resources/locales/cy/primary-health-list.json
  src/main/resources/locales/en/care-standards-list.json
  src/main/resources/locales/en/primary-health-list.json
  src/main/routes/routes.ts
  src/main/service/listManipulation/TribunalNationalListsService.ts
  src/main/views/style-guide/care-standards-list.njk
  src/main/views/style-guide/primary-health-list.njk
  src/test/a11y/tests/style-guide/care-standards-list.test.ts
  src/test/a11y/tests/style-guide/primary-health-list.test.ts
  src/test/end-to-end/shared/mocks/civilDailyCauseList.json
  src/test/end-to-end/shared/mocks/primaryHealthList.json
  src/test/end-to-end/tests/hmi-publication-receipt-test.ts
  src/test/end-to-end/tests/sorting-list-table-test.ts
  src/test/routes/style-guide/care-standards-list.test.ts
  src/test/routes/style-guide/primary-health-list.test.ts
  src/test/unit/controllers/style-guide/TribunalNationalListsController.test.ts
  src/test/unit/helpers/dateTimeHelper.test.ts
  src/test/unit/mocks/careStandardsList.json
  src/test/unit/mocks/primaryHealthList.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/listManipulation/TribunalNationalListsService.test.ts
  src/test/unit/views/style-guide/care-standards-list.test.ts
  src/test/unit/views/style-guide/primary-health-list.test.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1501

#1505 PUB-2905 Stop deletion of list types if there are remaining location subscription
  src/main/controllers/BulkUnsubscribeConfirmationController.ts
  src/main/controllers/UnsubscribeConfirmationController.ts
  src/main/controllers/system-admin/ManageThirdPartyUsersSubscriptionsController.ts
  src/main/service/SubscriptionService.ts
  src/main/service/ThirdPartyService.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/unit/controllers/BulkUnsubscribeConfirmationController.test.ts
  src/test/unit/controllers/UnsubscribeConfirmationController.test.ts
  src/test/unit/service/SubscriptionService.test.ts
  src/test/unit/service/ThirdPartyService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1505

#1512 PUB-2952 Update to CaTH interstitial page
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1512

#1502 PUB-2918 - Removed planning daily cause list
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/planning-court-daily-cause-list.json
  src/main/resources/locales/en/planning-court-daily-cause-list.json
  src/main/routes/routes.ts
  src/test/a11y/tests/style-guide/planning-court-daily-cause-list.test.ts
  src/test/routes/style-guide/planning-court-daily-cause-list.test.ts
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/views/style-guide/planning-court-daily-cause-list.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1502
