Repository hmcts/pip-frontend, pull requests merged in 2025-04, with the labels that each got.

#1454 PUB-2806 Add functionality to re-submit subscription in blob explorer
  src/main/controllers/system-admin/BlobViewJsonController.ts
  src/main/controllers/system-admin/BlobViewSubscriptionResubmitConfirmationController.ts
  src/main/controllers/system-admin/BlobViewSubscriptionResubmitConfirmedController.ts
  src/main/resources/auditActions.json
  src/main/resources/locales/cy/blob-view-json.json
  src/main/resources/locales/cy/blob-view-subscription-resubmit-confirmation.json
  src/main/resources/locales/cy/blob-view-subscription-resubmit-confirmed.json
  src/main/resources/locales/en/blob-view-json.json
  src/main/resources/locales/en/blob-view-subscription-resubmit-confirmation.json
  src/main/resources/locales/en/blob-view-subscription-resubmit-confirmed.json
  src/main/resources/requests/SubscriptionRequests.ts
  src/main/routes/routes.ts
  src/main/service/SubscriptionService.ts
  src/main/views/system-admin/blob-view-json.njk
  src/main/views/system-admin/blob-view-locations.njk
  src/main/views/system-admin/blob-view-publications.njk
  src/main/views/system-admin/blob-view-subscription-resubmit-confirmation.njk
  src/main/views/system-admin/blob-view-subscription-resubmit-confirmed.njk
  src/test/a11y/tests/system-admin-routes.test.ts
  src/test/end-to-end/tests/system-admin/audit-log-test.ts
  src/test/end-to-end/tests/system-admin/blob-explorer-test.ts
  src/test/routes/system-admin/blob-view-json.test.ts
  src/test/routes/system-admin/blob-view-subscription-resubmit-confirmation.test.ts
  src/test/routes/system-admin/blob-view-subscription-resubmit-confirmed.test.ts
  src/test/unit/controllers/system-admin/BlobViewJsonController.test.ts
  src/test/unit/controllers/system-admin/BlobViewSubscriptionResubmitConfirmationController.test.ts
  src/test/unit/controllers/system-admin/BlobViewSubscriptionResubmitConfirmedController.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/SubscriptionService.test.ts
  src/test/unit/views/system-admin/blob-view-json.test.ts
  src/test/unit/views/system-admin/blob-view-subscription-resubmit-confirmation.test.ts
  src/test/unit/views/system-admin/blob-view-subscription-resubmit-confirmed.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1454

#1461 PUB-2831 - Updated SSCS Non-Strategic
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/sscs-london-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-midlands-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-north-east-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-north-west-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-scotland-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-south-east-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-wales-and-south-west-daily-hearing-list.json
  src/main/resources/locales/en/sscs-london-daily-hearing-list.json
  src/main/resources/locales/en/sscs-midlands-daily-hearing-list.json
  src/main/resources/locales/en/sscs-north-east-daily-hearing-list.json
  src/main/resources/locales/en/sscs-north-west-daily-hearing-list.json
  src/main/resources/locales/en/sscs-scotland-daily-hearing-list.json
  src/main/resources/locales/en/sscs-south-east-daily-hearing-list.json
  src/main/resources/locales/en/sscs-wales-and-south-west-daily-hearing-list.json
  src/main/views/style-guide/sscs-daily-hearing-list.njk
  src/test/unit/views/style-guide/sscs-daily-hearing-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1461

#1463 PUB-2811 List type configuration
  src/main/controllers/SubscriptionConfigureListController.ts
  src/main/models/ListType.ts
  src/main/resources/jurisdictionTypeLookup.json
  src/main/resources/listLookup.json
  src/main/resources/welshJurisdictionLookup.json
  src/main/service/LocationService.ts
  src/main/service/SubscriptionService.ts
  src/main/views/macros/common-components.njk
  src/test/end-to-end/shared/mocks/reference-data-invalid.csv
  src/test/end-to-end/shared/mocks/system-admin-upload-reference-data-test.csv
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/routes/subscription-configure-list.test.ts
  src/test/unit/controllers/SubscriptionConfigureListController.test.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/mocks/deleteReferenceDataCourt.csv
  src/test/unit/mocks/listTypeSubscriptions/listTypeSubscriptions.json
  src/test/unit/mocks/testReferenceData.csv
  src/test/unit/service/FilterService.test.ts
  src/test/unit/service/LocationService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/SubscriptionService.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1463
