Repository hmcts/pip-frontend, pull requests merged in 2025-02, with the labels that each got.

#1423 PUB-2738 Text changes to Admin tiles and manual upload page
  src/main/resources/locales/cy/admin-dashboard.json
  src/main/resources/locales/cy/manual-upload.json
  src/main/resources/locales/en/admin-dashboard.json
  src/main/resources/locales/en/manual-upload.json
  src/main/views/admin/manual-upload.njk
  src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
  src/test/unit/views/admin/admin-dashboard.test.ts
  src/test/unit/views/admin/manual-upload.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1423

#1425 Modified functional tests to fix CodeceptJS page load problem
  src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
  src/test/end-to-end/tests/azure-screen-flow-welsh-test.ts
  src/test/end-to-end/tests/banner-navigation-test.ts
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/hmi-publication-receipt-test.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/search-court-test.ts
  src/test/end-to-end/tests/single-justice-procedure-test.ts
  src/test/end-to-end/tests/sjp-cases-filter-and-paging-test.ts
  src/test/end-to-end/tests/sorting-list-table-test.ts
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1425

#1428 PUB-2175 - Fixed header location + removed warning text
  src/main/resources/locales/cy/delete-court-reference-data-confirmation.json
  src/main/resources/locales/cy/remove-list-confirmation.json
  src/main/resources/locales/en/delete-court-reference-data-confirmation.json
  src/main/resources/locales/en/remove-list-confirmation.json
  src/main/views/admin/remove-list-confirmation.njk
  src/main/views/system-admin/delete-court-reference-data-confirmation.njk
  src/test/unit/views/admin/remove-list-confirmation.test.ts
  src/test/unit/views/system-admin/delete-court-reference-data-confirmation.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1428

#1436 PUB-2774 Add wait after e2e test login
  src/test/end-to-end/tests/custom-steps.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/system-admin/manage-third-party-users-test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1436

#1438 PUB-2770 - Interstitial pages
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1438

#1432 PUB-2654 - SSO rejected login page error message
  src/main/controllers/SsoRejectedLoginController.ts
  src/test/routes/sso-rejected-login.test.ts
  src/test/unit/controllers/SsoRejectedLoginController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1432

#1434 PUB-2755 Add SSCS Daily Hearing Lists
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/sscs-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-london-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-midlands-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-north-east-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-north-west-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-scotland-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-south-east-daily-hearing-list.json
  src/main/resources/locales/cy/sscs-wales-and-south-west-daily-hearing-list.json
  src/main/resources/locales/en/sscs-daily-hearing-list.json
  src/main/resources/locales/en/sscs-london-daily-hearing-list.json
  src/main/resources/locales/en/sscs-midlands-daily-hearing-list.json
  src/main/resources/locales/en/sscs-north-east-daily-hearing-list.json
  src/main/resources/locales/en/sscs-north-west-daily-hearing-list.json
  src/main/resources/locales/en/sscs-scotland-daily-hearing-list.json
  src/main/resources/locales/en/sscs-south-east-daily-hearing-list.json
  src/main/resources/locales/en/sscs-wales-and-south-west-daily-hearing-list.json
  src/main/routes/routes.ts
  src/main/views/style-guide/sscs-daily-hearing-list.njk
  src/test/a11y/tests/style-guide/ssca-daily-hearing-list.test.ts
  src/test/routes/style-guide/ssca-daily-hearing-list.test.ts
  src/test/unit/mocks/sscsDailyHearingList.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/views/style-guide/sscs-daily-hearing-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1434

#1433 PUB-2762 - Update to the UT-AAC Tribunal Open Justice Statement
  src/main/resources/locales/cy/ut-aac-daily-hearing-list.json
  src/main/resources/locales/en/ut-aac-daily-hearing-list.json
  src/test/unit/views/style-guide/ut-aac-daily-hearing-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1433

#1435 PUB-2763 - Update UT-IAC Statutory Appeal Tribunal hearing list
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/ut-iac-statutory-appeals-daily-hearing-list.json
  src/main/resources/locales/en/ut-iac-statutory-appeals-daily-hearing-list.json
  src/test/unit/views/style-guide/ut-iac-statutory-appeals-daily-hearing-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1435

#1431 PUB-2758 Monthly dependency update
  .nvmrc
  package.json
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1431

#1437 PUB-2772 Allow colon and full stop in non-strategic time format
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/style-guide/ftt-lr-weekly-hearing-list.njk
  src/main/views/style-guide/ftt-rpt-weekly-hearing-list.njk
  src/main/views/style-guide/ftt-tax-weekly-hearing-list.njk
  src/main/views/style-guide/grc-weekly-hearing-list.njk
  src/main/views/style-guide/siac-poac-paac-weekly-hearing-list.njk
  src/main/views/style-guide/sscs-daily-hearing-list.njk
  src/main/views/style-guide/ut-aac-daily-hearing-list.njk
  src/main/views/style-guide/ut-iac-judicial-review-daily-hearing-list.njk
  src/main/views/style-guide/ut-iac-statutory-appeals-daily-hearing-list.njk
  src/main/views/style-guide/ut-lc-daily-hearing-list.njk
  src/main/views/style-guide/ut-t-and-cc-daily-hearing-list.njk
  src/main/views/style-guide/wpafcc-weekly-hearing-list.njk
  src/test/unit/mocks/fttLandRegistryTribunalWeeklyHearingList.json
  src/test/unit/mocks/fttResidentialPropertyTribunalWeeklyHearingList.json
  src/test/unit/mocks/fttTaxWeeklyHearingList.json
  src/test/unit/mocks/grcWeeklyHearingList.json
  src/test/unit/mocks/siacWeeklyHearingList.json
  src/test/unit/mocks/sscsDailyHearingList.json
  src/test/unit/mocks/utAdministrativeAppealsChamberDailyHearingList.json
  src/test/unit/mocks/utLandsChamberDailyHearingList.json
  src/test/unit/mocks/utTaxAndChanceryChamberDailyHearingList.json
  src/test/unit/mocks/wpafccWeeklyHearingList.json
  src/test/unit/modules/nunjucks/njkFilters.test.ts
  src/test/unit/views/style-guide/ftt-lr-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ftt-rpt-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ftt-tax-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/grc-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/siac-poac-paac-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/sscs-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-aac-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-lc-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-t-and-cc-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/wpafcc-weekly-hearing-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1437

#1441 PUB-2737 Add no list message override for Mental Health Tribunal
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/models/AdditionalLocationInfo.ts
  src/main/resources/additionalLocationInfoLookup.json
  src/main/service/LocationService.ts
  src/main/views/summary-of-publications.njk
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/service/LocationService.test.ts
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1441
