Repository hmcts/pip-frontend, pull requests merged in 2025-08, with the labels that each got.

#1516 PUB-2968 Update location upload with duplicated location names
  src/main/controllers/system-admin/ReferenceDataUploadSummaryController.ts
  src/main/resources/requests/DataManagementRequests.ts
  src/main/service/FileHandlingService.ts
  src/main/service/ManualUploadService.ts
  src/main/views/system-admin/reference-data-upload-summary.njk
  src/test/unit/controllers/system-admin/ReferenceDataUploadSummaryController.test.ts
  src/test/unit/requests/dataManagementRequests.test.ts
  src/test/unit/service/FileHandlingService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1516

#1521 Added test for Data Management request
  src/test/unit/requests/dataManagementRequests.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1521

#1524 Updated test coverage
  jest.config.js
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1524

#1525 PUB-2892 Do not run Crime Idam tests on PR stage
  package.json
  src/test/end-to-end/tests/login-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1525
