Repository hmcts/pip-frontend, pull requests merged in 2025-06, with the labels that each got.

#1468 PUB-2823 - Add Interim Applications List
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/interim-applications-chd-daily-cause-list.json
  src/main/resources/locales/en/interim-applications-chd-daily-cause-list.json
  src/main/routes/routes.ts
  src/main/views/style-guide/interim-applications-chd-daily-cause-list.njk
  src/test/a11y/tests/style-guide/interim-applications-chd-daily-cause-list.test.ts
  src/test/routes/style-guide/interim-applications-chd-daily-cause-list.test.ts
  src/test/unit/mocks/interimApplicationsChanceryDivisionDailyCauseList.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/views/style-guide/interim-applications-chd-daily-cause-list.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1468

#1477 PUB-2880 Add Administrative Courts: Create Schema and List types (Part 1)
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/birmingham-administrative-court-daily-cause-list.json
  src/main/resources/locales/cy/bristol-and-cardiff-administrative-court-daily-cause-list.json
  src/main/resources/locales/cy/leeds-administrative-court-daily-cause-list.json
  src/main/resources/locales/cy/manchester-administrative-court-daily-cause-list.json
  src/main/resources/locales/en/birmingham-administrative-court-daily-cause-list.json
  src/main/resources/locales/en/bristol-and-cardiff-administrative-court-daily-cause-list.json
  src/main/resources/locales/en/leeds-administrative-court-daily-cause-list.json
  src/main/resources/locales/en/manchester-administrative-court-daily-cause-list.json
  src/main/routes/routes.ts
  src/main/views/style-guide/birmingham-administrative-court-daily-cause-list.njk
  src/main/views/style-guide/bristol-and-cardiff-administrative-court-daily-cause-list.njk
  src/main/views/style-guide/leeds-administrative-court-daily-cause-list.njk
  src/main/views/style-guide/manchester-administrative-court-daily-cause-list.njk
  src/test/a11y/tests/style-guide/birmingham-administrative-court-daily-cause-list.test.ts
  src/test/a11y/tests/style-guide/bristol-and-cardiff-administrative-court-daily-cause-list.test.ts
  src/test/a11y/tests/style-guide/leeds-administrative-court-daily-cause-list.test.ts
  src/test/a11y/tests/style-guide/manchester-administrative-court-daily-cause-list.test.ts
  src/test/routes/style-guide/birmingham-administrative-court-daily-cause-list.test.ts
  src/test/routes/style-guide/bristol-and-cardiff-administrative-court-daily-cause-list.test.ts
  src/test/routes/style-guide/leeds-administrative-court-daily-cause-list.test.ts
  src/test/routes/style-guide/manchester-administrative-court-daily-cause-list.test.ts
  src/test/unit/mocks/administrativeCourtDailyCauseList.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/SubscriptionService.test.ts
  src/test/unit/views/style-guide/birmingham-administrative-court-daily-cause-list.test.ts
  src/test/unit/views/style-guide/bristol-and-cardiff-administrative-court-daily-cause-list.test.ts
  src/test/unit/views/style-guide/leeds-administrative-court-daily-cause-list.test.ts
  src/test/unit/views/style-guide/manchester-administrative-court-daily-cause-list.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1477

#1489 Pub 2873
  package.json
  src/test/end-to-end/crossbrowser.conf.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1489

#1484 PUB-2891 Add Caution + No List Message Location Message for System Admin Screens
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/controllers/system-admin/LocationMetadataCreateConfirmedController.ts
  src/main/controllers/system-admin/LocationMetadataDeleteConfirmationController.ts
  src/main/controllers/system-admin/LocationMetadataDeleteConfirmedController.ts
  src/main/controllers/system-admin/LocationMetadataManageController.ts
  src/main/controllers/system-admin/LocationMetadataSearchController.ts
  src/main/controllers/system-admin/LocationMetadataUpdateConfirmedController.ts
  src/main/models/LocationMetadata.ts
  src/main/resources/additionalLocationInfoLookup.json
  src/main/resources/locales/cy/location-metadata-create-confirmed.json
  src/main/resources/locales/cy/location-metadata-delete-confirmation.json
  src/main/resources/locales/cy/location-metadata-delete-confirmed.json
  src/main/resources/locales/cy/location-metadata-manage.json
  src/main/resources/locales/cy/location-metadata-search.json
  src/main/resources/locales/cy/location-metadata-update-confirmed.json
  src/main/resources/locales/cy/system-admin-dashboard.json
  src/main/resources/locales/en/location-metadata-create-confirmed.json
  src/main/resources/locales/en/location-metadata-delete-confirmation.json
  src/main/resources/locales/en/location-metadata-delete-confirmed.json
  src/main/resources/locales/en/location-metadata-manage.json
  src/main/resources/locales/en/location-metadata-search.json
  src/main/resources/locales/en/location-metadata-update-confirmed.json
  src/main/resources/locales/en/system-admin-dashboard.json
  src/main/resources/requests/LocationRequests.ts
  src/main/routes/routes.ts
  src/main/service/LocationService.ts
  src/main/views/summary-of-publications.njk
  src/main/views/system-admin/location-metadata-create-confirmed.njk
  src/main/views/system-admin/location-metadata-delete-confirmation.njk
  src/main/views/system-admin/location-metadata-delete-confirmed.njk
  src/main/views/system-admin/location-metadata-manage.njk
  src/main/views/system-admin/location-metadata-search.njk
  src/main/views/system-admin/location-metadata-update-confirmed.njk
  src/test/a11y/tests/system-admin-routes.test.ts
  src/test/end-to-end/tests/system-admin/manage-location-metadata-test.ts
  src/test/routes/system-admin/location-metadata-create-confirmed.test.ts
  src/test/routes/system-admin/location-metadata-delete-confirmation.test.ts
  src/test/routes/system-admin/location-metadata-delete-confirmed.test.ts
  src/test/routes/system-admin/location-metadata-manage.test.ts
  src/test/routes/system-admin/location-metadata-search.test.ts
  src/test/routes/system-admin/location-metadata-update-confirmed.test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/controllers/system-admin/LocationMetadataCreateConfirmedController.test.ts
  src/test/unit/controllers/system-admin/LocationMetadataDeleteConfirmationController.test.ts
  src/test/unit/controllers/system-admin/LocationMetadataDeleteConfirmedController.ts
  src/test/unit/controllers/system-admin/LocationMetadataManageController.test.ts
  src/test/unit/controllers/system-admin/LocationMetadataSearchController.test.ts
  src/test/unit/controllers/system-admin/LocationMetadataUpdateConfirmedController.ts
  src/test/unit/requests/locationRequests.test.ts
  src/test/unit/service/LocationService.test.ts
  src/test/unit/views/summary-of-publications.test.ts
  src/test/unit/views/system-admin/location-metadata-create-confirmed.test.ts
  src/test/unit/views/system-admin/location-metadata-delete-confirmation.test.ts
  src/test/unit/views/system-admin/location-metadata-delete-confirmed.test.ts
  src/test/unit/views/system-admin/location-metadata-manage.test.ts
  src/test/unit/views/system-admin/location-metadata-search.test.ts
  src/test/unit/views/system-admin/location-metadata-update-confirmed.test.ts
  src/test/unit/views/system-admin/system-admin-dashboard.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1484

#1495 PUB-2825 Update styling in new GOV.UK frontend
  package.json
  src/main/app.ts
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  src/main/views/macros/common-components.njk
  src/main/views/template.njk
  webpack/govukFrontend.js
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1495

#1496 Remove list type from cache after location subscription is removed
  src/main/controllers/PendingSubscriptionsController.ts
  src/main/controllers/SubscriptionConfirmationPreviewController.ts
  src/main/service/SubscriptionService.ts
  src/test/unit/controllers/PendingSubscriptionsController.test.ts
  src/test/unit/controllers/SubscriptionConfigureListPreviewController.test.ts
  src/test/unit/controllers/SubscriptionConfirmationPreviewController.test.ts
  src/test/unit/service/SubscriptionService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1496

#1497 PUB-2878 - Updated Dependencies
  .yarn/releases/yarn-4.7.0.cjs
  .yarn/releases/yarn-4.9.2.cjs
  .yarnrc.yml
  package.json
  src/main/assets/scss/main.scss
  src/test/fortify/build.gradle
  src/test/fortify/gradle/wrapper/gradle-wrapper.jar
  src/test/fortify/gradle/wrapper/gradle-wrapper.properties
  src/test/fortify/gradlew
  src/test/fortify/gradlew.bat
  src/test/unit/middlewares/fileErrorHandler.middleware.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1497

#1499 PUB-2919 Add RCJ to CaTH interstitial page
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1499
