Repository hmcts/pip-frontend, pull requests merged in 2025-09, with the labels that each got.

#1527 PUB-2764 Fixed blob explorer crash with flat file publication
  src/main/controllers/system-admin/BlobViewLocationsController.ts
  src/main/controllers/system-admin/BlobViewPublicationController.ts
  src/main/resources/locales/cy/blob-view-publication.json
  src/main/resources/locales/en/blob-view-publication.json
  src/main/routes/routes.ts
  src/main/views/system-admin/blob-view-publication.njk
  src/main/views/system-admin/blob-view-publications.njk
  src/test/a11y/tests/system-admin-routes.test.ts
  src/test/accessibility/accessibility-system-admin-test.ts
  src/test/end-to-end/shared/helpers/testingSupportApiHelper.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/system-admin/blob-explorer-test.ts
  src/test/routes/system-admin/blob-view-publication.test.ts
  src/test/unit/controllers/system-admin/BlobViewLocationsController.test.ts
  src/test/unit/controllers/system-admin/BlobViewPublicationController.test.ts
  src/test/unit/views/system-admin/blob-view-publication.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1527

#1529 PUB-2965 - Removed CIC Daily Hearing List
  src/main/resources/listLookup.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1529

#1534 PUB-2419 Remove custom beta link styling
  src/main/assets/scss/main.scss
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1534

#1523 PUB-2798 - Add headers to account, data management and subscription requests
  src/main/authentication/ssoAuthentication.ts
  src/main/controllers/ListDownloadFilesController.ts
  src/main/controllers/admin/AdminDashboardController.ts
  src/main/controllers/admin/ManualUploadSummaryController.ts
  src/main/controllers/admin/MediaAccountApprovalConfirmationController.ts
  src/main/controllers/admin/MediaAccountApprovalController.ts
  src/main/controllers/admin/MediaAccountRejectionConfirmationController.ts
  src/main/controllers/admin/MediaAccountRejectionController.ts
  src/main/controllers/admin/MediaAccountRejectionReasonsController.ts
  src/main/controllers/admin/MediaAccountReviewController.ts
  src/main/controllers/admin/MediaApplicationsController.ts
  src/main/controllers/system-admin/AuditLogDetailsController.ts
  src/main/controllers/system-admin/BlobViewLocationsController.ts
  src/main/controllers/system-admin/BlobViewPublicationsController.ts
  src/main/controllers/system-admin/ManageThirdPartyUsersSubscriptionsController.ts
  src/main/controllers/system-admin/ReferenceDataUploadSummaryController.ts
  src/main/resources/requests/AccountManagementRequests.ts
  src/main/resources/requests/DataManagementRequests.ts
  src/main/resources/requests/LocationRequests.ts
  src/main/resources/requests/PublicationFileRequests.ts
  src/main/resources/requests/PublicationRequests.ts
  src/main/resources/requests/SubscriptionRequests.ts
  src/main/service/AuditLogService.ts
  src/main/service/ListDownloadService.ts
  src/main/service/LocationService.ts
  src/main/service/ManualUploadService.ts
  src/main/service/MediaAccountApplicationService.ts
  src/main/service/PublicationService.ts
  src/main/service/SubscriptionService.ts
  src/main/service/SummaryOfPublicationsService.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/routes/admin/manual-upload-summary.test.ts
  src/test/unit/controllers/admin/ManualUploadSummaryController.test.ts
  src/test/unit/controllers/admin/MediaAccountApprovalController.test.ts
  src/test/unit/controllers/admin/MediaAccountRejectionController.test.ts
  src/test/unit/requests/accountManagementRequests.test.ts
  src/test/unit/requests/dataManagementRequests.test.ts
  src/test/unit/requests/locationRequests.test.ts
  src/test/unit/requests/publicationFileRequests.test.ts
  src/test/unit/requests/publicationRequests.test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/service/ListDownloadService.test.ts
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/MediaAccountApplicationService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/SubscriptionService.test.ts
  src/test/unit/service/SummaryOfPublicationsService.test.ts
  src/test/unit/views/list-download-files.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1523

#1535 PUB-2980 Express v5 upgrade
  package.json
  src/main/app.ts
  src/main/routes/routes.ts
  src/test/unit/controllers/style-guide/CopDailyCauseListController.test.ts
  src/test/unit/controllers/style-guide/CrownDailyListController.test.ts
  src/test/unit/controllers/style-guide/CrownFirmListController.test.ts
  src/test/unit/controllers/style-guide/CrownWarnedListController.test.ts
  src/test/unit/controllers/style-guide/EtDailyListController.test.ts
  src/test/unit/controllers/style-guide/EtFortnightlyListController.test.ts
  src/test/unit/controllers/style-guide/IacDailyListController.test.ts
  src/test/unit/controllers/style-guide/MagistratesAdultCourtListController.test.ts
  src/test/unit/controllers/style-guide/MagistratesPublicListController.test.ts
  src/test/unit/controllers/style-guide/MagistratesStandardListController.test.ts
  src/test/unit/controllers/style-guide/SscsDailyListController.test.ts
  src/test/unit/controllers/system-admin/AuditLogDetailsController.test.ts
  src/test/unit/controllers/system-admin/AuditLogViewerController.test.ts
  src/test/unit/controllers/system-admin/DeleteCourtReferenceDataController.test.ts
  src/test/unit/controllers/system-admin/DeleteUserController.test.ts
  src/test/unit/controllers/system-admin/ManageUserController.test.ts
  src/test/unit/controllers/system-admin/UserManagementController.test.ts
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1535

#1541 PUB-2855 - Update Court of Appeal List open justice statement
  src/main/resources/locales/cy/court-of-appeal-criminal-daily-cause-list.json
  src/main/resources/locales/en/court-of-appeal-criminal-daily-cause-list.json
  src/main/views/style-guide/court-of-appeal-criminal-daily-cause-list.njk
  src/test/unit/views/style-guide/court-of-appeal-criminal-daily-cause-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1541
