Repository hmcts/pip-frontend, pull requests merged in 2025-01, with the labels that each got.

#1399 PUB-2712 Add CIC Daily Hearing List
  src/main/resources/listLookup.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1399

#1406 Merge freeze into master
  src/main/modules/i18next/index.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1406

#1409 PUB-2716 - Fixed filter overlap
  src/main/views/alphabetical-search.njk
  src/main/views/location-name-search.njk
  src/main/views/macros/sjp-common.njk
  src/main/views/subscription-configure-list.njk
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1409

#1408 PUB-2697 Accessibility - Add visually hidden text to alphabetical search page
  src/main/resources/locales/cy/alphabetical-search.json
  src/main/resources/locales/en/alphabetical-search.json
  src/main/views/alphabetical-search.njk
  src/test/unit/views/alphabetical-search.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1408

#1416 PUB-2735 - Adding query param to change button for non strategic
  src/main/views/admin/manual-upload-summary.njk
  src/test/unit/views/admin/manual-upload-summary.test.ts
Labels: ns:pip, prd:pip

#1407 PUB-2694 - Remove List journey accessibility improvements
  src/main/service/ManualUploadService.ts
  src/main/views/admin/remove-list-search-results.njk
  src/test/a11y/tests/admin-routes.test.ts
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/views/admin/remove-list-search-results.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1407

#1419 PUB-2726 - Updated List Types on manual upload pages
  src/main/controllers/admin/ManualUploadController.ts
  src/main/models/ListType.ts
  src/main/resources/listLookup.json
  src/main/service/ManualUploadService.ts
  src/main/views/admin/manual-upload.njk
  src/test/unit/controllers/CaseReferenceNumberSearchController.test.ts
  src/test/unit/controllers/CaseReferenceNumberSearchResultController.test.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/views/admin/manual-upload.test.ts
Labels: ns:pip, prd:pip

#1417 PUB-2720 Update non strategic list names
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/ftt-lr-weekly-hearing-list.json
  src/main/resources/locales/cy/ftt-rpt-weekly-hearing-list.json
  src/main/resources/locales/cy/ftt-tax-weekly-hearing-list.json
  src/main/resources/locales/cy/ut-aac-daily-hearing-list.json
  src/main/resources/locales/cy/ut-lc-daily-hearing-list.json
  src/main/resources/locales/cy/ut-t-and-cc-daily-hearing-list.json
  src/main/resources/locales/en/ftt-lr-weekly-hearing-list.json
  src/main/resources/locales/en/ftt-rpt-weekly-hearing-list.json
  src/main/resources/locales/en/ftt-tax-weekly-hearing-list.json
  src/main/resources/locales/en/ut-aac-daily-hearing-list.json
  src/main/resources/locales/en/ut-lc-daily-hearing-list.json
  src/main/resources/locales/en/ut-t-and-cc-daily-hearing-list.json
  src/main/routes/routes.ts
  src/main/views/style-guide/ftt-lr-weekly-hearing-list.njk
  src/main/views/style-guide/ftt-rpt-weekly-hearing-list.njk
  src/main/views/style-guide/ftt-tax-weekly-hearing-list.njk
  src/main/views/style-guide/ut-aac-daily-hearing-list.njk
  src/main/views/style-guide/ut-lc-daily-hearing-list.njk
  src/main/views/style-guide/ut-t-and-cc-daily-hearing-list.njk
  src/test/a11y/tests/style-guide/ftt-lr-weekly-hearing-list.test.ts
  src/test/a11y/tests/style-guide/ftt-rpt-weekly-hearing-list.test.ts
  src/test/a11y/tests/style-guide/ftt-tax-weekly-hearing-list.test.ts
  src/test/a11y/tests/style-guide/ut-aac-daily-hearing-list.test.ts
  src/test/a11y/tests/style-guide/ut-lc-daily-hearing-list.test.ts
  src/test/a11y/tests/style-guide/ut-t-and-cc-daily-hearing-list.test.ts
  src/test/routes/style-guide/ftt-lr-weekly-hearing-list.test.ts
  src/test/routes/style-guide/ftt-rpt-weekly-hearing-list.test.ts
  src/test/routes/style-guide/ftt-tax-weekly-hearing-list.test.ts
  src/test/routes/style-guide/ut-aac-daily-hearing-list.test.ts
  src/test/routes/style-guide/ut-lc-daily-hearing-list.test.ts
  src/test/routes/style-guide/ut-t-and-cc-daily-hearing-list.test.ts
  src/test/unit/mocks/fttLandRegistryTribunalWeeklyHearingList.json
  src/test/unit/mocks/fttResidentialPropertyTribunalWeeklyHearingList.json
  src/test/unit/mocks/fttTaxWeeklyHearingList.json
  src/test/unit/mocks/utAdministrativeAppealsChamberDailyHearingList.json
  src/test/unit/mocks/utLandsChamberDailyHearingList.json
  src/test/unit/mocks/utTaxAndChanceryChamberDailyHearingList.json
  src/test/unit/views/style-guide/ftt-lr-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ftt-rpt-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ftt-tax-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-aac-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-lc-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-t-and-cc-daily-hearing-list.test.ts
Labels: ns:pip, prd:pip

#1424 PUB-2749 - Fixed manual upload crash
  src/main/controllers/admin/ManualUploadSummaryController.ts
  src/test/unit/controllers/admin/ManualUploadSummaryController.test.ts
Labels: ns:pip, prd:pip

#1421 PUB-2736 Update non-strategic list frontend
  src/main/controllers/style-guide/NonStrategicTribunalListsController.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/non-strategic-common.json
  src/main/resources/locales/en/non-strategic-common.json
  src/main/views/style-guide/care-standards-list.njk
  src/main/views/style-guide/civil-and-family-daily-cause-list.njk
  src/main/views/style-guide/cop-daily-cause-list.njk
  src/main/views/style-guide/crown-daily-list.njk
  src/main/views/style-guide/crown-firm-list.njk
  src/main/views/style-guide/crown-warned-list.njk
  src/main/views/style-guide/cst-and-pht-weekly-hearing-list.njk
  src/main/views/style-guide/daily-cause-list.njk
  src/main/views/style-guide/et-daily-list.njk
  src/main/views/style-guide/et-fortnightly-list.njk
  src/main/views/style-guide/family-daily-cause-list.njk
  src/main/views/style-guide/ftt-lr-weekly-hearing-list.njk
  src/main/views/style-guide/ftt-rpt-weekly-hearing-list.njk
  src/main/views/style-guide/ftt-tax-weekly-hearing-list.njk
  src/main/views/style-guide/grc-weekly-hearing-list.njk
  src/main/views/style-guide/iac-daily-list.njk
  src/main/views/style-guide/magistrates-public-list.njk
  src/main/views/style-guide/magistrates-standard-list.njk
  src/main/views/style-guide/opa-public-list.njk
  src/main/views/style-guide/primary-health-list.njk
  src/main/views/style-guide/siac-poac-paac-weekly-hearing-list.njk
  src/main/views/style-guide/sscs-daily-list.njk
  src/main/views/style-guide/ut-aac-daily-hearing-list.njk
  src/main/views/style-guide/ut-iac-judicial-review-daily-hearing-list.njk
  src/main/views/style-guide/ut-iac-statutory-appeals-daily-hearing-list.njk
  src/main/views/style-guide/ut-lc-daily-hearing-list.njk
  src/main/views/style-guide/ut-t-and-cc-daily-hearing-list.njk
  src/main/views/style-guide/wpafcc-weekly-hearing-list.njk
  src/main/views/summary-of-publications.njk
  src/main/views/system-admin/blob-view-publications.njk
  src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
  src/test/unit/controllers/style-guide/NonStrategicTribunalListsController.test.ts
  src/test/unit/mocks/returnedArtefacts.json
  src/test/unit/modules/nunjucks/njkFilters.test.ts
  src/test/unit/views/style-guide/care-standards-list.test.ts
  src/test/unit/views/style-guide/crown-warned-list.test.ts
  src/test/unit/views/style-guide/cst-and-pht-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ftt-lr-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ftt-rpt-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ftt-tax-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/grc-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/primary-health-list.test.ts
  src/test/unit/views/style-guide/siac-poac-paac-weekly-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-aac-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-iac-judicial-review-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-iac-statutory-appeals-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-lc-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/ut-t-and-cc-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/wpafcc-weekly-hearing-list.test.ts
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1421
