Repository hmcts/pip-frontend, pull requests merged in 2025-03, with the labels that each got.

#1439 PUB-2739 Add Asylum Support Tribunal Daily Hearing List
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/ast-daily-hearing-list.json
  src/main/resources/locales/en/ast-daily-hearing-list.json
  src/main/routes/routes.ts
  src/main/views/style-guide/ast-daily-hearing-list.njk
  src/test/a11y/tests/style-guide/ast-daily-hearing-list.test.ts
  src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
  src/test/routes/style-guide/ast-daily-hearing-list.test.ts
  src/test/unit/mocks/astDailyHearingList.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/views/style-guide/ast-daily-hearing-list.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1439

#1445 Temporarily remove non-strategic list type check in e2e test
  src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1445

#1440 PUB-2721 Add Mental Health Hearing List
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/models/AdditionalLocationInfo.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/resources/additionalLocationInfoLookup.json
  src/main/resources/listLookup.json
  src/main/service/LocationService.ts
  src/main/views/summary-of-publications.njk
  src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
  src/test/end-to-end/tests/banner-navigation-test.ts
  src/test/end-to-end/tests/search-court-test.ts
  src/test/end-to-end/tests/sorting-list-table-test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/modules/nunjucks/njkFilters.test.ts
  src/test/unit/service/LocationService.test.ts
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1440

#1446 Remove list type check in e2e test
  src/test/end-to-end/tests/admin/manual-upload-non-strategic-test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1446

#1443 PUB-2750 Add frontend smoke tests
  Jenkinsfile_CNP
  jest.smoke.config.js
  package.json
  src/test/end-to-end/smoke.conf.js
  src/test/end-to-end/smoke.conf.ts
  src/test/end-to-end/tests/banner-navigation-test.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/search-court-test.ts
  src/test/smoke/healthCheck.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1443

#1450 PUB-2790 - Updated codeceptjs
  package.json
  src/test/config.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-frontend-pr-1450

#1452 Updated babel for i18next
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1452

#1377 PUB-2638 - Remove OPA lists
  src/main/controllers/SummaryOfPublicationsController.ts
  src/main/controllers/style-guide/OpaPressListController.ts
  src/main/controllers/style-guide/OpaPublicListController.ts
  src/main/controllers/style-guide/OpaResultsController.ts
  src/main/models/AdditionalLocationInfo.ts
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/opa-press-list.json
  src/main/resources/locales/cy/opa-public-list.json
  src/main/resources/locales/cy/opa-results.json
  src/main/resources/locales/en/opa-press-list.json
  src/main/resources/locales/en/opa-public-list.json
  src/main/resources/locales/en/opa-results.json
  src/main/routes/routes.ts
  src/main/service/LocationService.ts
  src/main/service/listManipulation/OpaPressListService.ts
  src/main/service/listManipulation/OpaPublicListService.ts
  src/main/service/listManipulation/OpaResultsService.ts
  src/main/views/style-guide/opa-press-list.njk
  src/main/views/style-guide/opa-public-list.njk
  src/main/views/style-guide/opa-results.njk
  src/test/a11y/tests/style-guide/opa-press-list.test.ts
  src/test/a11y/tests/style-guide/opa-public-list.test.ts
  src/test/a11y/tests/style-guide/opa-results-test.ts
  src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
  src/test/end-to-end/tests/azure-screen-flow-welsh-test.ts
  src/test/end-to-end/tests/banner-navigation-test.ts
  src/test/end-to-end/tests/hmi-publication-receipt-test.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/search-court-test.ts
  src/test/routes/style-guide/opa-press-list.test.ts
  src/test/routes/style-guide/opa-public-list.test.ts
  src/test/routes/style-guide/opa-results.test.ts
  src/test/unit/controllers/SummaryOfPublicationsController.test.ts
  src/test/unit/controllers/style-guide/OpaPressListController.test.ts
  src/test/unit/controllers/style-guide/OpaPublicListController.test.ts
  src/test/unit/controllers/style-guide/OpaResultsController.test.ts
  src/test/unit/mocks/listTypeSubscriptions/listTypes.json
  src/test/unit/mocks/opaPressList.json
  src/test/unit/mocks/opaPublicList.json
  src/test/unit/mocks/opaResults.json
  src/test/unit/mocks/returnedArtefacts.json
  src/test/unit/service/ManualUploadService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/listManipulation/OpaPressListService.test.ts
  src/test/unit/service/listManipulation/OpaPublicListService.test.ts
  src/test/unit/service/listManipulation/OpaResultsService.test.ts
  src/test/unit/views/style-guide/ast-daily-hearing-list.test.ts
  src/test/unit/views/style-guide/opa-press-list.test.ts
  src/test/unit/views/style-guide/opa-public-list.test.ts
  src/test/unit/views/style-guide/opa-results.test.ts
  src/test/unit/views/subscription-add-list.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
  src/test/unit/views/summary-of-publications.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1377

#1451 PUB-2775 - Update Accessibility Statement
  src/main/resources/locales/cy/accessibility-statement.json
  src/main/resources/locales/en/accessibility-statement.json
  src/main/views/accessibility-statement.njk
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1451

#1455 PUB-2827 - Updated chart to new version
  charts/pip-frontend/Chart.yaml
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-frontend-pr-1455
