Repository hmcts/pip-frontend, pull requests merged in 2025-05, with the labels that each got.

#1429 PUB-2730 Update calls to subscription-management
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  charts/pip-frontend/Chart.yaml
  charts/pip-frontend/values.dev.template.yaml
  charts/pip-frontend/values.yaml
  config/default.json
  frontend-arch.png
  service-diagram.png
  src/main/resources/requests/SubscriptionRequests.ts
  src/main/resources/requests/utils/axiosConfig.ts
  src/test/config.ts
  src/test/end-to-end/shared/testingSupportApi.ts
  src/test/end-to-end/tests/login-test.ts
  src/test/end-to-end/tests/system-admin/delete-court-test.ts
  src/test/unit/requests/subscriptionRequest.test.ts
  src/test/unit/resources/requests/utils/axiosConfigTest.ts
  yarn-audit-known-issues
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-frontend-pr-1429

#1473 PUB-2817 - Monthly Dependencies
  .nvmrc
  Dockerfile
  jestEnvVars.js
  package.json
  src/main/assets/scss/main.scss
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1473

#1460 PUB-2810 Add jurisdiction types to location name search filters
  src/main/controllers/AlphabeticalSearchController.ts
  src/main/controllers/SubscriptionConfigureListController.ts
  src/main/models/ListType.ts
  src/main/models/Location.ts
  src/main/resources/jurisdictionTypeLookup.json
  src/main/resources/listLookup.json
  src/main/resources/locales/cy/alphabetical-search.json
  src/main/resources/locales/cy/location-name-search.json
  src/main/resources/locales/en/alphabetical-search.json
  src/main/resources/locales/en/location-name-search.json
  src/main/resources/welshJurisdictionLookup.json
  src/main/service/FilterService.ts
  src/main/service/LocationService.ts
  src/main/service/SubscriptionService.ts
  src/main/views/alphabetical-search.njk
  src/main/views/location-name-search.njk
  src/main/views/macros/common-components.njk
  src/test/end-to-end/shared/mocks/reference-data-invalid.csv
  src/test/end-to-end/shared/mocks/system-admin-upload-reference-data-test.csv
  src/test/end-to-end/tests/a-z-list-courts-and-tribunals-test.ts
  src/test/end-to-end/tests/verified/email-subscriptions-test.ts
  src/test/routes/subscription-configure-list.test.ts
  src/test/unit/controllers/AlphabeticalSearchController.test.ts
  src/test/unit/controllers/SubscriptionConfigureListController.test.ts
  src/test/unit/mocks/courtAndHearings.json
  src/test/unit/mocks/deleteReferenceDataCourt.csv
  src/test/unit/mocks/listTypeSubscriptions/listTypeSubscriptions.json
  src/test/unit/mocks/testReferenceData.csv
  src/test/unit/service/FilterService.test.ts
  src/test/unit/service/LocationService.test.ts
  src/test/unit/service/PublicationService.test.ts
  src/test/unit/service/SubscriptionService.test.ts
  src/test/unit/views/alphabetical-search.test.ts
  src/test/unit/views/location-name-search.test.ts
  src/test/unit/views/subscription-configure-list.test.ts
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-frontend-pr-1460

#1475 PUB-2874 - Update text on home page
  src/main/resources/locales/cy/home.json
  src/main/resources/locales/en/home.json
  src/test/end-to-end/tests/unverified-user-end-to-end-journey-test.ts
  src/test/unit/views/home.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1475

#1476 PUB-2872 - Added validate on artefact ID
  src/main/controllers/system-admin/BlobViewJsonController.ts
  src/test/routes/system-admin/blob-view-json.test.ts
  src/test/unit/controllers/system-admin/BlobViewJsonController.test.ts
Labels: ns:pip, prd:pip, rel:pip-frontend-pr-1476
